### PR TITLE
Prettier

### PR DESCRIPTION
**Pull request by GarboMuffin**
instead of eslint screaming at you and me fixing all of your style issues somewhat manually, we'll just make the computer do it for you

### CODE REVIEW

**Comment by LilyMakesThings** [comment]
I think I have an idea of what this will do, but just to clarify, what _does_ this do?

**Comment by Flappy25** [comment]
Wow

**Comment by CubesterYT** [comment]
The use of prettier is going to be godly, were finally going to have a way to have a unified style.

**Comment by DNin01** [comment]
The code blocks in the docs may also need to be formatted, depending on the configuration.

**Comment by David-Orangemoon** [comment]
I already use prettier

**Pull request merged**
