### PR TITLE
ProjectCover

### PR DESCRIPTION
**Pull request by 0832k12**
Make a link.

### CODE REVIEW

**Comment by SharkPool-SP** [comment]
What

**Comment by Drago-Cuven** [comment]
what does it do? what blocks are there? why did you make it? WE NEED INFO PLEASE!

**Comment by CubesterYT** [comment]
I'm guessing this extension would be used in a case scenario where the project is just a thumbnail, and also has a bonus point of having very little file size (initially), and then imports the actual project from the link provided.

**Comment by 0832k12** [comment]
> I'm guessing this extension would be used in a case scenario where the project is just a thumbnail, and also has a bonus point of having very little file size (initially), and then imports the actual project from the link provided.

Yes.

**Comment by 0832k12** [comment]
image

**Comment by SharkPool-SP** [comment]
> I'm guessing this extension would be used in a case scenario where the project is just a thumbnail, and also has a bonus point of having very little file size (initially), and then imports the actual project from the link provided.

couldn't you just use asset manager

**Comment by RockyTheProtogen** [comment]
I can only say one thing... Why?

**Pull request closed without merging**
