### PR TITLE
Add keypressed.js

### PR DESCRIPTION
**Pull request by snowboyz0825**

### CODE REVIEW

**Comment by David-Orangemoon** [comment]
1. This is the old extension syntax for sandboxed extensions
2. Your folder is in the main instead of the extension's folder

Also this block exists in turbowarp blocks.

**Comment by snowboyz0825** [comment]
I didn't realize the block existed in the turbowarp blocks, or I would've just used that. To be honest this is my first time doing anything really on github so i'm trying to figure things out still, which is why I accidentally pushed it to main. Also, out of curiousity, where can I find the new syntax? I made it like 3 weeks ago using the turbowarp tutorial so I'd simultaniously be surprised and not surprised if it changed in the new update.

**Comment by David-Orangemoon** [comment]
> I didn't realize the block existed in the turbowarp blocks, or I would've just used that. To be honest this is my first time doing anything really on github so i'm trying to figure things out still, which is why I accidentally pushed it to main. Also, out of curiousity, where can I find the new syntax? I made it like 3 weeks ago using the turbowarp tutorial so I'd simultaniously be surprised and not surprised if it changed in the new update.

https://docs.turbowarp.org/development

**Comment by David-Orangemoon** [comment]
> > I didn't realize the block existed in the turbowarp blocks, or I would've just used that. To be honest this is my first time doing anything really on github so i'm trying to figure things out still, which is why I accidentally pushed it to main. Also, out of curiousity, where can I find the new syntax? I made it like 3 weeks ago using the turbowarp tutorial so I'd simultaniously be surprised and not surprised if it changed in the new update.
> 
> https://docs.turbowarp.org/development

Also quick note this syntax has been in use since unsandboxed extensions where officially added.

**Comment by snowboyz0825** [comment]
> > > I didn't realize the block existed in the turbowarp blocks, or I would've just used that. To be honest this is my first time doing anything really on github so i'm trying to figure things out still, which is why I accidentally pushed it to main. Also, out of curiousity, where can I find the new syntax? I made it like 3 weeks ago using the turbowarp tutorial so I'd simultaniously be surprised and not surprised if it changed in the new update.
> > 
> > 
> > https://docs.turbowarp.org/development
> 
> Also quick note this syntax has been in use since unsandboxed extensions where officially added.
I hate to ask a million questions, but what exactly was wrong with the syntax? I didn't necessarily code the thing in all honesty, I had chatgpt shorten the tutorial into something I could send in one message, and then ask to code an extension that does something. I hate to just use chatgpt but this is the first thing I've coded outside of scratch/turbowarp and I really want to learn actual coding. I have the general jist of what's needed to do (at least for extension), but I don't know any of the opcode I'd need to write to make the blocks actually work

**Comment by David-Orangemoon** [comment]
> > > > I didn't realize the block existed in the turbowarp blocks, or I would've just used that. To be honest this is my first time doing anything really on github so i'm trying to figure things out still, which is why I accidentally pushed it to main. Also, out of curiousity, where can I find the new syntax? I made it like 3 weeks ago using the turbowarp tutorial so I'd simultaniously be surprised and not surprised if it changed in the new update.
> > > 
> > > 
> > > https://docs.turbowarp.org/development
> > 
> > 
> > Also quick note this syntax has been in use since unsandboxed extensions where officially added.
> 
> I hate to ask a million questions, but what exactly was wrong with the syntax? I didn't necessarily code the thing in all honesty, I had chatgpt shorten the tutorial into something I could send in one message, and then ask to code an extension that does something. I hate to just use chatgpt but this is the first thing I've coded outside of scratch/turbowarp and I really want to learn actual coding. I have the general jist of what's needed to do (at least for extension), but I don't know any of the opcode I'd need to write to make the blocks actually work

Its still written the old way and this would be maintained by other people on this github page who want the new turbowarp syntax.

**Pull request closed without merging**
