### PR TITLE
Update comment blocks.

### PR DESCRIPTION
**Pull request by SurvExe1Pc**
Adds matrix comments, and also color comments.
sadly since C-Blocks don't work i could not add them 😭.

### CODE REVIEW

**Comment by GarboMuffin** [comment]
@LilyMakesThings this is your extension

do you agree with this?

**Comment by LilyMakesThings** [comment]
I don't like this. I'd prefer people to use a coupler for these values.

**Comment by NexusKitten** [comment]
> I don't like this. I'd prefer people to use a coupler for these values.
> 
> Adding a comment to a color or matrix value is so niche that, for the one person who is **going** to do that, they should just use the extra block to do that if it keeps this palette to a minimum.

It's worth noting there's not currently a matrix/color coupler in any extensions (other than LMS utils, which is currently unlisted). If these blocks were in couplers i'd be inclined to agree, but as it stands, they are not.

**Comment by GarboMuffin** [comment]
related: https://github.com/TurboWarp/extensions/pull/757

**Comment by GarboMuffin** [comment]
Similar blocks are in couplers now

**Pull request closed without merging**
