### PR TITLE
Revert "Lily/ClonesPlus.js -- Improve Performance of "when I start as...""

### PR DESCRIPTION
**Pull request by CubesterYT**
Reverts TurboWarp/extensions#1759

Someone on Discord already got an issue with it. It's breaking projects.
We need this merged ASAP

CC @SharkPool-SP
You got to be kidding me, it was working for ten people, why break now??

### CODE REVIEW

**Comment by SharkPool-SP** [comment]
Wait don't revert it. I know the issue

**Comment by GarboMuffin** [comment]
Try again tomorrow

**Comment by SharkPool-SP** [comment]
> Try again tomorrow

I could of fixed it today

**Comment by GarboMuffin** [comment]
You can send it today and if you're really confident you could merge it again

**Pull request merged**
