### PR TITLE
New Extension: MIDI

### PR DESCRIPTION
**Pull request by Brackets-Coder**
This is a very small and simple extension that adds MIDI input handling. While it could be updated to support MIDI output controlling in the future, that functionality is not currently supported. This extension was written very quickly and it's my first pull request so the quality may not be the best, but here's a quick look:
Screenshot 2024-07-30 at 9 46 34 PM
I also have a sample project ready to include but I'm going to wait until the extension is released before I add that to the repository.

### CODE REVIEW

**Comment by Brackets-Coder** [comment]
Since this is still in its very early stages, it has more room for updates. Right now it only supports MIDI input, and even then only the detection of keys. Future plans include other MIDI input events such as pedals, pitch bend, or other keyboard controls and MIDI output devices.

**Comment by CubesterYT** [comment]
As I said in the thread, let me know when you're ready with this extension, and I'll go ahead with the formalities.

**Comment by Brackets-Coder** [comment]
> As I said in the thread, let me know when you're ready with this extension, and I'll go ahead with the formalities.

Ok. It's ready to merge now. There may be a few undiscovered bugs because it was written quickly but in my testing it works great. I tried to fix format but I couldn't get prettier to work so if you could help me with that I'd appreciate it.

**Comment by Brackets-Coder** [comment]
> As I said in the thread, let me know when you're ready with this extension, and I'll go ahead with the formalities.

@CubesterYT I'm ready for this whenever you are

**Comment by Brackets-Coder** [comment]
So I've run the npx prettier write command on my file and re-committed but it still says format failed. I have the same config and prettier version as the repo, so I don't really know what's wrong. I'll let someone else deal with format when this gets reviewed sometime in the next 10 years (over exaggeration)

**Comment by Thebloxers998** [comment]
> So I've run the npx prettier write command on my file and re-committed but it still says format failed. I have the same config and prettier version as the repo, so I don't really know what's wrong. I'll let someone else deal with format when this gets reviewed

Are there any bugs

**Comment by Brackets-Coder** [comment]
> > So I've run the npx prettier write command on my file and re-committed but it still says format failed. I have the same config and prettier version as the repo, so I don't really know what's wrong. I'll let someone else deal with format when this gets reviewed
> 
> Are there any bugs

This is old. See #1637

**Pull request closed without merging**
