### PR TITLE
Add battery extension

### PR DESCRIPTION
**Pull request by GarboMuffin**
https://github.com/TurboWarp/extensions/issues/493#issuecomment-1570967970

### CODE REVIEW

**Comment by LukeManiaStudioss** [comment]
The fact this works on laptops too makes me happier than it has any right to.

**Comment by GarboMuffin** [comment]
need to add a note to the description that it "may not work on all devices and browser"

**Comment by Martinelplayz** [comment]
NICE! when is this getting merged?

**Comment by Martinelplayz** [comment]
Battery Extension
Battery Extension

PNG and SVG. My own Thumbnail for this ext

**Pull request merged**
