### PR TITLE
Add a new extension rxFS

### PR DESCRIPTION
**Pull request by 0832k12**

### CODE REVIEW

**Comment by TheShovel** [comment]
You should maybe translate the text on the blocks to English, because that's the language most TurboWarp users know.

**Comment by 0832k12** [comment]
I translate the text on the blocks to English.

**Comment by 0832k12** [comment]
image

**Comment by 0832k12** [comment]
image

**Comment by 0832k12** [comment]
This is a filesystem! Most filesystem functions, such as searching and creating deleted files, have been supported.

**Comment by 0832k12** [comment]
View [there](https://0832k12.github.io/rxFS/rxFSen.js)

**Pull request closed without merging**
