### PR TITLE
TheShovel/ColorPicker: add sample project

### PR DESCRIPTION
**Pull request by DNin01**
Adds a sample project that uses the Color Picker extension called "Recolor the Dango".

### CODE REVIEW

**Comment by GarboMuffin** [comment]
do you actually need the wait (0.01)? seems to work for me without it

**Comment by DNin01** [comment]
> do you actually need the wait (0.01)? seems to work for me without it

When I was testing, the color picker's position wouldn't update the first time I click, which is why I added the delay.

**Comment by DNin01** [comment]
https://github.com/TurboWarp/extensions/assets/106490990/2cee9732-72a1-4861-9965-e6adaedaf4a5

**Comment by DNin01** [comment]
I have removed the delay because #1365 was opened.

**Pull request merged**
