### PR TITLE
Add More Event Extension

### PR DESCRIPTION
**Pull request by mark-alex2004**
This extension adds more event to turbowarp

### CODE REVIEW

**Comment by LilyMakesThings** [comment]
Hi! I submitted a more events extension recently too. Would you like to collaborate on making an events extension? It seems pointless to have 2 :P https://github.com/TurboWarp/extensions/pull/639

**Comment by horizontal-shading** [comment]
There's already an extension planned to be added like this.
#639

**Comment by mark-alex2004** [comment]
Sorry I did not check requests, will close

**Comment by LilyMakesThings** [comment]
> Sorry I did not check requests, will close

I really liked this extension! If you want I could merge some of the blocks with mine and you can take half the credit, like a collab :D

**Comment by mark-alex2004** [comment]
> > Sorry I did not check requests, will close
> 
> I really liked this extension! If you would be interested, I'd like to merge some of the blocks with mine and you can take half the credit, like a collab :D

Yes you can use

**Pull request closed without merging**
