### PR TITLE
Update rxFS2.js

### PR DESCRIPTION
**Pull request by 0832k12**
Add Translation

### CODE REVIEW

**Comment by GarboMuffin** [comment]
extension source code must not be minified

**Comment by GarboMuffin** [comment]
also, we do not really want extensions to be translated by hand. we will automate it and send it to the translators that do the rest of our websites. this is fine for now though

**Comment by 0832k12** [comment]
> extension source code must not be minified

Why?

**Comment by 0832k12** [comment]
Lint wrong.

**Comment by LukeManiaStudioss** [comment]
> > extension source code must not be minified
> 
> Why?

Readability.

**Comment by GarboMuffin** [comment]
Per the GPLv3 that all files in this repository must be compatible with, the "preferred form of the work for making modifications to it" must be made available

**Comment by 0832k12** [comment]
I fixed a format error.

**Comment by NOname-awa** [comment]
> also, we do not really want extensions to be translated by hand. we will automate it and send it to the translators that do the rest of our websites. this is fine for now though

I think we can add both the native language and English.

**Comment by GarboMuffin** [comment]
due to some bugs in turbowarp desktop v1.7.2-beta.1, we will have to wait a bit for this

**Comment by GarboMuffin** [comment]
We will tolerate these manual translations from native speakers for now as a way to test the l10n system

Other contributors: please do not start writing translations by hand for languages you are not fluent in!

**Pull request merged**
