### PR TITLE
Add a run Javascript extension

### PR DESCRIPTION
**Pull request by powershell-data-download**
image

You can use this extension to run simple JS code and APIs. I would love to hear your opinions, maybe to change something. If I did something wrong, please tell me, because this is my first proper extension.

Also, could someone help me with the checks? I would be very thankful. 😀👍

### CODE REVIEW

**Comment by CubesterYT** [comment]
This extension will undoubtedly be denied. Eval is banned from use in TW Extensions due to it being able to run malicious code.

You can find more about it here, which is a preexisting PR for a JS extension: https://github.com/TurboWarp/extensions/pull/570

**Comment by softedco** [comment]
Please read [CONTRIBUTING.md](https://github.com/TurboWarp/extensions/blob/master/CONTRIBUTING.md)
You are not passing the checks because eval and arbitrary js evaluation are not allowed.

**Comment by GarboMuffin** [comment]
see above

**Comment by LIZARD-OFFICIAL** [comment]
i don't like how garbomuffin is putting devs into a guardrail like chatgpt.

**Comment by LilyMakesThings** [comment]
GarboMuffin is extremely lenient about what is accepted. Getting extensions accepted is not a right it's a privilege and the safeguards that are in place for extensions on the gallery for things like eval are there to protect people from losing their scratch accounts, credit card details, etc.

It is listed in the contributing guidelines, that I am sure you read before submitting this, that extensions with unrestricted eval will not be accepted.

If you would like to share the extension with friends you still can, just not on the gallery. Also maybe inform them how extremely dangerous it is.

**Pull request closed without merging**
