### PR TITLE
Add sound extension

### PR DESCRIPTION
**Pull request by softedco**
image
As suggested in #92
Playing sound from device didn't make it there because chrome blocks it.

### CODE REVIEW

**Comment by Mickmick2012** [comment]
is it possible to add "play sound from url until done" ?

**Comment by softedco** [comment]
> is it possible to add "play sound from url until done" ?

Yes

**Comment by CST1229** [comment]
#100

**Comment by GarboMuffin** [comment]
Rewrite this to use Scratch's AudioContext `vm.runtime.audioEngine.audioContext` instead of plain Audio elements. I think there's something like a "media element source". Otherwise this won't be able to reliably play audio in browsers that have autoplay disabled.

**Review by GarboMuffin — CHANGES_REQUESTED** [review]
See above

**Review by GarboMuffin — COMMENTED** [review]
Made some changes:

 - It will first try to play the sound using Scratch's audio engine, which means it'll integrate with volume, pitch, pan left/right, etc.
 - If the sound can't be played that way (most likely because the URL does not support CORS), it will instead just use an <audio> element, like the original version.

**Comment by SIPC** [comment]
Is it possible to add "pause [url]" and 'suspend all'?

**Comment by softedco** [comment]
> Is it possible to add "pause [url]" ？

From the audio element it is, but I don't know if it is possible with the audioEngine.

**Comment by GarboMuffin** [comment]
It will be possible in audio engine, just a good bit more annoying

**Comment by GarboMuffin** [comment]
We'll do pausing later

**Comment by GarboMuffin** [comment]
Whoever wants pausing: Open a new issue and describe which exact blocks you would like. There's a lot of ways this could be done and I don't want to have to change it later.

**Pull request merged**
