### PR TITLE
CrazyGames SDK Extension

### PR DESCRIPTION
**Pull request by softedco**
[SDK](https://sdk.crazygames.com/crazygames-sdk-v1.js)
[Docs](https://docs.crazygames.com/sdk/html5)

crazygames

Should work from the editor right away, but it won't get link data, check if the user has AdBlock and display ads, instead there would be an overlay:

overlay

Unfortunately, once you request an ad, the only way to get rid of the overlay is to refresh the page.

### CODE REVIEW

**Comment by GarboMuffin** [comment]
I imagine that their SDK is very much not open source, yes?

**Comment by softedco** [comment]
> I imagine that their SDK is very much not open source, yes?

As far as I can tell, the only publicly available version is minified.

**Comment by imya505222** [comment]
so extension will be added ?

**Comment by softedco** [comment]
> so extension will be added ?

I emailed crazygames developer support for license information, we'll see how it goes

**Comment by GarboMuffin** [comment]
I am assuming that the library is not available under a license that is GPL compatible, so unfortunately I am unable to include it here.

I will say that, regardless of license, accommodating a purely commercial game site littered with ads in this free open source project is not a high priority.

Anyone who is interested in this sort of integration is free to contact: contact@turbowarp.org

**Comment by Martinelplayz** [comment]
i imagine i could make use if this if everything were to work the way it should.

**Pull request closed without merging**
