### PR TITLE
New "contact" extension

### PR DESCRIPTION
**Pull request by samuellouf**
An extension to send e-mails, pass phone calls, use Skype...

### CODE REVIEW

**Comment by GalacticCoder922** [comment]
I'm pretty sure this would be a no.

**Comment by CST1229** [comment]
> I'm pretty sure this would be a no.

At least, it definitely wouldn't belong on the gallery home page.

**Comment by CubesterYT** [comment]
Oooo this extension is a definite security risk, but a very cool idea though. I like it but just won't see it come to light...

**Comment by samuellouf** [comment]
Ok, thanks.

**Comment by samuellouf** [comment]
I added another extension.
A "Chat GPT" extension. Based on : [Donutask's "AI" extension](https://www.youtube.com/watch?v=hSnFf_YT5qk)
I will not give the API KEY for the moment but it works.
You can get your own on OpenIA's website.

**Comment by CubesterYT** [comment]
Ok, two things, one, the chatgpt extension should've been a sperate PR for review. Two, as discussed prior, have a chatgpt extension is great but a massive security issue for those adding their private key to a project, and that private key being found and abused. It has been discussed in other chatgpt extension PRs.

**Comment by samuellouf** [comment]
Ok.

**Comment by samuellouf** [comment]
> ...as discussed prior, have a chatgpt extension is great but a massive security issue for those adding their private key to a project, and that private key being found and abused. It has been discussed in other chatgpt extension PRs.

The person using the extension needs his own API Key.

full block

**Comment by SurvExe1Pc** [comment]
> > ...as discussed prior, have a chatgpt extension is great but a massive security issue for those adding their private key to a project, and that private key being found and abused. It has been discussed in other chatgpt extension PRs.
> 
> The person using the extension needs his own API Key.
> 
> full block

Thats still dangerous

**Comment by kindpump** [comment]
You can do this using IFTTT webhooks using my IFTTT extension: https://[kindpump.github.io/extensions/ifttt.js](https://kindpump.github.io/extensions/ifttt.js). All you need is an IFTTT account and to set up a webhook and then use your private webhook key. I may further documentation on this extension in the future but it's capable of doing some impressive stuff. I've gotten it to connect to my smart lights and change them. This should avoid the privacy concerns mentioned by other users as it's using a third party webhook service to send texts or emails.

**Comment by samuellouf** [comment]
I think I'm gonna give up these extensions

**Comment by CubesterYT** [comment]
@samuellouf There's no reason to give up. You can still develop these extensions on your own by adding them to your own GitHub site to contain these extensions so that people can still use them if they want. The contact extension is something I would actually use for example. So it would be great if you kept it up on your own.

**Pull request closed without merging**
