### PR TITLE
Added my "iFrame"

### PR DESCRIPTION
**Pull request by samuellouf**
Hi, I made an iFrame extension. Most of the constructor was edited and is originally from @LilyMakesThings's video extension. Most of the blocks and the colors are from [PenguinMod's iFrame extension](https://github.com/PenguinMod/PenguinMod-Vm/blob/develop/src/extensions/jg_iframe/index.js) but I edited most of the code.

With iFrame, you can:
-  Load an URL
loadurl
- Load an YouTube video
loadyoutubevideo
- Show/Hide iFrame
showhideiframe
- show/hide iFrame border
showhideiframeborder
- Change and get iFrame width/height
changegetiframewidthheight
- Set/change 𝑥 and 𝑦
setchangexny
- Set iFrame rotation
setiframerotation
- Set/change/remove/get a visual effect on the iFrame (color, grayscale, brightness, contrast, ghost, blur, invert, saturate and sepia)
setchangeremovegetvisualeffectoniframe

### CODE REVIEW

**Comment by NexusKitten** [comment]
While I hope this gets added, it's unlikely to be on the gallery... #448 was a straight port from PenguinMod, and it got rejected. Maybe ask for permission from the user before you open an iFrame?

**Comment by BlueToadMakerr** [comment]
Add a block to reset the position

**Comment by BlueToadMakerr** [comment]
iFrame positioning is different to Sprite positioning

**Comment by samuellouf** [comment]
> 
tbh I think a friend of mine added this.

**Comment by Cbr2011** [comment]
i like to see this extension be in turbowarp. But I highly doubt it's gonna be merged.
because first. 

> image

and

image
[this comment is from #448]

**Comment by JeremyGamer13** [comment]
the youtube support seems really unnecessary considering its not even related to youtube

**Comment by OeildeLynx31** [comment]
Can you add a block to set the HTML content? Without the user needs to use data.URI!

**Pull request closed without merging**
