### PR TITLE
Xmer Utilities

### PR DESCRIPTION
**Pull request by XmerStudio**
A lot of Advanced Tools!

### CODE REVIEW

**Comment by CST1229** [comment]
Please read [CONTRIBUTING.md](https://github.com/TurboWarp/extensions/blob/master/CONTRIBUTING.md)!

> Strictly, nothing is banned, but the following are *highly* discouraged:
> 
> - **Broad "Utilities" extensions (break them up into multiple extensions, see https://github.com/TurboWarp/extensions/issues/674)**
> - **Extensions that are very similar to existing ones (consider modifying the existing one instead)**
> - One-use personal extensions (load the extension as a local file instead)
> - Extensions whose primary purpose is monetization (not in the spirit of an open source project)
> - Joke extensions (they aren't funny when they cause us to get bug reports)

**Comment by LilyMakesThings** [comment]
This extension will inevitably be declined because we do not except Utilities extensions as per the Contributing Guidelines ([CONTRIBUTING.md](https://github.com/TurboWarp/extensions/blob/master/CONTRIBUTING.md))

**Comment by XmerStudio** [comment]
> This extension will inevitably be declined because we do not except Utilities extensions as per the Contributing Guidelines ([CONTRIBUTING.md](https://github.com/TurboWarp/extensions/blob/master/CONTRIBUTING.md))

i named it like that because I couldn't find a name.

**Comment by LilyMakesThings** [comment]
> > This extension will inevitably be declined because we do not except Utilities extensions as per the Contributing Guidelines ([CONTRIBUTING.md](https://github.com/TurboWarp/extensions/blob/master/CONTRIBUTING.md))
> 
> i named it like that because I couldn't find a name.

It's not the name, it's the extension itself. "Utility" extensions without a consistent theme are not allowed.

**Comment by XmerStudio** [comment]
How can you respond so quickly? Also, have you tried the extension?

**Comment by LilyMakesThings** [comment]
After having to modify the code manually just to get it to function, I can safely say this is not going to be accepted.
image

**Comment by XmerStudio** [comment]
I think you turned off unsandboxed for your security, it doesn't load when it's off, no need to fix it manually when it's on. never mind, also do you wait 24/7 on github, you respond very fast.

**Comment by qxsck** [comment]
image
it is bad

**Comment by XmerStudio** [comment]
I made the code in notepad++. When I look at it from vs code, it looks really complicated.

**Comment by XmerStudio** [comment]
you can use any part of the code you want.

**Pull request closed without merging**
