### PR TITLE
Add Perlin-Noise

### PR DESCRIPTION
**Pull request by SharkPool-SP**
Simple Perlin Noise Extension utilizing built in methods and not libraries 👍 
image

### CODE REVIEW

**Comment by WAYLIVES** [comment]
Hello, cool extension!!! I just didn't quite understand how to work with it. Could you show through the screenshots what can be done with this extension?

**Comment by SharkPool-SP** [comment]
> Hello, cool extension!!! I just didn't quite understand how to work with it. Could you show through the screenshots what can be done with this extension?

Basically you generate noise which can be used for making terrain in 2d or 3d games.

**Comment by WAYLIVES** [comment]
> > Hello, cool extension!!! I just didn't quite understand how to work with it. Could you show through the screenshots what can be done with this extension?
> 
> Basically you generate noise which can be used for making terrain in 2d or 3d games.

Oh, OK, got it ;)

**Comment by c00lkase** [comment]
really cool extension! it can probably fix the formatting issue if you run `npx prettier --write path/to/file.js`

**Comment by SharkPool-SP** [comment]
The problem is idk where to run that

**Comment by c00lkase** [comment]
You can run it anywhere as long as the path given leads to your JavaScript file

**Comment by SharkPool-SP** [comment]
> You can run it anywhere as long as the path given leads to your JavaScript file

What counts as "anywhere"

**Comment by CST1229** [comment]
> really cool extension! it can probably fix the formatting issue if you run `npx prettier --write path/to/file.js`

no, use `npm run format` in the repo folder (so it gets formatted according to the repo's rules)

**Comment by c00lkase** [comment]
> no, use npm run format in the repo folder (so it gets formatted according to the repo's style)

ohh ok, i saw that way but i've used the way i recommended and ended up passing all checks

**Comment by SharkPool-SP** [comment]
> > really cool extension! it can probably fix the formatting issue if you run `npx prettier --write path/to/file.js`
> 
> no, use `npm run format` in the repo folder (so it gets formatted according to the repo's style)

wheres that

**Comment by c00lkase** [comment]
repo folder is the folder you pulled the repository from

**Comment by SharkPool-SP** [comment]
> repo folder is the folder you pulled the repository from

Do you have a video, sorry for being stupid but have 0 idea what's going on

**Comment by CST1229** [comment]
> > > really cool extension! it can probably fix the formatting issue if you run `npx prettier --write path/to/file.js`
> > 
> > 
> > no, use `npm run format` in the repo folder (so it gets formatted according to the repo's style)
> 
> wheres that
it's the folder that contains the package.json and stuff, it looks like this

image

**Comment by SharkPool-SP** [comment]
> > > > really cool extension! it can probably fix the formatting issue if you run `npx prettier --write path/to/file.js`
> 
> > > 
> 
> > > 
> 
> > > no, use `npm run format` in the repo folder (so it gets formatted according to the repo's style)
> 
> > 
> 
> > wheres that
> 
> 
> 
> it's the folder that contains the package.json and stuff, it looks like this
> 
> 
> 
> image
> 
> 

So I have to download the repo to my computer?

**Comment by c00lkase** [comment]
You needed to follow the "A better development server" step, which had you pull the repo to your computer

**Comment by SharkPool-SP** [comment]
Deprecated:

https://github.com/TurboWarp/extensions/pull/1815

**Pull request closed without merging**
