### PR TITLE
New Extension: Project Translate

### PR DESCRIPTION
**Pull request by RBryanYT**
This is a basic extension I made that allows you to translate your projects into multiple languages. Currently, it only supports 4 languages, but that will be expanded soon.

Here is an image showing some functionality:
Example Image

**Note:** This is my first pull request, so sorry if it isn't high quality.

### CODE REVIEW

**Comment by qxsck** [comment]
may be more convenient to allow creators to customize their own language directly

**Comment by CubesterYT** [comment]
How come this was closed?

**Comment by Thebloxers998** [comment]
> How come this was closed?

I think it was closed because this already exists and it was made by the scratch team

**Comment by CST1229** [comment]
> > How come this was closed?
> 
> I think it was closed because this already exists and it was made by the scratch team

Not really. Scratch's Translate extension is a translation API, while this is for handmade localization strings (but that could just be a dictionary).

**Pull request closed without merging**
