### PR TITLE
Update var-and-list.js

### PR DESCRIPTION
**Pull request by qxsck**
#690 Adjustments have been made based on this.

### CODE REVIEW

**Comment by GarboMuffin** [comment]
we are not going to be coloring blocks like this at this time

**Comment by qxsck** [comment]
> 我们目前不会像这样着色块

sorry

**Comment by Faris90** [comment]
> we are not going to be coloring blocks like this at this time

@GarboMuffin and why not?

**Comment by LilyMakesThings** [comment]
> > we are not going to be coloring blocks like this at this time
> 
> @GarboMuffin and why not?

I'm not GarboMuffin but I assume it's because at the moment, it's really hacky and untested. 

There's also no benefit for using this. Just colour your blocks like normal.

**Pull request closed without merging**
