### PR TITLE
Add McUtils

### PR DESCRIPTION
**Pull request by LukeManiaStudioss**
Self explanatory, it's mcutils, the best extension ever.

### CODE REVIEW

**Comment by TheShovel** [comment]
What in the world is this.

**Comment by NexusKitten** [comment]
> What in the world is this.

I dont know but i'm not exactly lovin' it

**Comment by TheShovel** [comment]
I just realized it's called McUtils because it means McDonald's utils. Truly one of the extensions of all time.

**Comment by NexusKitten** [comment]
I'm now in fact lovin' it

**Comment by David-Orangemoon** [comment]
10/10 would use again

**Comment by JeremyGamer13** [comment]
Now I'm truly lovin' it

**Comment by Mickmick2012** [comment]
i will laugh if this gets added

**Comment by NOVASPIDERULTRA** [comment]
bruh i can't order ice cream

**Comment by NOVASPIDERULTRA** [comment]
too realistic,,,,

**Comment by LoserFox** [comment]
bro now not 4.1
but i like it , just add it!

**Comment by Mickmick2012** [comment]
*_Laughs_*

**Pull request merged**
