### PR TITLE
Alert Extension

### PR DESCRIPTION
**Pull request by TheYali1**
Basically, what the extension does is display these Chrome notifications

image
image
image

And it can also create such notifications

image

**(sorry but my pc is in hebrew ^_^)**

### CODE REVIEW

**Comment by SharkPool-SP** [comment]
all these blocks exist in other extensions:
LMS utils, Notifications

**Comment by Thebloxers998** [comment]
> all these blocks exist in other extensions: LMS utils, Notifications

Yep

**Comment by snowboyz0825** [comment]
> all these blocks exist in other extensions: LMS utils, Notifications

doesn't everyone tell people not to use LMS

**Comment by LilyMakesThings** [comment]
> > all these blocks exist in other extensions: LMS utils, Notifications
> 
> doesn't everyone tell people not to use LMS

Sometimes I feel like I'm the only person saying that

**Comment by CubesterYT** [comment]
These blocks exist in the Notification extension, if you have new blocks that the Notification extension doesn't have, please contribute to that extension instead. Thank you.

**Pull request closed without merging**
