### PR TITLE
Clipping & blending: Update name and menu icon

### PR DESCRIPTION
**Pull request by Xeltalliv**

### CODE REVIEW

**Comment by True-Fantom** [comment]
It seems to me that you need to write `blending` with a capital letter.
Since in Scratch the extension names are arranged like this:
Скриншот 10-03-2023 153346

**Comment by True-Fantom** [comment]
And update name on the homepage, please)

**Comment by Xeltalliv** [comment]
Already done that in the first commit

**Comment by True-Fantom** [comment]
I mean the capital letter, too

Скриншот 10-03-2023 155015

**Comment by True-Fantom** [comment]
👍

**Pull request merged**
