### PR TITLE
More Sensors

### PR DESCRIPTION
**Pull request by G1nX-01**
okay so
this extension is able to get the user's language code, as well as if they have headphones.
it has 2 time-related blocks. the first one will transform a date into a relative timestamp ("1 day ago" or "in 77 days")
and the other will make a real-time countdown based on your timezone for any future date.
that's all. i plan to add an icon if i can.

### CODE REVIEW

**Comment by LilyMakesThings** [comment]
I like the utility of this extension, especially being able to detect language codes as well as if the user has headphones! However, there is an existing extension called Sensing+, is there any reason why these blocks can't just go into that extension?

**Comment by SurvExe1Pc** [comment]
a year is 365.256363004 days or shortened to 365.24 days because leap year, does it account for that or?

**Comment by G1nX-01** [comment]
> I like the utility of this extension, especially being able to detect language codes as well as if the user has headphones! However, there is an existing extension called Sensing+, is there any reason why these blocks can't just go into that extension?

ok

**Comment by G1nX-01** [comment]
> a year is 365.256363004 days or shortened to 365.24 days because leap year, does it account for that or?

Oh yea i don't really know. I'll have to check.

**Comment by SurvExe1Pc** [comment]
> > a year is 365.256363004 days or shortened to 365.24 days because leap year, does it account for that or?
> 
> Oh yea i don't really know. I'll have to check.

some math to show it, https://www.wolframalpha.com/input?i=floor%28%28365.24*4%29%2F365%29

**Pull request merged**
