### PR TITLE
Block to verify if the string is Base64

### PR DESCRIPTION
**Pull request by TheShovel**
image

### CODE REVIEW

**Comment by TheShovel** [comment]
I am not going to bother with Eslint. Someone else make it happy.

**Comment by LukeManiaStudioss** [comment]
It's 4 errors my g

**Comment by TheShovel** [comment]
I don't know what the terms mean. I tried doing stuff like how Eslint says but it just caused more issues. The extension works just fine, it's complaining that it's not formated how GarboMuffin wants.

**Comment by LukeManiaStudioss** [comment]
On line 260:
`if (args.string === '' || args.string.trim() === '') {`
`     return false;`
`}`

**Comment by TheShovel** [comment]
Happy?

**Pull request merged**
