### PR TITLE
NexusKitten/controlcontrols: Highlight block

### PR DESCRIPTION
**Pull request by DNin01**
I added a block that can play an animation to highlight any one of the four project control buttons. It can be useful to make buttons that you want the user to click pop out more, and to create effect.

Some examples:

https://github.com/TurboWarp/extensions/assets/106490990/c84efa9f-5f64-425e-b1bb-ff7bed3e9b32

### CODE REVIEW

**Comment by GarboMuffin** [comment]
Did you test in packager?

**Comment by DNin01** [comment]
> Did you test in packager?

No.

**Comment by veggiecan0419** [comment]
@DNin01 May I also add this to #1487?

**Comment by DNin01** [comment]
> @DNin01 May I also add this to #1487?

Yes, go ahead!

**Comment by AshimeeAlt** [comment]
This is epic

**Comment by GarboMuffin** [comment]
if you are going to copy this then see also https://github.com/TurboWarp/extensions/pull/1533

**Pull request merged**
