### PR TITLE
Add Key-Bindings

### PR DESCRIPTION
**Pull request by SurvExe1Pc**
Allows you to set custom key-binds.
Blocks:
image
Icon:
image
https://icons8.com/icon/34922/ctrl

### CODE REVIEW

**Comment by SurvExe1Pc** [comment]
Btw this was made in 7-8hrs on no sleep so it might be bad lol, I will gladly take criticism.

**Comment by SurvExe1Pc** [comment]
image
works as intended now
and 
image
was added

**Comment by SurvExe1Pc** [comment]
updated broadcast/whenrecived blocks + the inner version
image

**Comment by gomiigg** [comment]
this is really cool cause if been trying to use lists and variables to get customizable keybinds working so this makes it so much simpler

**Comment by gomiigg** [comment]
actually wait im having trouble setting multiple keys how am i supposed to format them

**Comment by SurvExe1Pc** [comment]
@LilyMakesThings pointed out some bugs so its a draft for rn

**Comment by SurvExe1Pc** [comment]
> actually wait im having trouble setting multiple keys how am i supposed to format them

its key and then space and then key

**Comment by SurvExe1Pc** [comment]
image

**Pull request closed without merging**
