### PR TITLE
OpenAI Extension

### PR DESCRIPTION
**Pull request by Twingamerdudes**
The OpenAI extension adds OpenAI API support to TurboWarp. It supports text and chat completions.

image

### CODE REVIEW

**Comment by LukeManiaStudioss** [comment]
this is the second OpenAI extension in the PRs now, wow

**Comment by Twingamerdudes** [comment]
That's what happens when your app becomes the fastest growing lol

**Comment by LukeManiaStudioss** [comment]
> That's what happens when your app becomes the fastest growing in history lol

true 😂

yours appears to be different anyway so I don't think it's even a problem lol, not that it would've been to begin with

**Comment by Twingamerdudes** [comment]
Thanks!

**Comment by GarboMuffin** [comment]
the reason the other PR is stalled is because storing the API key inside the project is very scary and will almost definitely cause someone's credit card to be charged for API requests they didn't make. IF possible I would prefer these types of extensions to have some custom UI that they use to ask for the API key rather than storing it in the scripts

**Comment by LukeManiaStudioss** [comment]
> the reason the other PR is stalled is because storing the API key inside the project is very scary and will almost definitely cause someone's credit card to be charged for API requests they didn't make. IF possible I would prefer these types of extensions to have some custom UI that they use to ask for the API key rather than storing it in the scripts

Like creating a variable?

**Comment by Twingamerdudes** [comment]
The problem with a secure system is how it works. Would it be a proxy server the dev has to setup? Would it be encryption (it can't be sha256 or md5 for obvious reasons)? I will look into it further

**Comment by zmh-program** [comment]
hey! I wrote an openai extension with built-in apikey. Would you like to take a look?

[turbowarp-openai](github.com/zmh-program/turbowarp-openai)

**Comment by LukeManiaStudioss** [comment]
> hey! I wrote an openai extension with built-in apikey. Would you like to take a look?
> 
> github.com/zmh-program/turbowarp-openai [turbowarp-openai](github.com/zmh-program/turbowarp-openai)

please submit a pull request instead of commenting about new extensions on existing ones

**Comment by zmh-program** [comment]
> > hey! I wrote an openai extension with built-in apikey. Would you like to take a look?
> > github.com/zmh-program/turbowarp-openai [turbowarp-openai](github.com/zmh-program/turbowarp-openai)
> 
> please submit a pull request instead of commenting about new extensions on existing ones

Thanks, I know. And I'm trying to figure out how to adapt the extension (because I write based on `Turbowarp-ClipX` and `typescript`).

**Comment by zmh-program** [comment]
#497

**Pull request closed without merging**
