### PR TITLE
New extension: Zip

### LINKED ISSUE #209: Scratch ZIP Extension
This extension would be fantastic, adding blocks to interact with ZIP files, full zip interaction not just loading it too, the ability to make a custom file extension by renaming a zip would be cool too, this would be amazing for mod support.

### PR DESCRIPTION
**Pull request by CST1229**
Resolves #209 
Goes well with #700, although that PR isn't required to be merged first (or the other way around)

A zip extension which has most zip things (at least, things that JSZip can do, so no encrypted archives or rar support or stuff like that). However, it *can* open (and probably output) .sb3 files!

### CODE REVIEW

**Comment by LilyMakesThings** [comment]
You're spoiling us 😭

**Comment by David-Orangemoon** [comment]
I'm just going to casually save this.

**Comment by SurvExe1Pc** [comment]
AUGHWFHUIHFQ I tried to make this and failed, like oml this is so awesome, been waiting for this for like forever i like this, it is must add, (tldr: very cool, must add)

**Comment by GarboMuffin** [comment]
do you consider this done?

**Comment by gomiigg** [comment]
does this mean that a web or desktop build of a game can load data from within itself an different times instead of having to load all data at once?

**Comment by CST1229** [comment]
> do you consider this done?

after the above 3 commits, yes

**Comment by ClaytonTDM** [comment]
YES

**Comment by echoless3484** [comment]
YES

**Comment by LilyMakesThings** [comment]
YES

**Comment by PuzzlingGGG** [comment]
YES

**Comment by SurvExe1Pc** [comment]
YES

**Comment by OeildeLynx31** [comment]
YES

**Comment by TheShovel** [comment]
YES

**Comment by Flappy25** [comment]
Yes

**Comment by GarboMuffin** [comment]
if you want, your user folder can be just `CST`, or I will merge this tonight

**Comment by CST1229** [comment]
YES

**Pull request merged**
