### PR TITLE
Functions: Add Functions extension

### PR DESCRIPTION
**Pull request by LilyMakesThings**
image

### CODE REVIEW

**Comment by Skyhigh173** [comment]
it will take another 6 months to merge :trollface:

**Comment by FurryR** [comment]
This extension is buggy in interpreter. It is because of wrong usage of `stackFrame` and `util.yield()`.
image-4

**Comment by qxsck** [comment]
> it will take another 6 months to merge :trollface:

why

**Comment by mcnole25** [comment]
> it will take another 6 months to merge :trollface:

7*

**Comment by BlueDome77** [comment]
> > it will take another 6 months to merge :trollface:
> 
> why

if you know, you know

**Comment by LilyMakesThings** [comment]
Closing PR:
- Unreliable with clones
- Doesn't work reliably in the interpreter
- I'd much rather just use global custom reporters/blocks, in the very distant future

**Pull request closed without merging**
