### PR TITLE
Add Effects extension

### PR DESCRIPTION
**Pull request by Xeltalliv**
image

Example of using those blocks:
image

Adds 2 effects:
- Clipping, which only shows parts of sprite inside of the clipping area.
- Additive blending

Those effects are cleared after stopping the project. They affect stamps, but don't affect pen. Touching blocks work as if those effects don't exist. They are disabled for stage.

### CODE REVIEW

**Comment by True-Fantom** [comment]
> It might need a better name.

Perhaps just "effects" would have been better. Or "shaders"

**Comment by True-Fantom** [comment]
It may be worth adding these blocks:

- `(clipping box x1)`
- `(clipping box y1)`
- `(clipping box x2)`
- `(clipping box y2)`
- `<additive blending on?>`

**Comment by True-Fantom** [comment]
image prototype (#204)

**Comment by True-Fantom** [comment]
@Xeltalliv By the way, maybe add #177 effects in the future?

**Comment by Xeltalliv** [comment]
> @Xeltalliv By the way, maybe add #177 effects in the future?

In terms of code, it makes more sense to make that a separate extension. I might eventually make it. Or someone else might make it. And for this reason, calling this extension "Effects" may be slightly problematic.

**Comment by True-Fantom** [comment]
@Xeltalliv Well, in fact, all these are the effects of displaying sprites. It would not be very convenient to divide them into "color effects" and "something effects". Perhaps there is an alternative name "Rendering" or "Render".

**Comment by True-Fantom** [comment]
@Xeltalliv 
Скриншот 01-03-2023 194644

**Comment by True-Fantom** [comment]
@Xeltalliv I edited the code a bit and added an icon. [Here](https://github.com/True-Fantom/true-fantom.github.io/blob/main/tests/render.js) is code

PS: I changed name to "Render"

**Comment by True-Fantom** [comment]
> Also, there's no need to mention me

Ok

I changed name back

**Comment by True-Fantom** [comment]
Do you agree with changes?

**Comment by Xeltalliv** [comment]
> Do you agree with changes?

> * added icon

Yes
> * renamed class from `Extension` to `Effects`

Keeping class named just `Extension` allows changing name of the extension more easily. I've recently switched to doing that in every new extension I make.

> * renamed `min x`, `min y`, `max x` and `max y` to `x1`, `y1`, `x2` and `y2` for convenience

There is a reason why it was called that way.
People might not expect this:
image
But this is immediately clear:
image

> * replaced `(function(Scratch) {` with `(Scratch => {`
> * removed unnecessary empty lines
> * add some empty lines

It was formatted in the way I prefer. Double/more empty lines are used to more visibly separate distinct sections of code. [Trailing commas](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas) in "blocks" and "menus" were also intentional.

**Comment by TheShovel** [comment]
Maybe rename this extension to Clipping if you are not planning on adding other effects.

**Comment by True-Fantom** [comment]
Okay)

I asked and offered everything I wanted. You made excellent extension! Good luck in the future)

**Comment by Xeltalliv** [comment]
Note to GarboMuffin: this extension modifies gl state, but doesn't fully restore it at the end. Despite that it seems to work. Not sure if it's better to keep it as is, or make it intercept, save and then restore everything which will add extra overhead, but potentially improve compatibility.

**Comment by GarboMuffin** [comment]
This seems like another case where a documentation page could be beneficial

I'll fix the merge conflicts and merge this in a bit, such a documentation page can be added later if you want to

**Comment by WojtekCodesToday** [comment]
ok

**Pull request merged**
