### PR TITLE
NOname-awa/graphics2d: Use atan2 to get coord to coord angle

### PR DESCRIPTION
**Pull request by DNin01**
Changed the "direction of _x1_,_y1_ to _x2_,_y2_" function to use Math.atan2. It does the same thing but with less lines of code.

Tested pretty much everything I can think of, atan2(0, 0) is 0, output ranges from -180 to 180, atan2 already auto-converts strings to numbers.

### CODE REVIEW

**Comment by Xeltalliv** [comment]
Scratch.Cast.toNumber also convertes NaN to 0. As a result, all Scratch blocks treat NaN inputs as 0 instead of letting NaN propagate like they do in JS.

**Comment by GarboMuffin** [comment]
you need the Cast.toNumber still

**Comment by DNin01** [comment]
Oh, ok!

**Comment by DNin01** [comment]
@GarboMuffin

**Comment by GarboMuffin** [comment]
image

original gives 225, new ones gives -135. so they're both the same actual angle but I don't know if we want to be changing how this block works

**Comment by DNin01** [comment]
This ok, @GarboMuffin?

**Pull request merged**
