### PR TITLE
Add 0832/rxFS2

### PR DESCRIPTION
**Pull request by 0832k12**
I eliminate the bug of "searching for files, listing files" and beautify the blocks.

### CODE REVIEW

**Comment by GarboMuffin** [comment]
Thank you for your patience

These changes look to be backwards incompatible. So we can either:

 - Keep all of the old blocks around forever, but hide them from the block list and add new ones to replace the old ones
 - Add an "rxfs2" extension to replace the old one on the homepage and not touch the old one

**Comment by 0832k12** [comment]
I choose the first one
"Keep all of the old blocks around forever, but hide them from the block list and add new ones to replace the old ones"

**Comment by GarboMuffin** [comment]
I suppose there is a third solution, we probably can consider a repository of not open source/proprietary extensions and move this one there

**Comment by 0832k12** [comment]
Can I make you a **“共同 开发者”**? This way, you can update the extension.
please E-mail to "0832k12@gmail.com to registration.

**Comment by TheShovel** [comment]
I actually wasn't aware of this and now I have to remove this extension from one of my projects. This is a very sketchy practice from  0832k12 and I don't think I'll trust using their code in the future.

**Comment by 0832k12** [comment]
Sorry, I feel guilty for my mistake and the impact it has had on your work. I will not use this license again in the future.
@GarboMuffin @TheShovel

**Comment by GarboMuffin** [comment]
"directly compatible with MIT license" is good enough for us; we will use it under that license. thank you, will get this into the next batch of merges

**Pull request merged**
