### PR TITLE
Readd rxFS extension

### PR DESCRIPTION
**Pull request by 0832k12**
Readd, no change.

### CODE REVIEW

**Comment by GarboMuffin** [comment]
- please address ESLint errors (see failing checks above)
 - change credit link on homepage to either point to a Scratch profile or no link at all
 - you do not need to close and reopen pull requests

**Comment by GarboMuffin** [comment]
some other things:

 - extension `id` should be based on your user folder's name somehow, eg. `0832k12rxfs`
 - if the docsURI page does not have any documentation, the link should be removed

**Comment by 0832k12** [comment]
What should I do with 'All checks have passed'?

**Comment by GarboMuffin** [comment]
Checks have not passed: https://github.com/TurboWarp/extensions/actions/runs/4479749817/jobs/7964911638?pr=291

**Pull request merged**
