### PR TITLE
Block colors for var and list extension

### PR DESCRIPTION
**Pull request by Faris90**
Block colors credit to @TheShovel

### CODE REVIEW

**Comment by qxsck** [comment]
> Block colors credit to @TheShovel

I test it

**Comment by qxsck** [comment]
> Block colors credit to @TheShovel

It has Syntax error

**Comment by GarboMuffin** [comment]
we are not going to be coloring blocks like this at this time

**Comment by Faris90** [comment]
Bruh

**Comment by TheShovel** [comment]
I did not make the extension colors code... . The credits were right above the code you copy pasted.
Xeltalliv made the code.

**Comment by Faris90** [comment]
@TheShovel Sorry I thought you made it

**Pull request closed without merging**
