### PR TITLE
Respond to requests

### PR DESCRIPTION
**Pull request by GarboMuffin**
As all extension contributors are [aware](https://docs.turbowarp.org/development/extensions/compatibility) when they submit an extension, we can't remove it later as doing so would break real projects made by real people. All extensions are also under [open source licenses](https://github.com/TurboWarp/extensions/blob/master/CONTRIBUTING.md#license) that allow us and any other open source or closed-source project to use them effectively without limitation.

What we can do is:

 - Remove all references to your name, as it is clear you do not want any connection
 - Remove all images made by you, as removing images is safe

### CODE REVIEW

**Comment by NexusKitten** [comment]
1. You know damn well we don't want to remove our extensions out of shame of being associated with TurboWarp, we just don't agree with it's philosophies anymore and would not appreciete any prior code we wrote being used. _Replacing the word "Shovel" with "Trowel" is not what we asked for, and is genuinely messed up._
2. You didn't even unlist the extensions from the extension.json. You cared enough to do that for Lily, but of course, we aren't your golden children, so gotta keep that front and center, right?
3. Realistically, how many projects would removing some of these extensions break? Realistically, how many active projects use S-Grab, or LZCompress, or More Motion?

**Comment by TheShovel** [comment]
Just unlist them please.

**Comment by GarboMuffin** [comment]
> would not appreciete any prior code we wrote being used

You shouldn't have submitted it then. Sorry.

> Replacing the word "Shovel" with "Trowel" is not what we asked for, and is genuinely messed up.

I am happy to revert this if Shovel is okay with leaving it as ShovelUtils. They know how to contact me, either through Discord or contact@turbowarp.org. Removing all your code from a project implies a desire to disassociate; this is one step towards that that compromises for compatibility, and the original name remains credited.

> You cared enough to do that for Lily

I will reconsider because of what I said in https://github.com/TurboWarp/extensions/pull/502#issuecomment-1572942065. However LMS Utilities had a lot of issues anyways; most of your extensions are perfectly fine and useful.

> Realistically, how many active projects use S-Grab, or LZCompress, or More Motion?

If the number is not zero then this is irrelevant.

**Comment by GarboMuffin** [comment]
Just to add a couple more things:

 - One reason against unlisting the extensions is that they aren't made only by you. Many of the received significant or at least non-trivial edits or review time from me and others -- why should you unilaterally be able to prevent me from listing my own work?
 - In https://github.com/TurboWarp/extensions/pull/502#issuecomment-1572942065 I did not consider an author asking for all of their extensions to be removed because of an incident outside of the extension repository
 - Realistically I could rewrite almost all of your extensions by this time next week, but that would be a waste of time for everyone involved for absolutely no gain.
 - You are, of course, welcome to contribute on GitHub, just as you did before the place you got banned from existed.

If you have any questions or concerns, you know exactly how to contact me.

**Comment by GarboMuffin** [comment]
For any extensions that remain listed, credits WILL be kept (at least the name), and ShovelUtils won't be renamed.

**Comment by GarboMuffin** [comment]
Been thinking about this.

Removing credits and renaming ShovelUtils was a very emotionally charged and childish action. Neither of those will be happening as long as you do not continue to disrupt the community. That said, I currently intend to leave all of the extensions up on the website.

You were both removed from the Discord server for routinely participating in bad faith. You both received more details on that in private messages; I see no need to elaborate in a public forum. Your requests to remove your extensions are retaliation to that ban, and are similarly made in bad faith. I won't be considering requests that are obviously made with malicious intent and a desire to harm our users. I can't believe I even have to say that.

LMS Utilities was removed for more reasons than just the author asking *politely*. The "LMS" part no longer reflected their identity, the extension was too big, and it was almost entirely redundant by other extensions. It is also important to note that I eventually decided to put it back up (against Lily's request) because **people kept asking for it back**. Removing your 10 collective extensions, which people actually use, will generate a lot more noise than removing LMS Utilities did. The requests of the many are more important than the requests of two people.

Extensions are a collective effort. Someone had the idea. Perhaps you made the initial version, with some help from the Discord. I spent significant amounts of my own time reviewing and editing your extensions to get them across the finish line. Someone else might've submitted some bug fixes. Another person made the artwork for the gallery. Now your extension is out there in the wild, being used by real people. It would be a waste to throw away everyone else's work just because you were disruptive in the Discord.

If you want to *disassociate* with the TurboWarp project entirely as I had originally misinterpreted, I can arrange that. You know how to contact me.

Disappointed that it had to end this way.

**Pull request closed without merging**
