### PR TITLE
NFCWarp - NFC tag reader extension

### PR DESCRIPTION
**Pull request by Alestore**
### What is NFCWarp?
An extension for TurboWarp that reads an NFC tag and returns the message contained in it.

### Reader block
block_30_6_2023-08_43_14

### Compatibility
Only available in Android Chrome, Android WebView, Android Opera and Samsung Internet for now, due to Web NFC API compatibility.
Check updated tab for compatibility [here](https://developer.mozilla.org/en-US/docs/Web/API/Web_NFC_API#browser_compatibility
).
### Future updates and support

- I will soon be adding a writing block in order to write a message (typically plain text) into the NFC tag;
- Reporter blocks that report the serial number of the NFC tag;
- And much more!

### CODE REVIEW

**Review by Flappy25 — COMMENTED** [review]
I tried it out and it worked perfectly

**Comment by GarboMuffin** [comment]
only issue is icon does not work well in light mode

image

I can't test the NFC part of this but if it seems to work for everyone else, that's good enough

**Comment by Alestore** [comment]
> only issue is icon does not work well in light mode
> 
> image
> 
> I can't test the NFC part of this but if it seems to work for everyone else, that's good enough

I can fix that today if you want!

Also, for the test part, if you want I can also send you a video showing how the extension work!

**Comment by GarboMuffin** [comment]
let me know if you have a scratch account you want credited, otherwise this should be ready to merge

**Comment by Alestore** [comment]
> let me know if you have a scratch account you want credited, otherwise this should be ready to merge

Can you put "Alestore Games" as the name and https://scratch.mit.edu/users/aleb2005/ as the Scratch link account? Thanks!

**Pull request merged**
