### PR TITLE
AI ChatBot

### PR DESCRIPTION
**Pull request by programORdie2**
This adds a block for asking stuff to an AI similar to chatGPT!
aichat

### CODE REVIEW

**Comment by programORdie2** [comment]
Yhm, sorry, but i've no idea what's wrong with mt code. A style error? And the escape character at line 38 is NOT unused.

**Review by LilyMakesThings — CHANGES_REQUESTED** [review]
Don't forget to change the ID in the comments once you're done! :)

**Comment by LilyMakesThings** [comment]
Also don't worry about formatting, that's done during the merge.

**Comment by programORdie2** [comment]
I've changed everything you asked for.

**Review by LilyMakesThings — APPROVED** [review]

**Comment by LilyMakesThings** [comment]
I will point out that the reliance of an external API run by an independent party that is required for the entire extension to work does prove this to be quite a weak candidate for acceptance.

**Comment by programORdie2** [comment]
I understand your point. I gonna reopen this PR when i found a way to do it  without backend.

**Pull request closed without merging**
