### PR TITLE
Add color extension

### PR DESCRIPTION
**Pull request by samuellouf**
I created an extension named "Colors +".
I will probably add some new blocks soon.
Screenshot of the Colors + extension

### CODE REVIEW

**Comment by LukeManiaStudioss** [comment]
I don't understand the utility behind the RGB and HSL blocks; they return a value that isn't recognised by other extensions and can't easily have its values extracted other than just having the values on its own, which you probably would have anyway if you're able to input it into the extension.

I understand they're used by the final block, but then the output of that block is also sometimes arbitrary for the same reason (it also has an error case when you input HSL to RGB with a hex default value, I've not tested for other error cases though).

Furthermore, 2 of the other blocks are already in other extensions.

**Comment by GarboMuffin** [comment]
considering this is an extension specifically about colors, having some overlap with other extensions is completely reasonable and probably a good thing honestly

>  I will probably add some new blocks soon.

please do

**Comment by LukeManiaStudioss** [comment]
> considering this is an extension specifically about colors, having some overlap with other extensions is completely reasonable and probably a good thing honestly
The overlap isn't a problem on paper, I only see it as an issue because the extension in its current state doesn't serve much utility. I do like the idea of these blocks being in one place.

**Comment by LukeManiaStudioss** [comment]
Also the name should just be "Colors" or something, as opposed to "Color +", which implies that it's an expansion of Scratch category called "color"

**Comment by Skyhigh173** [comment]
I can make my own version of Color Extension too

**Comment by LukeManiaStudioss** [comment]
> I can make my own version of Color Extension too

I would like to see that, there's a color extension on PenguinMod, perhaps use that as a reference

**Comment by Skyhigh173** [comment]
> > I can make my own version of Color Extension too
> 
> 
> 
> I would like to see that, there's a color extension on PenguinMod, perhaps use that as a reference

yep m2

**Comment by samuellouf** [comment]
Ok, I'm going to edit my extension.

**Comment by GarboMuffin** [comment]
we can merge this in its current state and add more blocks later, if you want

**Pull request closed without merging**
