### PR TITLE
New extension: Mobile keyboard

### PR DESCRIPTION
**Pull request by veggiecan0419**
### New extension: Mobile keyboard 

Blocks that show the keyboard on mobile devices and get the users input without showing any sort of input modal.

**THE THUMBNAIL:**

mobilekeyboard thumbnail

**THE BLOCKS:**

mobile keyboard blocks
newblocks

**THE POSSIBLE KEYBOARD TYPES:**

keyboard types menu items

###### run without sandbox!!!

**NOTES:**

This extension has only been tested out on a **_samsung galaxy A12_** and a **_MediaTek TV_**, though it should show the keyboard on any device with an on-screen keyboard, and should get the users input without showing any sort of input modal on ALL devices (ie. if you run the 'show alphabetical keyboard' block on a computer, the 'typed text' monitor should be recording whatever you type untill you click the enter key).

### CODE REVIEW

**Comment by SharkPool-SP** [comment]
this is cool.

**Comment by Skyhigh173** [comment]
Does it support iOS

**Comment by NexusKitten** [comment]
This extension looks cool, I haven't gotten to test it yet however one thing I notice the block pallete is the newline keyboard blocks, wouldn't those make sense in a drop-down with the other types of keyboards?

**Comment by veggiecan0419** [comment]
> Does it support iOS

@Skyhigh173 
We've updated the cover message.
See the notes section.

**Comment by veggiecan0419** [comment]
> This extension looks cool, I haven't gotten to test it yet however one thing I notice the block pallete is the newline keyboard blocks, wouldn't those make sense in a drop-down with the other types of keyboards?

@NexusKitten 
Done ✔️.
We had initially had them as separate blocks because they use two different javascript functions, but now we combined them into one block as it does make more sense that way.

**Comment by veggiecan0419** [comment]
@GarboMuffin
Could you please also add it to the in-built extension gallery (here basically⤵️) as we couldn't figure out how to do it.
in-built extension gallery
Thank you.

**Comment by veggiecan0419** [comment]
@Garbomuffin
We will be making a few changes. Please don't merge this yet.

**Comment by veggiecan0419** [comment]
@GarboMuffin, can we disable ESlint on SVG images? (Because it keeps complaining about the ratio not being EXACTLY 300×600px)

**Comment by GarboMuffin** [comment]
The aspect ratio must be exactly 2. I deal with that error if you do not.

**Comment by veggiecan0419** [comment]
# UPDATE!!!
### 6 new blocks are coming!

newblocks

**Comment by veggiecan0419** [comment]
# UPDATE!!!
### 6 new blocks are coming!
newblocks

##### And we will also be adding a test it out link (after we found out project_url was a parameter)

**Comment by veggiecan0419** [comment]
I wonder why force-pushing closed the PR?

**Comment by CubesterYT** [comment]
> I wonder why force-pushing closed the PR?

@veggiecan0419, force pushing deletes the other branch to add the contents of the branch to the one you are force pushing it to. Deleting the branch causes the PR the PR was made with to be deleted as well.

**Comment by veggiecan0419** [comment]
### Could someone please explain why the following comment was marked as spam?

###### (https://github.com/TurboWarp/extensions/pull/825#issuecomment-1660017719)
> This extension looks cool, I haven't gotten to test it yet however one thing I notice the block pallete is the newline keyboard blocks, wouldn't those make sense in a drop-down with the other types of keyboards?

**Comment by GarboMuffin** [comment]
hello sorry for delay, i've made some changes and tested them on an Android, do they seem good to you?

**Comment by GarboMuffin** [comment]
if it looks good to you then comment here; if it takes >24hrs to get merged after that then email contact@turbowarp.org because your comment got lost in my notifications

**Review by GarboMuffin — APPROVED** [review]

**Comment by veggiecan0419** [comment]
@GarboMuffin 

Yes, looks good 👍. A lot better than before.
Thanks a lot :)

**Comment by veggiecan0419** [comment]
Yay! 🥳

**Comment by Skyhigh173** [comment]
it seems this extension doesn't work on iOS

**Comment by GarboMuffin** [comment]
if you have an iphone then you can help us fix it

**Pull request merged**
