### PR TITLE
JSON extensions

### PR DESCRIPTION
**Pull request by Skyhigh173**
json extensions, which have the following blocks:
- is json valid
- json contains key?
- array contains value?
- get all (keys/values/keys&values) from json
- length of array
- -
- get key from json
- set key from json
- delete key from json
- -
- get item n of array
- item # of string in array
- array concat (list 1) (list 2)
- replace item n at array
- insert item at array
- delete item at array
- delete every specstring in array
- array from index a to b
- reverse array
- flat array with depth
- -
- create array by string with delimiter
- join array as string
- -
- get list content as array (vm)
- set list content as array (vm)

### CODE REVIEW

**Comment by GarboMuffin** [comment]
- add `const vm = Scratch.vm` at the top
 - move the extension to a use folder like Skyhigh173/json.js
 - change extension ID to something like skyhigh173json

**Comment by Skyhigh173** [comment]
should be ok now

**Comment by Skyhigh173** [comment]
I don't mind it, and I suggest you to add more features into your JSON extension!

**Comment by True-Fantom** [comment]
@Skyhigh173

Thanks)

I already have the following ideas:

Array of keys from the object
Array of values from the object
Sort the array `alphabetically and so on`
Keys with the value ()

**Comment by Skyhigh173** [comment]
My extension already have first 2.

**Comment by True-Fantom** [comment]
@Skyhigh173 

What about this?)

**Comment by Skyhigh173** [comment]
It is better to talk this in your own repo. (To JSON? Do it means it will return real JSON?)

**Comment by True-Fantom** [comment]
@Skyhigh173 

It works like this:

**Comment by Skyhigh173** [comment]
@GarboMuffin It has been some days since I updated it. Can you please check it again?

**Comment by GarboMuffin** [comment]
This, and all of the other extensions in the queue, will be looked at this weekend

**Pull request merged**
