### PR TITLE
IFrame extension port

### PR DESCRIPTION
**Pull request by TheShovel**
This is a port of the 'IFrame' extension from https://penguinmod.site/ . Credits to JeremyGamer13 for the original extension and TheShovel for porting it.
image
image

### CODE REVIEW

**Comment by TheShovel** [comment]
@GarboMuffin Mind fixing the Linting? I don't understand what it wants...

**Comment by LukeManiaStudioss** [comment]
This barely works on some browsers, and the implementation on PenguinMod is messy. I wanted to tackle this with my own method of implementation and workflow layout later on

**Comment by TheShovel** [comment]
What browsers does this not work on?

**Comment by LukeManiaStudioss** [comment]
For me Opera GX, admittedly I haven't tried it on any other browsers.

**Comment by JeremyGamer13** [comment]
this is one of the extensions that i kinda dont care about anymore so im fine with it being added to TW if you are still gonna do that

**Comment by OeildeLynx31** [comment]
In the Iframe, can you add the bloc set HTML ? To add custom HTML, without using an external website!

**Comment by TheShovel** [comment]
> In the Iframe, can you add the bloc set HTML ? To add custom HTML, without using an external website!

I am not sure of how to do that.

**Comment by OeildeLynx31** [comment]
> > In the Iframe, can you add the bloc set HTML ? To add custom HTML, without using an external website!
> 
> I am not sure of how to do that.

Ogadaki, the creator of adacraft added this on adacraft, I don't know exactly how, but you can search in the source code on gitlab.
I think he made a program to delete all <script> in the html code for security, but else he just inject the string with the html in a <div>!

**Comment by JeremyGamer13** [comment]
> In the Iframe, can you add the bloc set HTML ? To add custom HTML, without using an external website!

you can do this with data urls but just being able to type html would be better

**Comment by TheShovel** [comment]
> > In the Iframe, can you add the bloc set HTML ? To add custom HTML, without using an external website!
> 
> you can do this with data urls but just being able to type html would be better

Mind telling me how you can do that with data URLs? It would really help to make a simple implementation.

**Comment by OeildeLynx31** [comment]
> > > In the Iframe, can you add the bloc set HTML ? To add custom HTML, without using an external website!
> > 
> > you can do this with data urls but just being able to type html would be better
> 
> Mind telling me how you can do that with data URLs? It would really help to make a simple implementation.

You can encode to base 64 the original code and convert it to dataURI, then create an Iframe for this dataURI

**Comment by TheShovel** [comment]
> > > > In the Iframe, can you add the bloc set HTML ? To add custom HTML, without using an external website!
> > > 
> > > 
> > > you can do this with data urls but just being able to type html would be better
> > 
> > 
> > Mind telling me how you can do that with data URLs? It would really help to make a simple implementation.
> 
> You can encode to base 64 the original code and convert it to dataURI, then create an Iframe for this dataURI

I remember trying this before... mind showing me a working example?

**Comment by OeildeLynx31** [comment]
> > > > > In the Iframe, can you add the bloc set HTML ? To add custom HTML, without using an external website!
> > > > 
> > > > 
> > > > you can do this with data urls but just being able to type html would be better
> > > 
> > > 
> > > Mind telling me how you can do that with data URLs? It would really help to make a simple implementation.
> > 
> > You can encode to base 64 the original code and convert it to dataURI, then create an Iframe for this dataURI
> 
> I remember trying this before... mind showing me a working example?

the original code: `<p> example </p>`
The base64 code: `PHA+IGV4YW1wbGUgPC9wPg==`
The data URL code: `data:html/plain;base64,PHA+IGV4YW1wbGUgPC9wPg==`
Iframe + data URL: `<iframe src="data:html/plain;base64,PHA+IGV4YW1wbGUgPC9wPg=="></iframe>

**Comment by JeremyGamer13** [comment]
another way would be to change the url to about:blank, then edit the iframes document directly
im not sure what the browser support is for `contentDocument` on iframe elements but it would probably work for most use cases

**Comment by GarboMuffin** [comment]
there is also https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement/srcdoc

to comply with our policies to protect user security, this will also not be merged without applying a `sandbox` (it's on https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe) to the iframe that does not contain `allow-scripts` (ideally just an empty string)

**Comment by TheShovel** [comment]
I have no idea how to do this stuff. I just made sure the extension doesn't need dependencies from PenguinMod, formated it correctly for TurboWarp, and removed some litmits.
I would be happy if someone could take it from here and make it ready for merging.

**Comment by LukeManiaStudioss** [comment]
Once I get home I'm going to quickly throw together an iframe extension from the ground up to work in TurboWarp

**Pull request closed without merging**
