### PR TITLE
 fps-extension.js :O

### PR DESCRIPTION
**Pull request by Thebloxers998**
A nice extension, might be useless 
If yall say that this extension already exists, you don't need to tell me

### CODE REVIEW

**Comment by BlockBoi19** [comment]
As long as people use the extension and like it, its useful

**Comment by BlockBoi19** [comment]
If yall found a Bug, please tell me

**Review by BlockBoi19 — COMMENTED** [review]
Make sure to review it

**Comment by SharkPool-SP** [comment]
1: this already exists in Delta Time and Shovel Utilities
2: This is poorly implemented, clearly written by AI

**Comment by SharkPool-SP** [comment]
> 1: this already exists in Delta Time and Shovel Utilities 2: This is poorly implemented, seemingly written by AI

**Comment by SharkPool-SP** [comment]
> 1: this already exists in Delta Time and Shovel Utilities 2: This is poorly implemented, seemingly written by AI

**Comment by Thebloxers998** [comment]
> 1: this already exists in Delta Time and Shovel Utilities 2: This is poorly implemented, seemingly written by AI

You woke me up bruh while I was sleeping

**Comment by Thebloxers998** [comment]
> 1: this already exists in Delta Time and Shovel Utilities 2: This is poorly implemented, seemingly written by AI

Also didn't I just say "If yall say that this extension already exists, you don't need to tell me"

**Comment by Thebloxers998** [comment]
> 1: this already exists in Delta Time and Shovel Utilities 2: This is poorly implemented, seemingly written by AI

It's just that I'm not good at js

**Pull request closed without merging**
