### PR TITLE
Animated Text: Add Reporter and "text active?" boolean

### PR DESCRIPTION
**Pull request by LukeManiaStudioss**
### **Let's fill in some gaps.**

image

### CODE REVIEW

**Comment by Dy-tech** [comment]
This extension is designed to be compatible with the [Scratch Lab](lab.scratch.mit.edu) equivalent, so we can't add any extra blocks.

**Comment by LukeManiaStudioss** [comment]
> This extension is designed to be compatible with the [Scratch Lab](lab.scratch.mit.edu) equivalent, so we can't add any extra blocks.

The goal of this extension is to be compatible with Scratch Lab projects, however GarboMuffin has never turned down the idea of adding new blocks, even stating ["more blocks may be added later"](https://github.com/TurboWarp/extensions/pull/447#issuecomment-1557840433).

**Comment by Dy-tech** [comment]
@GarboMuffin, Can @LukeManiaStudioss add more blocks?

**Comment by LukeManiaStudioss** [comment]
> @GarboMuffin, Can @LukeManiaStudioss add more blocks?

image

**Pull request merged**
