### PR TITLE
A bunch of new things for Canvas Effects

### PR DESCRIPTION
**Pull request by TheShovel**
Added:
Sepia
Transparency
Scale
SkewX
SkewY
Offset X
Offset Y
Rotation
Border radius

### CODE REVIEW

**Comment by BlueDome77** [comment]
Lets go!!

**Comment by GarboMuffin** [comment]
Have you tested this in the packager?

**Comment by TheShovel** [comment]
> Have you tested this in the packager?

Yes I did. There are no issues.

**Comment by gomiigg** [comment]
It would be cool if there were a `fisheye` effect that could be combined with the `border radius` effect to simulate a CRT effect

**Comment by TheShovel** [comment]
> It would be cool if there were a `fisheye` effect that could be combined with the `border radius` effect to simulate a CRT effect

No.

**Pull request merged**
