### PR TITLE
Camera controls: bugfixes and move x steps

### PR DESCRIPTION
**Pull request by DT-is-not-available**
Fixed accidentally reversing the y-axis in the last pull request because I'm too used to down being positive, rearranged the block palette to more closely match the movement blocks, and added the move camera x steps block.

### CODE REVIEW

**Comment by GarboMuffin** [comment]
seems like this would technically be a backwards-incompatible change

**Comment by DT-is-not-available** [comment]
I'm pretty sure I reversed the Y axis in the last update when I implemented the new camera movement function, so I was considering this a fix to a backwards-incompatible change.

**Comment by DT-is-not-available** [comment]
If I rename the current blocks dealing with camera Y to prepend negative, and make new blocks that are scratch coordinate accurate (as they are now), would that then be backwards-compatable?

**Comment by gomiigg** [comment]
imagine the ability to have multiple (maybe just up to 4) cameras at once, and having certain sprites locked to certain cameras. like having a camHUD, camGame, etc. also i have no idea where I am or what im doing here or how github works i just thought it was a cool idea

**Comment by gomiigg** [comment]
> imagine the ability to have multiple (maybe just up to 4) cameras at once, and having certain sprites locked to certain cameras. like having a camHUD, camGame, etc. also i have no idea where I am or what im doing here or how github works i just thought it was a cool idea

ok nevermind instead of doing all that it could just be done using a "lock to camera at (x),(y)" block or something similar

**Pull request merged**
