### PR TITLE
Add AES encryption extension

### PR DESCRIPTION
**Pull request by LIZARD-OFFICIAL**
This would be really useful if you make a chatroom, or anything that requires a good encryption algorithm

Edit: Turns out github did not accept minified CryptoJS

### CODE REVIEW

**Comment by SurvExe1Pc** [comment]
> This would be really useful if you make a chatroom, or anything that requires a good encryption algorithm
> 
> Edit: Turns out github did not accept minified CryptoJS

😭 i made this but it accepts password input aes128 & aes256 with a password

**Comment by CubesterYT** [comment]
@LIZARD-OFFICIAL, you can use the eslint disable feature on the minified version of CryptoJS section. The new ZIP extension uses a minified version of JZIP to run, and it also used eslint disable.

**Comment by CubesterYT** [comment]
But other than that, this extension is AMAZING!

**Comment by CubesterYT** [comment]
> When does the extension get added to the gallery?

@LIZARD-OFFICIAL, it depends, because GarboMuffin is the only maintainer, meaning only he can review and merge. Since he has a job on weekdays, he can only review on weekends. Even then, it may not be merged or reviewed yet, since he's really busy.

**Comment by CubesterYT** [comment]
What happened???

**Comment by SurvExe1Pc** [comment]
they deleted the repo that it was in

**Comment by SurvExe1Pc** [comment]
so it was auto closed

**Comment by LIZARD-OFFICIAL** [comment]
i thought it would not close the pull 😭

**Pull request closed without merging**
