### PR TITLE
Image update batch

### PR DESCRIPTION
**Pull request by GarboMuffin**
About 8 months late

Various things from https://github.com/TurboWarp/extensions/issues/90 and https://github.com/TurboWarp/extensions/issues/1079

### CODE REVIEW

**Comment by SharkPool-SP** [comment]
Im gonna miss the old fetch

**Comment by SharkPool-SP** [comment]
also you forgot about key simulation

**Comment by GarboMuffin** [comment]
@veggiecan0419 instead of just thumbs down reacting, can you elaborate which images you think are worse?

**Comment by veggiecan0419** [comment]
@GarboMuffin Actually, I preffered how most of them were before.

With sensing+, I feel the old image better represented the extension (as it isn't only touch blocks).
As for fetch, I liked the old concept (the dog **fetch**ing the bone).

As for browser fullscreen, I do have to admit it was a 30min job, but I don't think it looked that bad, just the colours were a bit dull (and it wasn't SVG).

The only ones I really feel got an improvement were deltatime and all menus.

As for all the others, I think that they were good, because they gave the gallery a diverse feel, which I quite liked (I feel now it looks pretty monotone and repetitive).

**Comment by GarboMuffin** [comment]
Thank you for elaborating

Let me explain the motivation for why those images were due to get changed:

 - Many contained the name of the extension. This is redundant and can't be translated.
 - The old sensing+ has trademarks that we definitely should not be using in that context (griffpatch has gotten letters about his use of the Scratch Cat).
 - SVG is easier for other people to edit and looks better. Usually smaller too (old browser fullscreen 58KB, new 3KB)
 - There is a general style that the images should try to follow, but there is still plenty of room for the images to look unique within that style.
 - 2 of the extensions didn't even have images before

If you have better versions that don't regress the problems above, you can submit them and they will get looked at in less than 8 months this time

**Comment by GarboMuffin** [comment]
Any change that wasn't one of those bullet points, like the dog fetching metaphor being replaced, was largely coincidental and can be reverted if someone submits a better one

**Comment by veggiecan0419** [comment]
@GarboMuffin 👍

**Comment by xTvii** [comment]
Sorry if soem of the ones I submitted were a bit of a downgrade !!! ( I made the new fetch and sensing + ones . I also made quite some more if you check #1079 . I'm going to try and make some more too !!! I hope they're better !!

**Comment by xTvii** [comment]
HHOYAH ! i present to you , garbo , my latest invention !!! THE #1607 INATOR THREE THOUSAND !!! YYAAAAAYA more icons is always a good thing especially when like 4 million ( at least 3 of them ) of them have text

**Pull request merged**
