### PR TITLE
Create rixxyx.js

### PR DESCRIPTION
**Pull request by Alestore**
An extension that allows you to do a lot of interesting things, including transforming strings into binary code and then converting them back into binary strings (I use it to pass string values through the TurboWarp cloud server which only supports integer type cloud variables)

### CODE REVIEW

**Comment by GarboMuffin** [comment]
see the part of https://docs.turbowarp.org/development/unsandboxed-extensions about wrapping the extension code in an IIFE to avoid leaking to global scope

**Comment by GarboMuffin** [comment]
I am a bit curious about what 'rixxyx' means

**Comment by Alestore** [comment]
> I am a bit curious about what 'rixxyx' means

I can't really tell you, I found it in a Scratch forum.

**Comment by GarboMuffin** [comment]
So is this something you made or copied from somewhere else? If it's from somewhere else, link the original source, we need to know the license information and who needs to be attributed.

**Comment by Alestore** [comment]
> So is this something you made or copied from somewhere else? If it's from somewhere else, link the original source, we need to know the license information and who needs to be attributed.

Yes, I got it from a Scratch forum, I'm sorry.

You can find it in this list under the letter R: https://scratch.mit.edu/discuss/m/topic/470021/

**Comment by GarboMuffin** [comment]
I've asked the original creator for permission, so we'll see how that goes

Also, arbitrary JS execution blocks will have to be removed or altered: returnObject, execJsCode

**Comment by GarboMuffin** [comment]
Compared to the original version of the extension, returnObject, returnJsCode, and execJsCode were removed.

Note that the color reporter block currently returns the wrong values until a compiler bug fix goes live soon-ish

**Pull request merged**
