### PR TITLE
Update LMS Utilities

### PR DESCRIPTION
**Pull request by LukeManiaStudioss**
- Remove 26 blocks that are made redundant by other extensions (EDIT FROM MAINTAINERS: "Remove" here means "Hide")
- Update block colour to be far more readable
- Remove it from the gallery to discourage people from using it

### CODE REVIEW

**Comment by Scratchfangs** [comment]
Some of my projects that are in .html format right now uses a lot of features in the LMS extension. Removing them would completely break my project and for everyone who is using it.

**Comment by LukeManiaStudioss** [comment]
> Some of my projects that are in .html format right now uses a lot of features in the LMS extension. Removing them would completely break my project and for everyone who is using it.

There are several problems with this message:
- "Removing" blocks has no impact on existing projects. It hides them from the palette and they are permanently accessible.
- Projects in HTML format can be unpackaged with the Turbowarp Unpackager

**Comment by Scratchfangs** [comment]
There is a Turbowarp Unpackager??

**Comment by CST1229** [comment]
> There is a Turbowarp Unpackager??

yes, https://turbowarp.github.io/unpackager/

**Comment by GarboMuffin** [comment]
Just to clarify for anyone who is worried about removing blocks breaking their projects: projects that use them still work, the blocks just aren't listed in the palette

**Comment by Martinelplayz** [comment]
why are you trying to remove it?

**Comment by SurvExe1Pc** [comment]
"to discourage people from using it", and because 26 of its blocks are "redundant"

**Pull request merged**
