### PR TITLE
text: update credits

### PR DESCRIPTION
**Pull request by yuri-kiss**
Partially reverts a3d9564a93e0b5dc3a5f6f4333823d33d6e175b6

### CODE REVIEW

**Comment by yuri-kiss** [comment]
This mistake will not be made again by me.

**Comment by man-o-valor** [comment]
@yuri-kiss A little confused, as the code added in this pr was all written by me (I might be missing something here but I should be credited as far as I know)

**Comment by GarboMuffin** [comment]
Ok, consider sending a pr that adds yourself to the list

**Comment by yuri-kiss** [comment]
image

Resolved: https://discord.com/channels/837024174865776680/1228955450205012019/1321593057266892801

**Pull request merged**
