### PR TITLE
Add extension Outfitted.js

### PR DESCRIPTION
**Pull request by David-Orangemoon**
Outfitted is a scratch extension that allows for costume modification through your scratch blocks.

This extension will get updates in the future if accepted.
[SVG]
Outfitted
[PNG]
Outfitted-Bitmap

### CODE REVIEW

**Comment by GarboMuffin** [comment]
haven't tried this yet (really busy), but first look through the code:

 - eslint is complaining about style issues; not critical but easy to fix
 - replace read me block with `docsURI` to get a view documentation. You can put something like `outfitted.html` in `website` (until we get a more proper solution) then link to https://extensions.turbowarp.org/outfitted.html

**Comment by GarboMuffin** [comment]
Also see what happens if someone tries to set their costumes to weird things like `<script>alert(1)</script>`. I don't remember whether sanitization is something that happens in VM or renderer

**Comment by David-Orangemoon** [comment]
codebase. Didnt think about that thanks for notifying me

**Comment by GarboMuffin** [comment]
I didn't actually test what happened if someone tries to put script tags; it's just something that the extension needs to ensure is handled as it is possible to handle

**Comment by Martinelplayz** [comment]
this looks cool

**Comment by SurvExe1Pc** [comment]
> I didn't actually test what happened if someone tries to put script tags; it's just something that the extension needs to ensure is handled as it is possible to handle

it seems to be good!
image

Code used:
image
xss attack i used to test this: https://youtu.be/gVrdE6g_fa8

**Comment by LilyMakesThings** [comment]
> this looks cool

It's superseded by Looks Plus, which has similar functionality

**Comment by SurvExe1Pc** [comment]
when will there be bitmap support?

**Comment by Drago-Cuven** [comment]
ah I remember this. outdated by looks+ correct?

**Pull request closed without merging**
