### PR TITLE
Update ShovelUtils

### PR DESCRIPTION
**Pull request by Procybit**
I'm a heavy user of ShovelUtils and I've decided to implement some lacking features that I needed sometimes.
After some hours of backtracking (being newbie in JS) I've made:
• import image block now works fine with SVG (through both data: URI and web URL)
• delete sound block implemented

P.S.
After I've finished, I successfully came across https://github.com/TurboWarp/extensions/pull/1141. To be honest, it turned out awkward, but the job is done and it seems like my implementation is neater (maybe).

### CODE REVIEW

**Comment by LilyMakesThings** [comment]
Asset Manager does all this already and serves as a replacement for ShovelUtils.

**Comment by Procybit** [comment]
> Asset Manager does all this already and serves as a replacement for ShovelUtils.

Well I'm blind... Thanks for your remark!

**Comment by SharkPool-SP** [comment]
> Asset Manager does all this already and serves as a replacement for ShovelUtils.

lily coming in clutch fr fr

**Comment by GarboMuffin** [comment]
yeah i think asset manager is preferred for this anyways

**Pull request closed without merging**
