### PR TITLE
TurboHook V.1.1.0 Update

### PR DESCRIPTION
**Pull request by CubesterYT**
The moment everyone's been waiting for... TurboHook V.1.1.0!!!

This update includes full embed support, JSON support, bugfixes, typo fixes, some semi colons, extra space removals, and so much more.

Here is the current roster:
image

### CODE REVIEW

**Comment by LucasXD5** [comment]
bart

**Comment by LilyMakesThings** [comment]
everyone?

**Comment by LucasXD5** [comment]
hi

**Comment by gh-nachoso** [comment]
does the old documentation still exist

**Pull request closed without merging**
