### PR TITLE
Add TOTP + AES extension (Re-opened with cryptography branch)

### PR DESCRIPTION
**Pull request by LIZARD-OFFICIAL**
Not ``master`` branch anymore

### CODE REVIEW

**Comment by CubesterYT** [comment]
@LIZARD-OFFICIAL the two extensions you want to merge still need to be in two different PRs.

**Comment by LilyMakesThings** [comment]
> @LIZARD-OFFICIAL the two extensions you want to merge still need to be in two different PRs.

They don't need to be if they've already been made in 1 PR, it just means that if one has issues and the other doesn't, they will both not get merged immediately.

**Comment by GarboMuffin** [comment]
one extension per pull request, please

**Review by DNin01 — CHANGES_REQUESTED** [review]
I wouldn't really expect an authenticator program to run on TurboWarp because there are already desktop/mobile apps that get the job done (an option that the user doesn't have to program themselves). A TOTP extension sounds kind of like an extension you'd use only once and never again, which isn't accepted.
https://github.com/TurboWarp/extensions/blob/f8182b10b98d5fbb6f57d97c4dbb3c76db12f46a/CONTRIBUTING.md?plain=1#L21
AES encryption sounds fine to me, though.

**Pull request closed without merging**
