### PR TITLE
3 Stylish and useful extensions.

### PR DESCRIPTION
**Pull request by Eaielectronic**
The first extension FPS returns allows you to receive 30 times 1 every second, useful for projects that have different FPS so as not to create a difference in speed in the loops. The second extension is for detecting multiple fingers on mobile, unlike sensing + it uses a completely different API. which allows it to work on all mobile devices whether iOS or Android. The third extension allows you to create login forms and the fourth extension allows you to create bubbles with scrolling texts, if you include HTML tags in the text of the blocks, then it will apply the styles to the text in the bubble: for example, if you write <em> Example.<em/> it will write example in italics in the bubble. I hope you are interested in these extensions and thank you for nothing for your attention to this message.

### CODE REVIEW

**Review by Eaielectronic — COMMENTED** [review]
add scratch function

**Comment by Brackets-Coder** [comment]
Generally, it's preferred that you have one fork of the repository with one branch per extension, and you submit one pull request per branch/extension instead of combining multiple in one pull request. It helps to keep things more organized.

**Comment by Eaielectronic** [comment]
Do you want me to ask for an extension addition?

**Comment by Brackets-Coder** [comment]
> Do you want me to ask for an extension addition?

You should split this pull request into three separate ones for each extension. In your forked repository, use one branch per extension and submit one pull request per branch. Avoid using the master branch.

**Comment by Eaielectronic** [comment]
ok

**Comment by Thebloxers998** [comment]
> I dont see a use in this (fps extension) when you can literally just do this with the delta time extension. Its more accurate too: Screenshot 2024-11-20 at 10 55 59 PM

You also forgot Shovel Utilities extension, it has a fps value

**Pull request closed without merging**
