### PR TITLE
Use Scratch.fetch, Scratch.openWindow, Scratch.redirect, etc.

### PR DESCRIPTION
**Pull request by GarboMuffin**
https://github.com/TurboWarp/extensions/issues/169

### CODE REVIEW

**Comment by showierdata9978** [comment]
Cloudlink should be able to fetch example servers without using `Scratch.fetch`. My reasoning is that, before scratch even knows about the extension, it loads it. (plus it only goes to mikes gh pages)

That URL is also static, and would only get changed if the CL repo changed, or mike added a gh pages domain (unlikely)

people are also likely to decline it, not knowing what it does. Then not being able to see any default servers (Then complaining that its broken).

**Comment by GarboMuffin** [comment]
There will be a list of websites that are always exempted from the permission prompt. *.github.io and raw.githubusercontent.com will be in that list.

**Comment by showierdata9978** [comment]
Ah ok.

**Comment by showierdata9978** [comment]
Prob easier to maintain then having it in the ext.

But best just to ask @MikeDev101

**Comment by MikeDev101** [comment]
Server list not being built directly into the extension is mainly just for convenient updating. On that note, I believe the changed fetch methods are for providing a user consent prompt of some sort?

**Comment by showierdata9978** [comment]
Yeah, it opens an alert with the domain

**Comment by True-Fantom** [comment]
@GarboMuffin There will be no alerts when the project is in electron format? If they are, it will be very inconvenient, considering that the user already provides full access to the device by opening `.exe` file.

**Comment by GarboMuffin** [comment]
There will be no permission prompts in any packaged format

**Pull request merged**
