### PR TITLE
Create Particle Tools

### PR DESCRIPTION
**Pull request by SharkPool-SP**
Tools to help make particle engines easier!
Particle_Tools
Screenshot 2023-09-02 at 10 30 04 PM

### CODE REVIEW

**Comment by veggiecan0419** [comment]
# #1000 ! 🎉

**Comment by hdboye** [comment]
This looks awesome, but I think some documentation might help. I genuinely have no idea how it works LOL

(also #1000 !!)

**Comment by SharkPool-SP** [comment]
> This looks awesome, but I think some documentation might help. I genuinely have no idea how it works LOL
> 
> (also #1000 !!)

I’ll add some documentation:) thanks!!!!

**Comment by horizontal-shading** [comment]
A 1000!

**Comment by idoinfactexist** [comment]
yes! i was about to ask for this, thank you so much!

**Comment by SharkPool-SP** [comment]
> yes! i was about to ask for this, thank you so much!

Thanks!!! I’ll add documentation soon so it’s easier to understand btw :)

**Comment by SharkPool-SP** [comment]
this is now obsolete #1724

**Pull request closed without merging**
