### PR TITLE
New extension "Screen resolution"

### PR DESCRIPTION
**Pull request by shreder95ua**
also, sorry for being karen last time)

### CODE REVIEW

**Comment by CST1229** [comment]
Those blocks could belong in Navigator.

**Comment by CubesterYT** [comment]
> Those blocks could belong in Navigator.

@shreder95ua These blocks are already in this extension #708

**Comment by LilyMakesThings** [comment]
I like it!

**Comment by shreder95ua** [comment]
> > Those blocks could belong in Navigator.
> 
> @shreder95ua These blocks are already in this extension #708

@CubesterYT Well, I didn't knew about it :/



> Those blocks could belong in Navigator.

Hm... Maybe...? Because I think of adding a lot of features to my extension soon.

**Comment by GarboMuffin** [comment]
Made redundant by #708

**Pull request merged**
