### PR TITLE
AmongUs blocks

### PR DESCRIPTION
**Pull request by TheShovel**
Yep. They are blocks, and they are sussy.
image

### CODE REVIEW

**Review by David-Orangemoon — COMMENTED** [review]
10/10 my preferred theme

**Comment by LilyMakesThings** [comment]
10/10 Ooohohohh the sussy wussy extension!!

**Comment by Flappy25** [comment]
I love it! Good job!

**Comment by Mickmick2012** [comment]
looks good but i just wanted to say that the meme is dead
also very sus

**Comment by GarboMuffin** [comment]
Same problem as mrbeast utilities: it might be funny, but when someone sees this after loading a project, I'm the one who gets more issues and emails to deal with.

**Comment by TheShovel** [comment]
> Same problem as mrbeast utilities: it might be funny, but when someone sees this after loading a project, I'm the one who gets more issues and emails to deal with.

Fair enough.

**Comment by Martinelplayz** [comment]
i can imagine this being added to a skins menu though or maybe as a skin options in the addons menu. and it would not be attached to the project but rather a setting on the user's computer.

**Pull request closed without merging**
