### PR TITLE
Add clipboard blocs

### PR DESCRIPTION
**Pull request by tomyo-code**
A litlle extension for interact with the clipboard

### CODE REVIEW

**Comment by Martinelplayz** [comment]
what exactly does this do that the other 2 extensions that have clipboard blocks don't?

**Comment by tomyo-code** [comment]
There is à hat block for trigger when you copy something and there is a popup when the block copy something in your clipboard for advertis you

**Comment by tomyo-code** [comment]
oooh thanks

**Comment by GarboMuffin** [comment]
closing in favor of https://github.com/TurboWarp/extensions/pull/667

**Pull request closed without merging**
