### PR TITLE
Add Encoding extension

### PR DESCRIPTION
**Pull request by SIPC**
image

### CODE REVIEW

**Comment by Xeltalliv** [comment]
Suggestion:
First 6 blocks in this extension are about different types of text encoding and the other 3 are about working with time, which isn't what most people expect from the extension named math. Maybe it is worth to split it into 2 extensions called: _Encoding_ and _Time_.
_Time_ extension could be extended to have blocks like:
image

**Comment by SIPC** [comment]
> Suggestion: First 6 blocks in this extension are about different types of text encoding and the other 3 are about working with time, which isn't what most people expect from the extension named math. Maybe it is worth to split it into 2 extensions called: _Encoding_ and _Time_? _Time_ extension could be extended to have blocks like: image

I will try to improve!

**Comment by SIPC** [comment]
image

**Comment by GarboMuffin** [comment]
I think that the encoding blocks and the time blocks should be put in separate extensions

**Comment by SIPC** [comment]
> I think that the encoding blocks and the time blocks should be put in separate extensions

Removed blocks over time

**Comment by SIPC** [comment]
image

**Comment by GarboMuffin** [comment]
Where did you get the code for the md5 function here? We need to credit where we copy code from.

**Comment by GarboMuffin** [comment]
I am not sure how much the random generation blocks belong here, but once it's clarified where the md5 script comes from, I can merge this

**Comment by SIPC** [comment]
md5 scripts can be found everywhere on the web, here is the md5 script from [Wie erzeugt man einen MD5-Dateihash in JavaScript/Node.js?](https://stackoverflow.com/questions/14733374/how-to- generate-an-md5-file-hash-in-javascript-node-js)

**Comment by GarboMuffin** [comment]
I'm very sorry for all the delay on this

If you want, we can probably rename this to `SIPC/encoding.js`, and you can go add back all the blocks that I had asked to be removed, or I can just merge it as-is

About the MD5 function: Note that StackOverflow's content license is not compatible with the GPLv3 that we require code to be compatible with, so I've replaced the the function with one that is. Note that just because there are a lot of MD5 functions on the internet doesn't mean we can just copy one without checking its license.

**Comment by SIPC** [comment]
That's it! :)

**Comment by GarboMuffin** [comment]
Do you want your name and/or link to be listed here, and if so, what should those be? (scratch.mit.edu links okay, other links may not be)

image

**Comment by SIPC** [comment]
> Do you want your name and/or link to be listed here, and if so, what should those be? (scratch.mit.edu links okay, other links may not be)
> 
> image

yes

**Comment by SIPC** [comment]
I have posted pictures about the extension in [Help us create images for all of the extensions](https://github.com/TurboWarp/extensions/issues/90)

**Pull request merged**
