### PR TITLE
Unified clipboard extension

### PR DESCRIPTION
**Pull request by NexusKitten**
Two people made a clipboard extension, both with blocks the other didn't have, and so I decided it would be best just to merge the two and let the creators split the credit.

If any of the original creators have issues with this, please leave a comment on this PR and we can try to work something out.\

Clipboard
image

### CODE REVIEW

**Comment by horizontal-shading** [comment]
Nice extension! But the clipboard reporter isn't working, sadly....

**Comment by LilyMakesThings** [comment]
> Nice extension! But the clipboard reporter isn't working, sadly....

they forgot to ask for permission to use the clipboard as well :/

**Comment by NexusKitten** [comment]
> > Nice extension! But the clipboard reporter isn't working, sadly....
> 
> they forgot to ask for permission to use the clipboard as well :/

The extension requires permission to view the clipboard, however the original extensions didn't ask for permission for clipboard and I don't know how to do that

**Comment by NexusKitten** [comment]
> Nice extension! But the clipboard reporter isn't working, sadly....

Weird, it works fine for me, did you enable clipboard on the website?

**Comment by horizontal-shading** [comment]
> > Nice extension! But the clipboard reporter isn't working, sadly....
> 
> Weird, it works fine for me, did you enable clipboard on the website?

Every other block works OK for me, except for the clipboard reporter.

**Comment by NexusKitten** [comment]
> > > Nice extension! But the clipboard reporter isn't working, sadly....
> > 
> > 
> > Weird, it works fine for me, did you enable clipboard on the website?
> 
> Every other block works OK for me, except for the clipboard reporter. I use Firefox, and I don't know if this is a common issue.

The clipboard reporter is the only one that requires enabling permissions, IDK how to do it on firefox but there should be a way to give the website permission for clipboard.

**Comment by LilyMakesThings** [comment]
> > > > Nice extension! But the clipboard reporter isn't working, sadly....
> > > 
> > > 
> > > Weird, it works fine for me, did you enable clipboard on the website?
> > 
> > 
> > Every other block works OK for me, except for the clipboard reporter. I use Firefox, and I don't know if this is a common issue.
> 
> The clipboard reporter is the only one that requires enabling permissions, IDK how to do it on firefox but there should be a way to give the website permission for clipboard.

It's your responsibility to ask for the clipboard. Look at my recent ExtraUtilities pull to figure out how to do that.

**Comment by NexusKitten** [comment]
> It's your responsibility to ask for the clipboard. Look at my recent ExtraUtilities pull to figure out how to do that.
fine, fixed

**Comment by AdamMady** [comment]
> Two people made a clipboard extension, both with blocks the other didn't have, and so I decided it would be best just to merge the two and let the creators split the credit.
> 
> If any of the original creators have issues with this, please leave a comment on this PR and we can try to work something out.\
> 
> Clipboard image

I don't mind the merge

**Comment by AdamMady** [comment]
> > > Nice extension! But the clipboard reporter isn't working, sadly....
> > 
> > 
> > they forgot to ask for permission to use the clipboard as well :/
> 
> The extension requires permission to view the clipboard, however the original extensions didn't ask for permission for clipboard and I don't know how to do that

I'll try to do that

**Comment by tomyo-code** [comment]
> > > Nice extension! But the clipboard reporter isn't working, sadly....
> > 
> > they forgot to ask for permission to use the clipboard as well :/
> 
> The extension requires permission to view the clipboard, however the original extensions didn't ask for permission for clipboard and I don't know how to do that

Do you talk about my extension? If yes i don't need to ask permission because in my code there is no permission check

**Comment by LilyMakesThings** [comment]
> > > > Nice extension! But the clipboard reporter isn't working, sadly....
> > > 
> > > 
> > > they forgot to ask for permission to use the clipboard as well :/
> > 
> > 
> > The extension requires permission to view the clipboard, however the original extensions didn't ask for permission for clipboard and I don't know how to do that
> 
> Do you talk about my extension? If yes i don't need to ask permission because in my code there is no permission check

To comply with the other Clipboard blocks in the 3 existing extensions that support them, you need to ask for permission

**Comment by tomyo-code** [comment]
> > > > > Nice extension! But the clipboard reporter isn't working, sadly....
> > > > 
> > > > 
> > > > they forgot to ask for permission to use the clipboard as well :/
> > > 
> > > 
> > > The extension requires permission to view the clipboard, however the original extensions didn't ask for permission for clipboard and I don't know how to do that
> > 
> > Do you talk about my extension? If yes i don't need to ask permission because in my code there is no permission check
> 
> To comply with the other Clipboard blocks in the 3 existing extensions that support them, you need to ask for permission

I don't really understand why, for me you just need to delet the line where you check the permissions... but you have more experience than me, i trust you

**Comment by AdamMady** [comment]
> I don't really understand why, for me you just need to delet the line where you check the permissions... but you have more experience than me, i trust you

Really glad both of our work didn't go to waste

**Comment by horizontal-shading** [comment]
Update: I set dom.events.asyncClipboard.readText to true on Firefox and now the clipboard block _finally_ works.

**Comment by GarboMuffin** [comment]
The current "read clipboard" block was not very thought out. Browsers typically ignore it if you aren't in eg. a click event handler, but Scratch blocks don't run in click events. Usually it ends up working the first time (because you click on the permission button), but future attempts silently break. We will probably have to make that prompt appear each time to make the block somewhat workable.

Would encourage using "when something is pasted" and "last pasted text" instead if possible

**Pull request merged**
