### PR TITLE
New extension: Font Manager

### PR DESCRIPTION
**Pull request by SharkPool-SP**
Manage Fonts in Your Project, Ashimee helped me implementing Custom Fonts and the Event Blocks :)
image

### CODE REVIEW

**Comment by GarboMuffin** [comment]
Hey, so made a couple changes.

If you think it looks fine now then let me know and I'll merge it within 24 hours after that (ping me on discord if I forget)

**Comment by GarboMuffin** [comment]
and add a // License:

**Comment by SharkPool-SP** [comment]
> and add a // License:

done, all seems fine to me!

**Comment by AshimeeAlt** [comment]
this is a great day for sure 
image

**Pull request merged**
