### PR TITLE
Delete my extensions

### PR DESCRIPTION
**Pull request by NexusKitten**
I got cancelled on TurboWarp.org and now Im banned and when Im banned Ic an't talk and I can't talk because bad opinion and extension my bad not clones plus so my extensions go away for good now >:(

### CODE REVIEW

**Comment by NexusKitten** [comment]
I passed eslint for once, how sentimental

**Comment by NexusKitten** [comment]
https://www.youtube.com/shorts/Dtxm-yFVzdk?feature=share
CG5 Made A New Song And I Think It's Pretty Cool

**Comment by GarboMuffin** [comment]
As you were aware when you submitted the extension, we can't remove them later as doing so would break real projects by real people. See https://github.com/TurboWarp/extensions/pull/1052

**Comment by GarboMuffin** [comment]
You were never "cancelled", and you are, of course, still welcome to participate on the GitHub if you choose to, just as you did before the other place existed

**Pull request closed without merging**
