### PR TITLE
Lily/ClonesPlus: re-re fix performance for "when I start as w/ set to ..." block

### PR DESCRIPTION
**Pull request by SharkPool-SP**
Now it should work. It waits for variables to initialize

### CODE REVIEW

**Review by CubesterYT — DISMISSED** [review]
😔

**Comment by GarboMuffin** [comment]
Fails on this project

https://static.muffin.ink/extensions-1763.sb3

image


production:

image

this pull request:

image

**Comment by GarboMuffin** [comment]
Anything that isn't an edge-activated hat will differ at least a little bit. That could break projects. But maybe worth doing since this is probably rare and that it's not running right after the vanilla block is arguably a bug. Though in this project it doesn't even run at all so that's a pretty bad failure case.

Here is where the vanilla event gets fired. You could do it in the same spot.

https://github.com/TurboWarp/scratch-vm/blob/b900a375fa1c4a9574835c308baf5f8f16fd6cd9/src/sprites/rendered-target.js#L177

**Comment by SharkPool-SP** [comment]
> Anything that isn't an edge-activated hat will differ at least a little bit. That could break projects. But maybe worth doing since this is probably rare and that it's not running right after the vanilla block is arguably a bug. (if you follow this logic expected output would be `when i start as clone` then `when i started as clone with` then `when timer` then `forever` then `end`).
> 
> Here is where the vanilla event gets fired. You could do it somewhere around. Might not be able to do this spot exactly since the variable won't be set yet.
> 
> https://github.com/TurboWarp/scratch-vm/blob/b900a375fa1c4a9574835c308baf5f8f16fd6cd9/src/sprites/rendered-target.js#L177

fixed

**Comment by GarboMuffin** [comment]
btw the unrelated changes like Scratch.vm.runtime -> runtime probably didn't really need to be included

**Comment by GarboMuffin** [comment]
!format

**Comment by SharkPool-SP** [comment]
> btw the unrelated changes like Scratch.vm.runtime -> runtime probably didn't really need to be included

eh, ever so slightly faster + simpler

**Comment by GarboMuffin** [comment]
at the cost of making the diffs bigger  for no reason and  increasing change of a typo  causing a regression

**Comment by GarboMuffin** [comment]
ok will use this pr to test more things related to the formatting workflow being broken

**Comment by GarboMuffin** [comment]
!format

**Pull request merged**
