### PR TITLE
Add LMS Utilities Extensions

### PR DESCRIPTION
**Pull request by LukeManiaStudioss**
Hi,

This extension includes several interesting utility blocks.

Hat block to allow a boolean input:
image

Boolean input that can allow for true, false, or a random readout.
image

Booleans to detect whether a sprite is a clone or whether it was clicked.
image

A block that can set the username and a block that can trigger the green flag.
image
image

As well as 46 other blocks.

### CODE REVIEW

**Comment by 0832k12** [comment]
Great!

**Comment by True-Fantom** [comment]
Actually, it would be cool to combine this with tw-blocks and runtime-options:

_when, isClone, spriteClicked to tw-blocks
setUserName and greenFlag to runtime-options_

**Comment by GarboMuffin** [comment]
- the block's current color makes text borderline unreadable, even for people with good vision
 - SVG is preferred for extension images
 - see ESLint errors messages -- they all seem to be actual bugs

**Comment by LukeManiaStudioss** [comment]
Alright, these are all issues I can amend, thank you

**Comment by LukeManiaStudioss** [comment]
I've resolved all of the issues stated. I can provide an SVG for the updated thumbnail but it's uncropped. 

Below is the SVG and PNG, the PNG is cropped to 600x300 and the SVG is raw.
lmsutils
lmsutils

**Comment by LukeManiaStudioss** [comment]
Third time's the charm

**Pull request merged**
