### PR TITLE
add notifications rework

### PR DESCRIPTION
**Pull request by gvalue-04**
yeah so i did it :goose:

### CODE REVIEW

**Comment by gvalue-04** [comment]
why is the lint failing because stuff that is defined apparently isnt defined

**Comment by SharkPool-SP** [comment]
> why is the lint failing because stuff that is defined apparently isnt defined

error should be "Error"

**Comment by SharkPool-SP** [comment]
also if garbo merges this, please hide the other notifications extension. Since this isnt editing the og files

**Comment by gvalue-04** [comment]
also why does the folders have to be my scratch user

**Comment by gvalue-04** [comment]
@SharkPool-SP Yeah i hid it

**Comment by gvalue-04** [comment]
why does the formatting keep failing :sob:

**Comment by gvalue-04** [comment]
h

**Pull request closed without merging**
