### PR TITLE
Policy on AI (ChatGPT, Bard, etc.)

### PR DESCRIPTION
**Pull request by GarboMuffin**
Example of why you shouldn't use ChatGPT: https://chat.openai.com/share/245724e7-0a3c-4001-9fef-fb72c4a4acc6

Everything except the last code block is hallucinated garbage, and even the code block is still worse than useless as it uses ScratchX so it can never be accepted here.

### CODE REVIEW

**Comment by horizontal-shading** [comment]
I've never used Chatgpt, but I agree

**Comment by BunkerStriker** [comment]
That is why in the prompt you got to include a real TurboWarp extension for the ChatGPT to try to replicate it
https://chat.openai.com/share/2d46a624-5dca-4e66-b159-4bd1d0a92a07

**Comment by GarboMuffin** [comment]
There are several things wrong with the example you have provided.

 - No one submitting an AI extension actually prompts it like that
 - Math operations is a trivial extension. Try something that we would actually accept here, and watch it painlessly fumble over itself
 - It doesn't include the mandatory // headers at the top
 - The divide block returns a string form of "Infinity" for no reason
 - The extension ID is improperly formatted

It's small things like this that make extension review painful at times because it's obvious someone has never even peeked at the documentation or another extension. What's worse is that ChatGPT, although it's awful at making real extensions, is really good at making things that look real, which makes people submit them in good faith and end up wasting a lot of our time fixing a broken heap of garbage.

**Comment by IonMakesGarbage** [comment]
i dont think people should use it for actually making the extensions but having a quick tool that can check basic errors like a missing comma or colon is extremely useful

**Comment by GarboMuffin** [comment]
if you need an AI to help you fix simple syntax errors (which your editor is already going to notify you about), then you probably shouldnt be submitting extensions here

**Comment by IonMakesGarbage** [comment]
ok...

**Pull request merged**
