### PR TITLE
Add new TAS EXTENSION 

### PR DESCRIPTION
**Pull request by BlockBoi19**
Add this extension please

### CODE REVIEW

**Comment by Drago-Cuven** [comment]
this extension is completely broken XD

**Comment by Drago-Cuven** [comment]
this extension can also easily be recreated with more timers.

**Comment by BlockBoi19** [comment]
> this extension can also easily be recreated with more timers.

So what does that have to do with the more timers extension

**Comment by BlockBoi19** [comment]
> this extension can also easily be recreated with more timers.

And anyways

**Comment by BlockBoi19** [comment]
> this extension is completely broken XD

You could've reviewed a comment like that

**Comment by CubesterYT** [comment]
Sorry, we cannot accept this extension. This extensions functionality can be easily replicated using `More Timers`.

**Comment by BlockBoi19** [comment]
> Sorry, we cannot accept this extension. This extensions functionality can be easily replicated using `More Timers`.

Dang, maybe if I didn't forget to set this as draft

**Pull request closed without merging**
