### PR TITLE
Lily/ClonesPlus.js -- Fix "when I start as..." Performance, but this time it works

### PR DESCRIPTION
**Pull request by SharkPool-SP**
Resolves: https://github.com/TurboWarp/extensions/issues/1758

Now it works packaged and when opening projects :)

### CODE REVIEW

**Review by hammouda101010 — APPROVED** [review]

**Review by CubesterYT — APPROVED** [review]
Good that it's fine now.

**Review by CST1229 — APPROVED** [review]
ok i guess

**Comment by SharkPool-SP** [comment]
Yummers

**Comment by CubesterYT** [comment]
You better hope to god nothing else happens. Most likely not, considering we did more extensive testing this time around.

**Comment by SharkPool-SP** [comment]
> You better hope to god nothing else happens. Most likely not, considering we did more extensive testing this time around.

Hopefully.

**Pull request merged**
