### PR TITLE
Add turboGPT.js

### PR DESCRIPTION
**Pull request by LOLEMO**
### **TurboGPT Extension**
Adds an extension that lets interact with chatbots of gpt-3.5

- No api key required
- Lets make simple prompts and interact with multiple chat sessions

- You can test it [**here**](https://turbowarp.org/editor?extension=https://lolemo.github.io/turboGPT/extension.js)

### CODE REVIEW

**Comment by LilyMakesThings** [comment]
You thumbnail's SVG is using a text element, which isn't allowed, which is why it's failing

**Comment by CubesterYT** [comment]
lolemo, let me give you a heads up, if this does get merged, I want to tell you that the extension can't be named with scratch in it's name, as GarboMuffin doesn't want TurboWarp to be associated with Scratch in any way. He told me the same thing with my extension, called TurboHook, which was called ScratchHook originally. So try renaming the extension to TurboGPT.

**Comment by LOLEMO** [comment]
> lolemo, let me give you a heads up, if this does get merged, I want to tell you that the extension can't be named with scratch in it's name, as GarboMuffin doesn't want TurboWarp to be associated with Scratch in any way. He told me the same thing with my extension, called TurboHook, which was called ScratchHook originally. So try renaming the extension to TurboGPT.

thanks, I just changed the name

**Comment by XeroName** [comment]
image
this is really interesting

**Comment by GalacticCoder922** [comment]
I wonder if you can use GPT-4.

**Comment by Flappy25** [comment]
> I wonder if you can use GPT-4.

You can, if you know python

**Comment by GalacticCoder922** [comment]
Oh, OK.

**Comment by LOLEMO** [comment]
> > I wonder if you can use GPT-4.
> 
> You can, if you know python

You'd need an API key but i think it's expensive
This extension is gpt-3.5 only, but free and faster than gpt-4

**Comment by Flappy25** [comment]
> > > I wonder if you can use GPT-4.
> > 
> > You can, if you know python
> 
> You'd need an API key but i think it's expensive
> This extension is gpt-3.5 only, but free and faster than gpt-4

Use the GPT-4 free project

**Comment by ghbbeep** [comment]
This is a really good extension! Something that could be useful is a block that prints the last thing generated by the AI. Otherwise, this should really be on the extensions website!

**Comment by BlueDome77** [comment]
> I wonder if you can use GPT-4.

People say ChatGPT 4 is getting [dumber](https://duckduckgo.com/?q=ChatGPT+4+dumber&kp=1&t=iphone&iar=news&ia=news)

**Comment by Flappy25** [comment]
> > I wonder if you can use GPT-4.
> 
> People say ChatGPT 4 is getting [dumber](https://duckduckgo.com/?q=ChatGPT+4+dumber&kp=1&t=iphone&iar=news&ia=news)

Maybe cuz the internet is full of fake news or openai is trying to suppress it's knowledge

**Comment by ddededodediamante** [comment]
so cool

**Comment by NexusKitten** [comment]
image
It seems the API is bugged right now, is it down? If so, how often does said API go down?

**Comment by LOLEMO** [comment]
> image It seems the API is bugged right now, is it down? If so, how often does said API go down?

It works well for me. If the extension doesn't work it's because the OpenAI API is down, probably due to maintenance. Could you send any error messages you get in the browser console?
You can see the openai status page to see how often this happens [here](https://status.openai.com/)

**Comment by LOLEMO** [comment]
### **Added new blocks**
Last generated thing and prompt suggested by @ghbbeep :
lastgen
Exporting and importing specific chats:
Captura de pantalla 2023-07-31 a las 11 06 08
Reporter to list active chats:
Captura de pantalla 2023-07-31 a las 11 06 58
Export everything:
Captura de pantalla 2023-07-31 a las 11 07 37
Import and merge, or remove and import:
Captura de pantalla 2023-07-31 a las 11 08 19

**Comment by True-Fantom** [comment]
Hello! I really like your extension, but I also want to point out the shortcomings that can be easily fixed.

Block icon is black, which does not correspond to the scratch style, repaint it in white.

It is not clear from the extension what some blocks are responsible for, it can be solved by adding documentation.

Also, it is not clear from the extension which GPT model is used, and even if you add it to the documentation, it will not be convenient. So you should probably change the name of the extension to "GPT-3.5", it will be more concise and without the "Turbo" prefix, which is useless in this case.

**Comment by Martinelplayz** [comment]
@LOLEMO this ext is currently broken.

**Comment by NexusKitten** [comment]
> @LOLEMO this ext is currently broken.

This has happened in the past, presumably because it's a free API designed for a different service. Perhaps add a label warning the user that the API may go down often.

**Comment by ghbbeep** [comment]
> > @LOLEMO this ext is currently broken.
> 
> This has happened in the past, presumably because it's a free API designed for a different service. Perhaps add a label warning the user that the API may go down often.

Another idea is maybe you can either select from a dropdown of known/reputable APIs, or type one in yourself. But as it stands right now, this extension isn't really useable.

**Comment by GalacticCoderReturns** [comment]
This is cool! I have it in my PenguinMod Library right now.

**Comment by GarboMuffin** [comment]
The problem with these ends up being that LLMs are expensive to run; *someone* has to be footing the bill. It happens that the free API of choice shut down since this pull request was created.

**Comment by GarboMuffin** [comment]
#497 is still open

**Comment by zmh-program** [comment]
> The problem with these ends up being that LLMs are expensive to run; *someone* has to be footing the bill. It happens that the free API of choice shut down since this pull request was created.

Please don't have that mentality with ai. You have no idea how cheap chat completions are for llm nowadays (including cf's free stable diffusion, etc).

**Comment by LilyMakesThings** [comment]
> > The problem with these ends up being that LLMs are expensive to run; _someone_ has to be footing the bill. It happens that the free API of choice shut down since this pull request was created.
> 
> Please don't have that mentality with ai. You have no idea how cheap chat completions are for llm nowadays (including cf's free stable diffusion, etc).

Well who's gonna pay for the extension's API, then? Because TurboWarp would have to offer it for free and then what happens when other websites start using it for free?

**Comment by zmh-program** [comment]
> > > The problem with these ends up being that LLMs are expensive to run; _someone_ has to be footing the bill. It happens that the free API of choice shut down since this pull request was created.
> > 
> > Please don't have that mentality with ai. You have no idea how cheap chat completions are for llm nowadays (including cf's free stable diffusion, etc).
> 
> Well who's gonna pay for the extension's API, then? Because TurboWarp would have to offer it for free and then what happens when other websites start using it for free?

U DON'T EVEN know cf free llm.

**Comment by GarboMuffin** [comment]
There is nothing stopping you from using any of the HTTP/Fetch/Network extensions to use any API you want

But when something is submitted here, the idea is that it's going to keep working basically forever. Free AI services demonstrably are not reliable; again see how the original website that this PR used unceremoniously shut down one day.

**Comment by zmh-program** [comment]
So you think the merge was stopped because cloudflare would be shut down? As well as it might be good to know about the website I wrote (chatnio.net). Also, my recommended practice is to understand the llm circle rather than just assume so.

**Comment by GarboMuffin** [comment]
if you think you have a way to solve my concerns then you are welcome to submit a new pull request

**Comment by zmh-program** [comment]
I think you and the developers in the turbowarp community could tap into it if you're interested via [chatnio api](https://docs.chatnio.net/kai-fa-zhe-zi-yuan/api-reference) (supports openai calls in the same format)

(My non-profit site chatnio.net has 50,000 people registered, just don't think it's a small site)

**Pull request closed without merging**
