### PR TITLE
true-fantom/math: add x < y < z blocks

### PR DESCRIPTION
**Pull request by MaelkMark**
I've added a new boolean block that checks whether a number is in a given range.
`<A is in range B - C>`

block opcode: `is_in_range_block`

### CODE REVIEW

**Comment by LilyMakesThings** [comment]
I think this exists in more comparisons as `() < () < ()`

**Comment by MaelkMark** [comment]
> I think this exists in more comparisons as `() < () < ()`

Oh, I didn't know. However I think it would be practical to have such a block in the math extension too - you don't have to add the more comparisons ext. (I've added that block because I needed a block like that in my project)

**Comment by GarboMuffin** [comment]
you have to use Cast.compare or this will break horribly when it gets a string containing a number instead of an actual number

**Comment by MaelkMark** [comment]
Thanks for the correction and adding the blocks to the extension!

**Pull request merged**
