### PR TITLE
JeremyGamer13/tween: add easier blocks

### PR DESCRIPTION
**Pull request by GarboMuffin**
- Supercedes https://github.com/TurboWarp/extensions/pull/727
 - Supercedes https://github.com/TurboWarp/extensions/pull/766

image

### CODE REVIEW

**Comment by Martinelplayz** [comment]
YESSS! I can't wait to use this!
image

thank you so much :)

**Comment by asherlr23** [comment]
W

**Comment by hdboye** [comment]
When's this getting merged? It's awesome.

**Comment by fast-food-inception** [comment]
> When's this getting merged? It's awesome.

I agree, when

**Pull request merged**
