### PR TITLE
TurboHookV2 which supports discord's embeds

### PR DESCRIPTION
**Pull request by fcures**
It tested it beforehand to make sure it all works correctly.
It sends embeds data like title, timestamp, color, images, links, thumbnail, footer, and description.

### CODE REVIEW

**Comment by CubesterYT** [comment]
There's no need for this PR. I made a PR that already did this, but I closed it because I decided the current version of TurboHook is too messy have a rewritten version that loads better that I plan to PR soon.

**Comment by CubesterYT** [comment]
This was the update: https://github.com/TurboWarp/extensions/pull/706
I closed it because I rewrote the entire extension from the ground up, that makes it a fully capable normal multi purpose WebHook extension that'll have a lot of useful functionality. So I request this be closed, I don't need the bad code to be expanded on.

**Comment by fcures** [comment]
> This was the update: #706 I closed it because I rewrote the entire extension from the ground up, that makes it a fully capable normal multi purpose WebHook extension that'll have a lot of useful functionality. So I request this be closed, I don't want the bad code to be expanded on.

ok cool, thanks, also how the hell do I use prettier 💀💀💀😭 also where is the better version

**Comment by CubesterYT** [comment]
@fcures you have to either have to install the deck server and command line use prettier using `npm run format`, or use the prettier VSCode extension

**Comment by CubesterYT** [comment]
The better version still needs one more thing till release

**Comment by fcures** [comment]
> The better version still needs one more thing till release

Alright cool

**Pull request closed without merging**
