### PR TITLE
Add sorting blocks to JSON.

### PR DESCRIPTION
**Pull request by SurvExe1Pc**
Blocks added:
image

image
allows you to sort some numbers in ascending or descending order using a algorithm in the dropdown[f1]

image
allows you to sort letters / words in ascending or descending order.

Sorting option for numbers [f1]:
image

image

Difference from list utils version:
(video from @LilyMakesThings)
https://github.com/TurboWarp/extensions/assets/135030944/bf13697f-d459-4b25-8d34-2b4b3822a7dd

### CODE REVIEW

**Comment by BlueDome77** [comment]
Awesome! (づ>◞ <)づ

**Comment by Skyhigh173** [comment]
great! however there's two JSON extension poll about sorting.

**Comment by SurvExe1Pc** [comment]
> great! however there's two JSON extension poll about sorting.

yes, I made mine 18hrs before the otherone, but lily wanted the other person to also make a pr.
Its fine.

**Comment by GarboMuffin** [comment]
I don't think having all those sorting algorithms is necessary

**Comment by GarboMuffin** [comment]
if it was just sort ascending/descending I would merge this right now

**Comment by SurvExe1Pc** [comment]
> I don't think having all those sorting algorithms is necessary

well lily is already doing ascending + descending in her list extension so it would be as simple as setting the list to the json and then running the sort you want and then just grabbing it, its like 4 blocks

**Comment by GarboMuffin** [comment]
These still have a place in JSON without using an intermediate list

Ignore all the merge conflicts and don't bother merging master, I will do that later, if you finish this extension

**Comment by GarboMuffin** [comment]
Minified sorting algorithms are unlikely to be useful as comments

**Comment by SurvExe1Pc** [comment]
ok i will update it :D

**Comment by SurvExe1Pc** [comment]
doneeeeeeeeeeeee

**Comment by SurvExe1Pc** [comment]
woohooo!

**Pull request merged**
