### PR TITLE
New extension "Screen Resolution"

### PR DESCRIPTION
**Pull request by shreder95ua**

### CODE REVIEW

**Comment by shreder95ua** [comment]
wtf is literally happening fail after fail

**Comment by shreder95ua** [comment]
i'll better host it somewhere else, this is bullshit

**Comment by NexusKitten** [comment]
The reason it's failing because of eslint, go to the "checks" tab and do what it tells you to do.

**Comment by shreder95ua** [comment]
don't worry, i fixed it. but thanks for the help, i'll use it next time when commiting to other repositories.

**Pull request closed without merging**
