### PR TITLE
Custom_Shader

### PR DESCRIPTION
**Pull request by promissame**
It looks like I spent a lot of time fixing the issue I was having on github, but thankfully I should have successfully PR the repository

### CODE REVIEW

**Comment by CST1229** [comment]
By the way, you don't have to make a new PR every time you make changes. Just commit to your existing branch and it will update.

**Comment by Skyhigh173** [comment]
It's good to add a document/example project

**Comment by promissame** [comment]
我抽点时间整个，或者你做一个PR也行（



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月3日(星期二) 晚上7:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TurboWarp/extensions] Custom_Shader (PR #1068)






添加一个文档/示例项目是很好的

-
直接回复此邮件，在GitHub上查看，或取消订阅.
***@***.***与&gt;.

**Comment by yuri-kiss** [comment]
Pen+v7 works does this and more.

**Comment by promissame** [comment]
This is a long time ago project, I have completed pen v7 functions before pen v5 was released, but it has not been merged for a long time, and I don't want to care about it now (note that the code of this project is very irregular and not strict enough, if you want to use it, please check the specification carefully, I can't guarantee whether it has other problems).

**Comment by yuri-kiss** [comment]
> This is a long time ago project, I have completed pen v7 functions before pen v5 was released, but it has not been merged for a long time, and I don't want to care about it now (note that the code of this project is very irregular and not strict enough, if you want to use it, please check the specification carefully, I can't guarantee whether it has other problems).

Glad to see people still have these old pr's in their notifs, thanks for responding it does help.

Yes this is before pen+ v7 but it exists now which is why I closed it.

**Comment by promissame** [comment]
It's just an act to contribute to the community, thank you for still reading these old PRs

**Comment by yuri-kiss** [comment]
> It's just an act to contribute to the community, thank you for still reading these old PRs

It is the least I can do, you all have been waiting for so long, and such rightfully deserve to be read, even with our slow team.

**Pull request closed without merging**
