### PR TITLE
Big miscalleneous reporter extension

### PR DESCRIPTION
**Pull request by BunkerStriker**

### CODE REVIEW

**Comment by LilyMakesThings** [comment]
This seems reminiscent of a Utilities extension, there's too much variety which ends up hindering a lot of its features.

**Comment by BunkerStriker** [comment]
I've at first made it for myself but wanted to share it, so i did.

**Comment by BunkerStriker** [comment]
I couldn't really just choose a theme so i just made everything i thought of as useful with help from ChatGPT on the more complex blocks

**Comment by NexusKitten** [comment]
There's a few things I noticed about this extension:

1. The theme of "reporters" is vague enough to be considered a "utilities" extension. As @LilyMakesThings pointed out, broad "utilities" extensions aren't very likely to get accepted to the gallery. For a full list of reasons why, see #674.
2. Several blocks from your extension already exist in other extensions. Although there are exceptions, we generally try to add a block once to the extension gallery. Some of the duplicate blocks include:
- Both direction + distance blocks will soon be in Graphics 2D.
- Almost all blocks from Couplers appear in the extension
- Several static blocks, the clamp block, and the "if <> () else ()" block appear in Utilities.
- Almost all JSON blocks appear in the JSON extension.
3. The only block I found with particularly confusing behavior was the block listed below, which seems to strangely prioritize whether it reports as a boolean or a reporter, and can return an empty output if the second setup below is used (empty outputs can break projects).
image
image
4. The extension color is very bright, which may be difficult for visually impaired people to read. Consider darkening the extension colors if possible.
5. Pertaining to the extension ID (Line 32), generally it's better to include your name or initials somewhere in there. For example, "bsreportersbucket" would work.
When it comes to Utilities extensions, I generally suggest splitting up the major functions not already in other extensions to their own extensions. I'm not very experienced with gaussian, however I saw you had multiple blocks pertaining to that, and I'm relatively certain there's not already a gaussian extension on the gallery, so that would make a good extension of it's own. If there's any functions that fit under the umbrella of an extension, however are not currently added, feel free to submit a pull request to add those blocks. The extension gallery is open source, so you're free to submit pull requests to anything as you see fit.

**Comment by GarboMuffin** [comment]
Are there any unique blocks in this extension that are not found in other ones?

**Comment by NexusKitten** [comment]
> Are there any unique blocks in this extension that are not found in other ones?

image

**Comment by GarboMuffin** [comment]
- map can go in utilities (Arduino has a similar function, it is quite useful)
 - PRNG should be expanded into a dedicated PRNG extension
 - Probability stuff should be expanded into a dedicated probability extension. There is a *lot* that can be done here.
 - i do not anticipate matrix at or wait then to be useful anywhere

**Pull request closed without merging**
