### PR TITLE
All my main extensions

### PR DESCRIPTION
**Pull request by Mistium**
A couple of extensions that i've made :P

### CODE REVIEW

**Comment by LilyMakesThings** [comment]
Please keep pull requests to 1 extension per pull requests. This is a nightmare to review.

**Comment by Mistium** [comment]
> Please keep pull requests to 1 extension per pull request. This is a nightmare to review.

hmm yea. I mean, id say im trustworthy enough to not put fucking malware in it lol

**Comment by Mistium** [comment]
i get it tho :3 i have to manage my networking protocols 💀

**Comment by LilyMakesThings** [comment]
> > Please keep pull requests to 1 extension per pull request. This is a nightmare to review.
> 
> hmm yea. I mean, id say im trustworthy enough to not put fucking malware in it lol

Unfortunately no one is trustworthy on here. Please close this pull request and separate the extensions.

**Comment by Mistium** [comment]
> > > Please keep pull requests to 1 extension per pull request. This is a nightmare to review.
> > 
> > 
> > hmm yea. I mean, id say im trustworthy enough to not put fucking malware in it lol
> 
> Unfortunately no one is trustworthy on here (especially those who have not read the contributing guidelines). Please close this pull request and separate the extensions.

yea i meant to close it and forgot lol, imma go make a extension gallery cos this seems like too much effort and would be cool to make one in osl

**Comment by Mistium** [comment]
ig i kinda expected this to be more like talking to people and less like talking to an organisation representative

**Comment by GarboMuffin** [comment]
the only "organisation representative" here is me, everyone else is just a developer with some suggestions

one-extension-per-pull-request is the expectation just so they can be reviewed & merged independently; a problem with Frame Plus should not hold up Key History. the problem is not so much malware but the need to maintain these in working condition indefinitely and that they are covered under my bug bounty

**Comment by Mistium** [comment]
> the only "organisation representative" here is me, everyone else is just a developer with some suggestions
> 
> one-extension-per-pull-request is the expectation just so they can be reviewed & merged independently; a problem with Frame Plus should not hold up Key History. the problem is not so much malware but the need to maintain these in working condition indefinitely and that they are covered under my bug bounty

Ahhh, that makes a lot of sense

**Pull request closed without merging**
