### PR TITLE
Added my "Geolocation" extensions

### PR DESCRIPTION
**Pull request by samuellouf**
I created a Geolocation extension.
Here are the blocks : 
geolocation extension blocks

Tell me what you think.

### CODE REVIEW

**Comment by CubesterYT** [comment]
I will like to say three things. One, is this extension going to be used for checking user location? Like apps like maps and other programs? Two, what is the timeout blocks for? Three, in index.ejs, the banner must be a .svg image banner, not your .js file, so create a image banner that is 600 wide and 300 tall and add the .svg to a folder named to your name in the image folder.

**Comment by SurvExe1Pc** [comment]
dangerous

**Comment by SurvExe1Pc** [comment]
unless you makin a maps app lol

**Comment by LilyMakesThings** [comment]
Add an IP Address block while you're at it

**Comment by NexusKitten** [comment]
I personally feel like a Geolocation Extension poses too much of a security risk to be admitted to the gallery. If the extension instead outputted more vague information such as country, continent, or even nearest city, it would be understandable, however longitude and latitude are the user's _exact location_. Other than using it for fetch requests, I can only imagine this being used maliciously.
It's a neat idea, I just feel it isn't very safe.

**Comment by samuellouf** [comment]
> One, is this extension going to be used for checking user location? Like apps like maps and other programs?

Yes.

>  Two, what is the timeout blocks for?

The extension will try to get the user's current location. If a certain amount of time is passed, the extension will return an error.

And also @NexusKitten is right, it's a dangerous extension.

**Comment by GarboMuffin** [comment]
if we just add something like Scratch.canGeolocate() that asks the user, this is fine

**Comment by CubesterYT** [comment]
YES REVIVED!!!

**Comment by horizontal-shading** [comment]
Remove latitude and longitude, and replace it with current city and current country. That would be safer, I _think_.

**Comment by GarboMuffin** [comment]
as long as it has user consent, precise position to the millimeter is perfectly fine

**Comment by CubesterYT** [comment]
Dang bruh.

**Comment by samuellouf** [comment]
Hello y'all! I finally published the extension. Have a look at the [pull request](https://github.com/TurboWarp/extensions/pull/1943) if you want to. Thank you all for guidance and your support!

**Pull request closed without merging**
