### PR TITLE
New line block

### PR DESCRIPTION
**Pull request by TheShovel**
Does this need explanation?
image

### CODE REVIEW

**Comment by softedco** [comment]
I was thinking about this too, btw you can make the text "\\n" so it's not that long for what's just a newline character

**Comment by TheShovel** [comment]
It's easier to understand I think.

**Comment by softedco** [comment]
> It's easier to understand I think.

Yeah but it would also look unnecessarily huge when multiple of these are used in a join nest, if you're still fine with that, then might I suggest adding a block that replaces "\\\\n" with just "\\n"? Also, why is it a boolean? I know booleans are practically reporters but better, but I can't imagine a scenario where it would be used as a condition and not just replaced with `<(true)>` or `<not<>>`.

**Comment by TheShovel** [comment]
image

**Comment by GarboMuffin** [comment]
call it newline, not \n, average Scratch users will see that and try to report a bug

**Comment by TheShovel** [comment]
Changed it, again.

**Pull request merged**
