### PR TITLE
Add "Variables Extended"

### PR DESCRIPTION
**Pull request by Ashimee**
Allows for better variable control and usage. (Some of it is VERY json focused)

Blocks:
image

note:
  delete and create variable blocks are missing because they break when packaged and are unsafe / made redundant

### CODE REVIEW

**Comment by Ashimee** [comment]
i hate git sometimes

**Comment by VoxelDoesCode** [comment]
I tested this, and I do want to point out that in `changeVar`, if a variable is not available, it seemingly runs forever (or a long time, haven't tested when it ended). So if you use it in a loop, it stops completely when on the `changeVar` block. The `setVar` block does nothing and lets the loop continue, as expected.

**Comment by Ashimee** [comment]
> I tested this, and I do want to point out that in `changeVar`, if a variable is not available, it seemingly runs forever (or a long time, haven't tested when it ended). So if you use it in a loop, it stops completely when on the `changeVar` block. The `setVar` block does nothing and lets the loop continue, as expected.

weird, i did not notice thx

**Comment by Martinelplayz** [comment]
why is this closed then?

**Comment by Ashimee** [comment]
I know what I just did, It was on purpose.

**Pull request closed without merging**
