### PR TITLE
Profanity remover extension

### PR DESCRIPTION
**Pull request by TheShovel**
A similar extension to one of the ones mentioned in #99

### CODE REVIEW

**Comment by GarboMuffin** [comment]
Please don't put example profanity here...

**Comment by TheShovel** [comment]
Sorry, didn't think that word was that big of a deal.

**Comment by TheShovel** [comment]
There are a lot of things already made that can do this, but none (that I can find) that are gonna work with just pure js. I will draft this, and if you or someone else has another idea I'll be sure to try it.

**Comment by GarboMuffin** [comment]
You can absolutely do what I described with pure JS

**Comment by showierdata9978** [comment]
AFAIK You should not do it client side, but this could be useful in a no "server" environment. (like if your using an example CL server)

**Comment by TheShovel** [comment]
Ok, so I am trying to make it client side, and translate the array to binary, but when I translate it back, and use regex I get
`Invalid regular expression: /[/: Unterminated character class`

**Comment by TheShovel** [comment]
> AFAIK You should not do it client side, but this could be useful in a no "server" environment. (like if your using an example CL server)

Yeah, but Garbo asked for it. I'll host the api version on my github, but I still wanna get this one done.

**Comment by softedco** [comment]
> Ok, so I am trying to make it client side, and translate the array to binary, but when I translate it back, and use regex I get
> `Invalid regular expression: /[/: Unterminated character class`

[ is a meta character so you write it like so \\[

**Comment by TheShovel** [comment]
I have made it client side, and the words are base64 encrypted.
Also added the option to change what it is replaced with.

**Comment by GarboMuffin** [comment]
https://extensions.turbowarp.org/TheShovel/profanity.js

I do not know if we want this listed on the website

**Comment by TheShovel** [comment]
It's a harmless extension to help people make stuff like chat apps safer for younger people. I don't see a reason why this shouldn't be on the website.

**Comment by softedco** [comment]
> It's a harmless extension to help people make stuff like chat apps safer for younger people. I don't see a reason why this shouldn't be on the website.

I believe there is more of a concern on how the Scratch Team would deal with the website having this extensiom on the front page, but I also believe that it's fine since the scratch website itself has bad word filtering.

**Pull request merged**
