### PR TITLE
Add Run JS extension [Replaced eval-no new function()]

### PR DESCRIPTION
**Pull request by RayFB-13**
Adds an extension that runs JS.

### CODE REVIEW

**Comment by showierdata9978** [comment]
> It's still arbitrary js which can be used mauliciously.

it would really only work with already injected js.  This only runs functions.

**Comment by GarboMuffin** [comment]
Which functions is this actually useful for?

**Comment by showierdata9978** [comment]
basically none, as it can only run global objects

**Comment by CST1229** [comment]
> > It's still arbitrary js which can be used mauliciously.
> 
> it would really only work with already injected js. This only runs functions.

`eval (eval) (alert("hakd"))`

**Comment by GarboMuffin** [comment]
It does seem the code refuses to run eval now so maybe it is secure (maybe)

My concern here is that if this is only useful for things like `alert`, `confirm`, and `prompt`, it would make more sense to just have an extension with specific blocks for those.

**Comment by Xeltalliv** [comment]
> It does seem the code refuses to run eval now so maybe it is secure (maybe)

image

**Comment by GarboMuffin** [comment]
I'm closing this because making this safe is not trivial and the usefulness is unclear per above discussions.

You are welcome and encouraged to submit extensions that expose safe and intentional wrappers around functions on window or any other Web API

**Pull request closed without merging**
