### PR TITLE
Add Browser Utilities Extension

### PR DESCRIPTION
**Pull request by NexusKitten**
A handful of blocks for receiving and setting browser information.

image
image

It should go without saying that most if not all of these blocks will not function when the project is packaged into an exe file.

### CODE REVIEW

**Comment by LilyMakesThings** [comment]
4 of these blocks exist within other extensions; in network (dark green) they're far more precise. Consider revising the existing blocks to at least match the functionality.

image

**Comment by LilyMakesThings** [comment]
It's nice to finally see alert, confirm and prompt have a home outside of LMS Utils :') only a few more blocks until that extension is finally obsolete! woohoo!

**Comment by GarboMuffin** [comment]
I think I will make isonline just check navigator.online. It's not great, but it doesn't involve making requests to a website that many schools block for one reason or another

**Comment by GarboMuffin** [comment]
this would probably be not very affected by #674

**Comment by GarboMuffin** [comment]
i wonder if we just rename navigator to browser utilities and put everything from this in there

**Comment by NexusKitten** [comment]
> i wonder if we just rename navigator to browser utilities and put everything from this in there

Possibly, I feel like some of the blocks in network would fit under the umbrella of "Browser Utilities" (specifically the ones below), however I feel like the get/post blocks and blocks about network specs are out there enough to warrant their own extension. It's ultimately up to you, however I'd rather just have them next to each other and move some blocks over.
image

**Comment by NexusKitten** [comment]
> 

If this message makes no sense, I'm sorry. I have trouble remembering the differences between Network and Navigator; they have very similar names and functions. You can merge Browser Utilities and Navigator

**Comment by NexusKitten** [comment]
@GarboMuffin I've made several changes, most notably merging this extension with Navigator as you suggested.

This extension is now ready to merge.

**Review by Eliaspierce — APPROVED** [review]

**Comment by NexusKitten** [comment]
Updated to include new blocks from #759

**Comment by NexusKitten** [comment]
@GarboMuffin any reason lint isn't running for me?

**Comment by LilyMakesThings** [comment]
> @GarboMuffin any reason lint isn't running for me?

You have conflicts

**Pull request closed without merging**
