### PR TITLE
Proposal to Modify Existing Extensions in Violation of the Guidelines (PMEEVG)

### PR DESCRIPTION
**Pull request by PPPDUD**
Name says it all.

### CODE REVIEW

**Comment by LilyMakesThings** [comment]
I don't exactly understand what you mean by "modify", but the reason existing extensions that were passed before the guidelines were changed have remained in-tact is due to backwards compatibility.

**Comment by Xeltalliv** [comment]
It seems like your text editor, storage or ram have issues as after your editing, some random sections of text got duplicated and overwrote other random sections of text.

As for suggestion itself, it doesn't make much sense as the extensions that could be fixed were already fixed. The ones remaining are impossible to fix. The only way to make "McUtils" which was intentionally designed as a joke comply with "no joke extensions" rule is to remove it. Same goes for duplicate functionality and broad utilities extensions - they can only be fixed by either removing them or some of their features. But nothing can be removed for compatibility reasons.

**Comment by LilyMakesThings** [comment]
Even just hiding the extensions or delisting them can cause problems, for months after LMS Utilities was delisted Garbo and I received comments on our profile asking where it was, which is the only reason why it's still up. It's really hard to "remove" extensions or features from extensions.

**Comment by GarboMuffin** [comment]
If you think you can modify them into compliance then you are welcome to try

**Pull request closed without merging**
