### PR TITLE
true-fantom/couplers: add more couplers

### PR DESCRIPTION
**Pull request by BlueDome77**
Added COLOR, ANGLE, MATRIX, and NOTE reporters from LMS Utils.

### CODE REVIEW

**Comment by SurvExe1Pc** [comment]
> Added COLOR, ANGLE, MATRIX, and NOTE reporters from LMS Utils.
> 
> Someone tell me how to create separate PRs please!

you have to use branches

**Comment by GarboMuffin** [comment]
Can you describe the intent of `numericalEncodingV2`?

**Comment by Flappy25** [comment]
The matrix input is awesome!

**Comment by BlueDome77** [comment]
> Can you describe the intent of `numericalEncodingV2`?

Way more convenient:

block_9_11_2023-3_08_02 PM
VS:

block_9_11_2023-3_09_15 PM

**Pull request merged**
