### PR TITLE
Add Clipboard Extension

### PR DESCRIPTION
**Pull request by AdamMady**
### Description: A few blocks that interact with the user's clipboard. Created by [AdamMady2](https://scratch.mit.edu/users/AdamMady2/)

### CODE REVIEW

**Comment by LilyMakesThings** [comment]
Another one?

**Comment by AdamMady** [comment]
> Another one?

one already exists?

**Comment by AdamMady** [comment]
dang I should've done my research but I'll leave this here since it has more features than the other one

**Comment by 0832k12** [comment]
Yes, you are right.
**But** I think your newly added block can be achieved through variables, an extension should only do its job.

**Comment by LilyMakesThings** [comment]
> Yes, you are right. **But** I think your newly added block can be achieved through variables, an extension should only do its job.

And the other extension has blocks that are not in this extension but can't be replicated easily.

**Comment by NexusKitten** [comment]
If you don't mind, I'll probably submit another pull request that merges this and #632 into one, since we don't exactly need 2 clipboard extensions. With that being said, both of you will still receive credit for your work.

**Comment by GarboMuffin** [comment]
closing in favor of https://github.com/TurboWarp/extensions/pull/667

**Pull request closed without merging**
