### PR TITLE
Add network extension

### PR DESCRIPTION
**Pull request by TrueFantom**
Several blocks for working with Internet:
Screenshot_164

I didn't add "fetch DELETE" and "fetch PATCH" blocks because I don't understand how these methods work. If someone needs it, I will add them.

*Thanks to  @TheShovel  for code of ping block.

*Method String() for arguments is need.

### CODE REVIEW

**Comment by showierdata9978** [comment]
post should have a content-type option that is default text, for stuff like POST`in JSON

**Review by showierdata9978 — CHANGES_REQUESTED** [review]
post should have a content-type option that is default text, for stuff like POST`in JSON

**Comment by TrueFantom** [comment]
@showierdata9978

As I understand it, you are proposing to add menu with options "string" and "json". If "string" is selected, the code that exists now is executed. If "json" is selected, BODY is converted to JSON by method: "BODY = JSON.stringify(BODY);" and then same code. Did I understand you correctly?

**Comment by showierdata9978** [comment]
it should be arbitrary, as the header in html spec is arbitrary

**Comment by CST1229** [comment]
> s I understand it, you are proposing to add menu with options "string" and "json". If "string" is selected, the code that exists now is executed. If "json" is selected, BODY is converted to JSON by method: "BODY = JSON.stringify(BODY);" and then same code. Did I understand you correctly?

I think they mean a content type option that sets the `Content-Type` header to any string.

**Comment by Samq64** [comment]
This should probably be merged with the fecth extension.

**Comment by GarboMuffin** [comment]
Merge this into the existing `fetch` extension

**Comment by GarboMuffin** [comment]
And keep the websocket pinging stuff in the websocket pinging extension, we don't need to duplicate it in the fetch extension.

A way to specify the Content-Type of the body will be required. A way to get the status code of the response and other response headers would also be interesting.

**Review by GarboMuffin — CHANGES_REQUESTED** [review]
See my previous comments

**Pull request closed without merging**
