### PR TITLE
Get from JSON array

### PR DESCRIPTION
**Pull request by TheShovel**
A reporter block that lets you get a item from a JSON array.

### CODE REVIEW

**Comment by TheShovel** [comment]
Sorry for adding TextBox.js by mistake. Removed it now.

**Comment by GarboMuffin** [comment]
I'm not sure if this is needed because you can already do

image

**Comment by TheShovel** [comment]
It wold be more convenient and easier to understand, but I get your point, this is not really needed.

**Comment by GarboMuffin** [comment]
Closing for now per previous comment that this can already be done using other blocks

**Pull request closed without merging**
