### PR TITLE
Bug fix

### PR DESCRIPTION
**Pull request by True-Fantom**

### CODE REVIEW

**Comment by True-Fantom** [comment]
@GarboMuffin https://github.com/TurboWarp/extensions/pull/381#issuecomment-1548383701

**Comment by GarboMuffin** [comment]
we should instead change the blocks because "00101010100" and "10100101000101010010101001010101010100001010010101010" are clearly valid binary; don't see any need to restrict it to 32 bits exactly

**Comment by True-Fantom** [comment]
@GarboMuffin This is due to the structure of the number in js, exactly 32 bits are allocated to the number, so there are 2 options: either remove all the leading zeros from the values, or leave it as it is. The second option is more convenient, since the blocks by type set the letter, will work as a set bit, without any problems.

**Comment by True-Fantom** [comment]
@GarboMuffin Plus, in the second option, you do not need to change the code of the returned values.

**Comment by True-Fantom** [comment]
In this pr, I fixed all the main problems, returned the old bit values , replaced "binary" with "number bits", since this is much more correct, replaced the record of cyclic shifts so that they correspond to the programming languages and previous shifts. So, I think it needs to be accepted, because everything is done here naturally.

**Comment by True-Fantom** [comment]
@GarboMuffin ?

**Pull request closed without merging**
