### PR TITLE
Add CORS Proxy docs/extension

### PR DESCRIPTION
**Pull request by NexusKitten**
AN extension to help teach about CORS errors, and hopefully avoid future GitHub issues for them lol.

This is my first time using the documentation API, lmk if I messed anything up.

image
image

# **_Any feedback/upvotes (👍) are apprecieted!_**

### CODE REVIEW

**Comment by SurvExe1Pc** [comment]
does this support all origins also

**Comment by NexusKitten** [comment]
> does this support all origins also

Yep! Currently it supports allorigins and corsproxy.io

**Comment by NexusKitten** [comment]
I've decided to draft this extension due to changes to Documentation and index.ejs, will get around to fixing soon 👍

**Comment by NexusKitten** [comment]
Finally updated this extension for new repository-wide updates.

This extension should be ready to merge.

**Pull request closed without merging**
