### PR TITLE
Create TurboMD.js

### PR DESCRIPTION
**Pull request by David-Orangemoon**
MarkDown reader for Turbowarp

### CODE REVIEW

**Comment by David-Orangemoon** [comment]
Banner
The logo

**Comment by LilyMakesThings** [comment]
Isn't it mark**up**, not mark**down**?

**Comment by David-Orangemoon** [comment]
> Isn't it mark**up**, not mark**down**?

Html
Hyper Text Markdown Language 

MD
Markdown

**Comment by CST1229** [comment]
> Html
> Hyper Text Markdown Language

image

**Comment by David-Orangemoon** [comment]
Shhhhhhhh

**Comment by GarboMuffin** [comment]
what does this, like, do?

**Comment by David-Orangemoon** [comment]
Reads markdown

**Comment by GarboMuffin** [comment]
Okay, I see what this does

Let's rename it to something like XML Parser or Turbo XML. Markdown is a separate thing

**Comment by David-Orangemoon** [comment]
Ok will do that when I get home

**Comment by David-Orangemoon** [comment]
Also it doesn't just support xml

**Comment by GarboMuffin** [comment]
HTML and SVG are both based on XML. You can mention this in the extension's description

**Comment by SurvExe1Pc** [comment]
i finally found a use for it, removing word document passwords!

**Comment by David-Orangemoon** [comment]
Closing due to inaction

**Pull request closed without merging**
