### PR TITLE
Update strings 20240515

### PR DESCRIPTION
**Pull request by Eaielectronic**
The extension allows you to create bubbles with scrolling texts, if you include HTML tags in the text of the blocks, then it will apply the styles to the text in the bubble: for example, if you write Example. it will write example in italics in the bubble. I hope you are interested in these extensions and thank you for nothing for your attention to this message.

### CODE REVIEW

**Comment by Thebloxers998** [comment]
We need this, it's PERFECT for game diologs

**Review by Thebloxers998 — APPROVED** [review]
Should be added

**Comment by Eaielectronic** [comment]
Super, thanks a lot

**Comment by Thebloxers998** [comment]
Is it possible to make the text bold

**Comment by Eaielectronic** [comment]
You can already set a font in the bubble creation block by default Arial and to bold just set the strong html tags example:<strong>this is a bold word</strong>. I hope I've answered your questions.

**Comment by Eaielectronic** [comment]
This balise is <strong>

**Comment by Thebloxers998** [comment]
Oh ok

**Pull request closed without merging**
