### PR TITLE
Add Monitor Styles

### PR DESCRIPTION
**Pull request by TheShovel**
Custom CSS extension, that lets you modify the CSS for variable and list displays.

Blocks:
- Set CSS color of [general text, general background, general border, variable value box, variable value text, list label, list footer, list value box, list value text] to [Color]
- Set CSS border size to [Number]
- Set CSS roundness of [general borders, variable value box borders, list value box borders] to [Number]
- Set CSS list scroll rule to [auto, hidden]
- Set CSS position of variable with label [String] to x:[Number] y:[Number]
- Set CSS position of list with label [String] to x:[Number] y:[Number]
- Make a CSS gradient with [Color] and [Color] at angle [Angle]

Screenshot from 2023-06-14 13-27-59

All blocks change CSS properly in the editor view, and in the packaged project.

Most professional banner ever made.
CustomCSS

I beg you, just accept the pull request without making me fix Eslint errors, please.
The code is perfect, it's like Bill Gates himself wrote it. There CAN'T be errors. It is impossible.

### CODE REVIEW

**Comment by LukeManiaStudioss** [comment]
Good lord the amount of lint errors, might wanna run `npm run fix` on that lol

**Comment by CST1229** [comment]
image

**Comment by GarboMuffin** [comment]
warnings are unimportant and can be ignored (I fix them myself) -- don't pester people about them

errors are more serious -- try to get those fixed

**Comment by TheShovel** [comment]
Eslint says 'scaffolding' is not defined, but it is, even though it is a packager only thing. It shouldn't be an error.

**Comment by LilyMakesThings** [comment]
> Eslint says 'scaffolding' is not defined, but it is, even though it is a packager only thing. It shouldn't be an error.

Eslint will also say "Blockly" or "ScratchBlocks" isn't defined. You just need to disable eslint for it:
```
// @ts-expect-error - scaffolding not typed yet
// eslint-disable-next-line no-undef
```

**Comment by TheShovel** [comment]
I fixed every Eslint error.
I hope you stop laughing at there being more warnings than lines of code.

**Comment by TheShovel** [comment]
Blocks now follow these settings.
image

**Comment by TheShovel** [comment]
Please wait until I change from using `isPackaged` to checking for scaffolding.

**Comment by TheShovel** [comment]
Should be ready now.

**Comment by TheShovel** [comment]
Is this going to get pushed, or is there something else you have to do before?

**Comment by GarboMuffin** [comment]
- some block names could be more clear but that's changeable later
 - background color styles need to make sure that the CSS is actually a color or gradient and not a url() which would allow unrestricted fetching
 - Custom CSS isn't a great name for this; something like custom monitor style would make more sense

**Comment by TheShovel** [comment]
Got it. Going to remake the icons as well, since they are literally made in MS Paint.

**Comment by TheShovel** [comment]
This should be enough to check for URLs.
image

**Comment by BlueDome77** [comment]
What if the user wants to reset the colors/positions to default?

**Comment by BlueDome77** [comment]
Some things that are missing:

Normal readout for Variables color
Variable's Slider
"Ask for () and wait" Input color

**Comment by TheShovel** [comment]
> Some things that are missing:
> 
> Normal readout for Variables color Variable's Slider "Ask for () and wait" Input color

Normal readout for Variables color? that already is a thing.

**Comment by TheShovel** [comment]
I'm going to add customization for the ask input soon.

**Comment by TheShovel** [comment]
I forgot to mention, but with this commit, I also fixed loading images from links in the packager.

**Comment by BlueDome77** [comment]
I think Monitor Styles needs a proper documentation page like AR and Bitwise.

**Comment by TheShovel** [comment]
This won't get any more updates for now (from me at leasat).
Everything works both in the packager and in the editor. Every value is tested and has no errors.
I hope this gets finally accepted.

**Comment by BlueDome77** [comment]
> > I think Monitor Styles needs a proper documentation page like AR and Bitwise.
> 
> 
> 
> It's not that complicated. People can figure it out.

I mean replace the button in the editor with an actual documentation page

**Comment by TheShovel** [comment]
> > > I think Monitor Styles needs a proper documentation page like AR and Bitwise.
> > 
> > 
> > It's not that complicated. People can figure it out.
> 
> I mean replace the button in the editor with an actual documentation page

No. Lol.

**Comment by BlueDome77** [comment]
Would it be possible to resize variables and lists?

**Comment by TheShovel** [comment]
> Would it be possible to resize variables and lists?

Yes, but I said I won't add anything more until Garbo merges this.

**Comment by GarboMuffin** [comment]
My last concern with this is that backgrounds and colors are both handled by "set color of [ ] to [ ]". Would it make sense to have a separate "set background of [ ] to [ ]", especially because backgrounds allow things like gradients and images while normal text color does not?

**Comment by TheShovel** [comment]
> 

I would keep it in the same block. It keeps stuff a little cleaner.

**Comment by TheShovel** [comment]
I fixed some stuff.
This is now ready to be merged.

**Comment by mudkipdev** [comment]
> Would it be possible to resize variables and lists?
+1, can this be added?

**Pull request merged**
