### PR TITLE
Add Project Extension

### PR DESCRIPTION
**Pull request by 0832k12**
image

### CODE REVIEW

**Comment by Skyhigh173** [comment]
Wow you used Chinese characters as variable name

**Comment by snowboyz0825** [comment]
Oh i'm gonna have some fun with this actually

**Comment by Thebloxers998** [comment]
Why did you close this PR for?

**Comment by yuri-kiss** [comment]
> Why did you close this PR for?

it exists in asset manager

**Comment by Thebloxers998** [comment]
> > Why did you close this PR for?
> 
> it exists in asset manager

Oh ok

**Pull request closed without merging**
