### PR TITLE
Lukewarm Fix | Pen+ v6

### PR DESCRIPTION
**Pull request by David-Orangemoon**

### CODE REVIEW

**Review by LilyMakesThings — APPROVED** [review]
see you in 6 months

**Comment by horizontal-shading** [comment]
> see you in 6 months

See you in 999999999 lifetimes

**Comment by GarboMuffin** [comment]
sorry for delay, although things like this can be reviewed faster if the diff is not every line in the extension

**Comment by GarboMuffin** [comment]
i will trust you know what you're doing with pen+

(if the original diff looked as simple as the one after formatting, it could've been merged same day)

**Pull request merged**
