### PR TITLE
OAUTH 

### PR DESCRIPTION
**Pull request by Thebloxers998**
A extension

### CODE REVIEW

**Comment by Thebloxers998** [comment]
Don't worry guys, I'm sure it's server sided

**Comment by SharkPool-SP** [comment]
all this extension does is just generate a link that you still gave to find yourself?

**Comment by Thebloxers998** [comment]
> all this extension does is just generate a link that you still gave to find yourself?

I'm still working on extension

**Comment by SharkPool-SP** [comment]
aight

**Comment by Thebloxers998** [comment]
> > all this extension does is just generate a link that you still gave to find yourself?
> 
> I'm still working on extension

Anyways, how did u get access to extension

**Comment by Thebloxers998** [comment]
> aight

I'm thinking on how to use api

**Comment by Thebloxers998** [comment]
> > aight
> 
> I'm thinking on how to use api
How to make it use api*

**Comment by Thebloxers998** [comment]
Closed because it's too hard

**Comment by Thebloxers998** [comment]
> Closed because it's too hard

And I don't think it works

**Comment by Thebloxers998** [comment]
Use [https://github.com/TurboWarp/extensions/pull/1757](url)

**Pull request closed without merging**
