### PR TITLE
Add high contrast colors to listed extensions

### PR DESCRIPTION
**Pull request by DNin01**
Scratch will soon be introducing a High Contrast color mode to increase text contrast on blocks. To help us with the process of getting the extensions blocks to adapt to this, I have gone ahead and updated every extension listed on the website with high contrast colors.

These changes modify the fill and stroke colors of each extension. Unfortunately, I overlooked hardcoding dropdown menu colors at the time, but those can probably be auto-generated based on the fill color, or maybe you can do that for me. Sorry about that!

**This is not ready to merge by itself.** This is just the data - we still need a way to use these new colors.

You may make any edits or corrections as you see fit. I didn't test the code I changed and there may be some mistakes.

### CODE REVIEW

**Comment by David-Orangemoon** [comment]
For the newgrounds api I would reccomend using these colors as the Newgrounds API colours
color1: "#FFC322",
color2: "#B96F10",
color3: "#1B1717",
as they are newgrounds official High Contrast colours

color1: "#85C4E0",
color2: "#AED8EA",
color3: "#57A8CB",
for sensing plus as these are the official scratch labs sensing colours

color1: "#13ECAF",
color2: "#75F0CD",
color3: "#1DBB8E",
for pen+ since this is also the default extension High Contrast colour

color1: "#CCB3FF",
color2: "#DDCCFF",
color3: "#A888EA",
for looks plus

**Comment by David-Orangemoon** [comment]
Also

color1: '#FFBE4C',
color2: '#FFDA99',
color3: '#CF8B17',

for clones+

color1: '#FFA54C',
color2: '#E78019',
color3: '#E78019',
for runtimeVariables since these are the variable colors for high contrast
The original on top the scratch labs on the bottom

**Comment by LilyMakesThings** [comment]
> Also
> 
> color1: '#FFBE4C', color2: '#FFDA99', color3: '#CF8B17',
> 
> for clones+
> 
> color1: '#FFA54C', color2: '#E78019', color3: '#E78019', for runtimeVariables since these are the variable colors for high contrast The original on top the scratch labs on the bottom

temporary variables don't use the standard variable colours, they use a colour in between variables and lists

**Comment by David-Orangemoon** [comment]
> > Also
> > color1: '#FFBE4C', color2: '#FFDA99', color3: '#CF8B17',
> > for clones+
> > color1: '#FFA54C', color2: '#E78019', color3: '#E78019', for runtimeVariables since these are the variable colors for high contrast The original on top the scratch labs on the bottom
> 
> temporary variables don't use the standard variable colours, they use a colour in between variables and lists

shoot didn't see that sorry.

**Comment by GarboMuffin** [comment]
I don't think this is how we'll be doing this

**Pull request closed without merging**
