### PR TITLE
Relist LMS Utilities

### PR DESCRIPTION
**Pull request by LilyMakesThings**
In response to:
https://github.com/TurboWarp/extensions/issues/703
https://github.com/TurboWarp/extensions/issues/719

As well as dozens of comments asking where it went in various places.

I took this down for a reason but it's not worth having it down if we keep getting comments about it.

It needs to be renamed, and needs a new thumbnail. Suggestions open.

## 👍 and 👎 are particularly important here.

### CODE REVIEW

**Comment by LilyMakesThings** [comment]
Current name suggestions:
- Lily Makes Utilities
- Lots of Miscellaneous Stuff
- Levy Utilities

**Comment by horizontal-shading** [comment]
Lily's Miscellaneous Utilities would be a good name

**Comment by LilyMakesThings** [comment]
> Lily's Miscellaneous Utilities would be a good name

I'll add it to the list

**Comment by GarboMuffin** [comment]
figure out a name and i'll merge it

**Comment by LilyMakesThings** [comment]
I decided on the name, I don't have a single clue as to what thumbnail I should give this so I might leave this up to the lovely volunteers of https://github.com/TurboWarp/extensions/issues/90.

**Comment by horizontal-shading** [comment]
Lily's Toolbox, I like it lol

**Pull request merged**
