### PR TITLE
Update gamepad.js

### PR DESCRIPTION
**Pull request by Meehdrescher**
Now featuring blocks to get and set deadzones.

Tested with a project that uses the current version, it didn't break anything and it works fine :)

### CODE REVIEW

**Comment by Martinelplayz** [comment]
did you combine it with https://github.com/TurboWarp/extensions/pull/881 ?

**Comment by Meehdrescher** [comment]
no

Am Do., 7. Sept. 2023 um 16:49 Uhr schrieb MartinelplayzYT <
***@***.***>:

**Comment by Martinelplayz** [comment]
would you be ok with me keeping my PR up?

**Comment by Meehdrescher** [comment]
> would you be ok with me keeping my PR up?

I'm fine with that, you can keep the PR

**Comment by GarboMuffin** [comment]
Redundant since https://github.com/TurboWarp/extensions/commit/e746d762ce2acc571a65be75c2fe6c07fc57fc86

**Pull request closed without merging**
