### PR TITLE
Add resolve block to math.js

### PR DESCRIPTION
**Pull request by TheShovel**
Screenshot_20230810_185303

### CODE REVIEW

**Comment by SurvExe1Pc** [comment]
oo

**Comment by LilyMakesThings** [comment]
finally, math in the math extension

**Review by NexusKitten — APPROVED** [review]
This version of Math.js is slightly out of date (it doesn't have the metadata header like it now does), but other than that, everything looks good!

**Comment by TheShovel** [comment]
> This version of Math.js is slightly out of date (it doesn't have the metadata header like it now does), but other than that, everything looks good!

Garbo has to resolve that. This PR was made before those headers existed.

**Comment by GarboMuffin** [comment]
Closing per request of author

**Pull request closed without merging**
