### PR TITLE
Key Utils Beta

### PR DESCRIPTION
**Pull request by Aness6040**
Can you add Key Utils Extnsion Please? I tried to follow contributing instructions. Can i contribute please?

### CODE REVIEW

**Comment by Aness6040** [comment]
Can you add Key Utils Extension Please? I tried to follow contributing instructions. Can i contribute please?

**Comment by Aness6040** [comment]
@GarboMuffin Format Crashed

**Comment by CubesterYT** [comment]
@Aness6040, I already have a PR for a extension similar to this that is also smaller and works way better. #982

**Comment by CubesterYT** [comment]
Also know constantly asking Garbo to add an extension won't help.

**Comment by LilyMakesThings** [comment]
> Also note you must use branches instead of your master branch.

Actually that's not a requirement

**Comment by LilyMakesThings** [comment]
> @Aness6040, I already have a PR for a extension similar to this that is also way smaller and works way better. This is the link ==> #982.

Your extension is unfinished

**Comment by Aness6040** [comment]
> > @Aness6040, I already have a PR for a extension similar to this that is also way smaller and works way better. This is the link ==> #982.
> 
> Your extension is unfinished

I didn't know you did something similar but I'm only a beginner and please accept that I'm part of the contribution I planned an extension for Minecraft servers

**Comment by Aness6040** [comment]
@LilyMakesThings If my extension is not finished, it's because it's a Beta

**Comment by LilyMakesThings** [comment]
> @LilyMakesThings If my extension is not finished, it's because it's a Beta

I was talking to Cubester

**Pull request closed without merging**
