### PR TITLE
CST1229/zip: multi-archive

### PR DESCRIPTION
**Pull request by CST1229**
A major update to the Zip extension, mainly adding support for multiple archives at a time. Marked as draft because it probably still needs bug-finding.
image

### CODE REVIEW

**Comment by Martinelplayz** [comment]
I'll do some testing

**Comment by Martinelplayz** [comment]
it works just fine for me. I haven't found any bugs since I started using it.

**Comment by Drago-Cuven** [comment]
breh ... this should have been accepted so long ago.

**Comment by LilyMakesThings** [comment]
> breh ... this should have been accepted so long ago. its useful, an upgrade from the original, and works flawlessly as far as I've seen.

merges are slower because we've all got other stuff to do.

**Pull request merged**
