### PR TITLE
Stretch (scale x and y) extension

### PR DESCRIPTION
**Pull request by TheStarWorld**
probably not the best way of making it work

### CODE REVIEW

**Comment by dinoscove** [comment]
god i love you

**Comment by GarboMuffin** [comment]
I think the big question here is what "unit" to use for how stretched a sprite is. Should "100" mean "100% of original size" (normal length) or "stretched by 100%" (double length)?

**Comment by CST1229** [comment]
> I think the big question here is what "unit" to use for how stretched a sprite is. Should "100" mean "100% of original size" (normal length) or "stretched by 100%" (double length)?

Probably "100% = original size"; that's what Scratch 1.4 used for its (unused) stretch block.

**Comment by GarboMuffin** [comment]
100

image

200

image

0

image

-100

image

-200

image

works the same in the Y direction too

**Comment by GarboMuffin** [comment]
The Scratch 1.4 stretch block only has one number that is horizontal stretch. I'm not sure if that's something we want to copy with this.

Also, Scratch 3 technically has stretch blocks, they just don't do anything. Nothing would stop us from making them do something, though

**Comment by CST1229** [comment]
> Also, Scratch 3 technically has stretch blocks, they just don't do anything. Nothing would stop us from making them do something, though

I am aware.

> The Scratch 1.4 stretch block only has one number that is horizontal stretch. I'm not sure if that's something we want to copy with this.

Of course we probably wouldn't remove vertical stretching.

**Pull request merged**
