### PR TITLE
Gallery: Change my username + link

### PR DESCRIPTION
**Pull request by LilyMakesThings**
We can tackle the extension URL problem later

### CODE REVIEW

**Comment by SurvExe1Pc** [comment]
you could just have the old ones under the old name redirect to the new one right?

**Comment by GarboMuffin** [comment]
Some things in images/README.md too

**Comment by LilyMakesThings** [comment]
> Some things in images/README.md too

Oh yes, that as well

**Comment by LilyMakesThings** [comment]
I'm struggling to edit it while on mobile, I'll make the changes in a few hours or we can just merge it as it is for now

**Comment by LilyMakesThings** [comment]
I changed the username/link credits, I did not change the file directories yet because those are where the images are stored (and because I never have to look at README anyway)

**Pull request merged**
