### PR TITLE
Add formatting workflow

### PR DESCRIPTION
**Pull request by CubesterYT**
Add a new workflow that should format a PR when a message is "!format"

Further testing by others is needed.

### CODE REVIEW

**Review by SharkPool-SP — APPROVED** [review]

**Review by Thebloxers998 — APPROVED** [review]

**Comment by CST1229** [comment]
I still think this should be a `workflow_dispatch` workflow.

**Comment by CubesterYT** [comment]
Are `workflow_dispatch`s accessible by normal people?

**Comment by GarboMuffin** [comment]
If they enable GitHub actions on their fork. Do they need to do that anyways for this to work?

**Comment by CubesterYT** [comment]
As it currently works, when the comment command is said, actions will auto format the PR, in theory. I haven't done extensive testing, so I'd like if others actually tried.

**Comment by CST1229** [comment]
> As it currently works, when the comment command is said, actions will auto format the PR, in theory. I haven't done extensive testing, so I'd like if others actually tried.

i don't think actions would allow committing on a user's branch without them enabling actions (see also: sa's autoformat action which i'm pretty sure you do have to enable actions for)

**Comment by GarboMuffin** [comment]
Ok, will just merge it and see what happens

For your reference there were a few problems with the original code

 - missing write contents permission (this entire organization is readonly by default)
 - ${{ }} inside shell script allows arbitrary shell code execution
 - not filtering to just pull request comments

**Comment by CubesterYT** [comment]
Great, this will help so much!

**Comment by Thebloxers998** [comment]
> Great, this will help so much!

Wait, but how do I use this

**Comment by Thebloxers998** [comment]
> Great, this will help so much!

Wait, but how do I use this

**Pull request merged**
