### PR TITLE
New extension (Jazzmidi)

### PR DESCRIPTION
**Pull request by ziqiangao**
Closes https://github.com/TurboWarp/extensions/issues/105

### CODE REVIEW

**Comment by GarboMuffin** [comment]
I reformatted this extension to match the guidelines -- can you see if it still works? I do not have the necessary hardware to test it myself

**Comment by ziqiangao** [comment]
you don't need hardware, you just need some software and an extension for your browser, download the software from jazzmidi
[https://jazz-soft.net/]

**Comment by horizontal-shading** [comment]
What is jazzmidi

**Comment by ziqiangao** [comment]
> What is jazzmidi

Jazz midi is a module which allows you to use midi to play notes on your computer and midi devices

**Comment by ziqiangao** [comment]
closed due to inactively, FluidSynth will be used

**Pull request closed without merging**
