### PR TITLE
S-Grab V2

### PR DESCRIPTION
**Pull request by SharkPool-SP**
Added 7 NEW BLOCKS to S-Grab that fetch useful stats about users and projects! 

Changes:
-Added Credits
-Added new blocks
-Fixed minor bugs
-Changed some og code to include commas and such (just quality of life stuff, doesn't break anything)

Screenshot 2023-07-17 223103

### CODE REVIEW

**Comment by qxsck** [comment]
> 在S-Grab中添加了7个新块，以获取有关用户和项目的有用统计信息！
> 
> 更改： - 添加了学分 - 添加了新块 - 修复了一些小错误 - 更改了一些 og 代码以包含逗号等（只是生活质量的东西，不会破坏任何东西）
> 
> 截图 2023-07-17 223103

Can users customize the maximum number?

**Comment by SharkPool-SP** [comment]
> > 在S-Grab中添加了7个新块，以获取有关用户和项目的有用统计信息！
> > 更改： - 添加了学分 - 添加了新块 - 修复了一些小错误 - 更改了一些 og 代码以包含逗号等（只是生活质量的东西，不会破坏任何东西）
> > 截图 2023-07-17 223103
> 
> Can users customize the maximum number?

No, its just to let users know that the blocks can only fetch a max of 20 users/titles. Using an input will just confuse people more.

**Comment by Martinelplayz** [comment]
(id of user (username))

**Comment by anymousuer293** [comment]
yay

**Comment by SharkPool-SP** [comment]
> (id of user (username))

 I believe someone else is adding that... might be wrong

**Comment by BlueDome77** [comment]
can you change the 20 user/title limit by editing the extension?

**Comment by SharkPool-SP** [comment]
> can you change the 20 user/title limit by editing the extension?

No, I need to let people know those blocks can only fetch the most recent 20 users/titles maximum. No more no less, sadly.

**Comment by CubesterYT** [comment]
Where's the credits?

**Comment by SharkPool-SP** [comment]
> Where's the credits?

It’s in the .js

**Pull request closed without merging**
