### PR TITLE
Cast: Add Cast

### PR DESCRIPTION
**Pull request by LilyMakesThings**
**Requires VM changes: https://github.com/TurboWarp/scratch-vm/pull/145**

Simple extension to use Scratch.Cast to convert inputs to strings, numbers, or booleans.
image

You can also get what type of value an input is.
image

Bonus: it works as a coupler for values ༼ つ ◕_◕ ༽つ
image

### CODE REVIEW

**Comment by SurvExe1Pc** [comment]
how did you get the reporter in the boolean input???
also this seems very useful

**Comment by LilyMakesThings** [comment]
Ok I'm done now :)

**Comment by SurvExe1Pc** [comment]
> Ok I'm done now :)

lol, also what does the "default" option do?

> Bonus: it works as a coupler for values ༼ つ ◕_◕ ༽つ
HOWW, its a reporter thoe. I am so confused

**Comment by LilyMakesThings** [comment]
>lol, also what does the "default" option do?


default just doesn't cast the value, which allows it to function as a coupler :)

**Comment by SurvExe1Pc** [comment]
> > lol, also what does the "default" option do?
> 
> default just doesn't cast the value, which allows it to function as a coupler :)

BUT HOW???????

**Comment by SurvExe1Pc** [comment]
i am going to have to lookup what the different between switch and if else does.

**Comment by CST1229** [comment]
> how did you get the reporter in the boolean input???

Set the `output` of the block to null in getInfo.

**Comment by LilyMakesThings** [comment]
> > > lol, also what does the "default" option do?
> > 
> > 
> > default just doesn't cast the value, which allows it to function as a coupler :)
> 
> But howw???????

When defining the block, set "isDynamic" to true, and "output" to null (in that order)!

Keep in mind, this method of achieving this does have the side effect of making any menu with "acceptReporters: false" not show up on the block, but it is the simplest method.

**Comment by LilyMakesThings** [comment]
Optional Thumbnail:
image

**Comment by LilyMakesThings** [comment]
Note: Just found this would also be ideal

**Comment by SurvExe1Pc** [comment]
> Note: Just found this would also be ideal

oml, so no more trickery lol

**Comment by GarboMuffin** [comment]
thanks for your patience

**Comment by GarboMuffin** [comment]
allowDropAnywhere is not live yet, but when it is, that part of the extension will just work

**Pull request merged**
