### PR TITLE
Add Encode and Decode URIComponent block to HTTP

### PR DESCRIPTION
**Pull request by hdboye**
Title says it all. I'm not 100% sure if this block already exists.
image
image

### CODE REVIEW

**Comment by GarboMuffin** [comment]
If we have encode that surely we should also have decode

**Comment by hdboye** [comment]
> If we have encode that surely we should also have decode

Oh yeah. Give me a second

**Comment by hdboye** [comment]
Done

**Comment by SurvExe1Pc** [comment]
these blocks do exist fyi, there in encoding

**Comment by hdboye** [comment]
> these blocks do exist fyi, there in encoding

Oh wow, I didn't know. PR closed

**Pull request closed without merging**
