### PR TITLE
Add extension 'bitwise.js'

### PR DESCRIPTION
**Pull request by RazyRabbit**
Before:
Before

After:
After

### CODE REVIEW

**Comment by GarboMuffin** [comment]
Don't combine style changes and extension changes in the same PR, all I'm interested in here is the extension so revert everything else

**Comment by RazyRabbit** [comment]
i didn't add or remove the css classes, just their attributes.

Without these changes the blocks are displayed in one line and with incorrect spacing
Before

**Comment by RazyRabbit** [comment]
Already reverted the changes in the index.html

**Comment by mollthecoder** [comment]
Ooh! A bitiwise extension! Nothing I would have ever thought about! Very neat! 👍

**Comment by mollthecoder** [comment]
But one thing I'd recommend you change before our friend GarboMuffin merges this is that you give yourself credit in index.html.

**Comment by RazyRabbit** [comment]
Thanks! But i really don't any credits

**Comment by RazyRabbit** [comment]
@GarboMuffin

**Pull request merged**
