### PR TITLE
Add "Line Direction" to Graphics2D

### PR DESCRIPTION
**Pull request by NexusKitten**
This was my first time editing an extension using Scratch.Translate, apologies if I broke anything
image

### CODE REVIEW

**Comment by Flappy25** [comment]
What is scratch.translate

**Comment by LilyMakesThings** [comment]
> What is scratch.translate

An API that allows extensions to have different translations for block text depending on the language you have selected.

**Comment by Flappy25** [comment]
> > What is scratch.translate
> 
> An API that allows extensions to have different translations for block text depending on the language you have selected.

Ok

**Comment by NOname-awa** [comment]
> 这是我第一次使用Scratch.Translate编辑扩展，如果我破坏了任何东西，请道歉 image

The correct translation of ray_direction is“（[x1],[y1]）到（[x2],[y2]）的方向”
After adding ray_direction, the translation of “line_section” should be changed to “（[x1],[y1]）到（[x2],[y2]）的距离”（zh）

**Comment by NexusKitten** [comment]
> > 这是我第一次使用Scratch.Translate编辑扩展，如果我破坏了任何东西，请道歉 image
> 
> The correct translation of ray_direction is“（[x1],[y1]）到（[x2],[y2]）的方向” After adding ray_direction, the translation of “line_section” should be changed to “（[x1],[y1]）到（[x2],[y2]）的距离”（zh）

Went ahead and fixed ray_direction line_section translations

**Comment by NOname-awa** [comment]
> > > 这是我第一次使用Scratch.Translate编辑扩展，如果我破坏了任何东西，请道歉 image
> > 
> > 
> > The correct translation of ray_direction is“（[x1],[y1]）到（[x2],[y2]）的方向” After adding ray_direction, the translation of “line_section” should be changed to “（[x1],[y1]）到（[x2],[y2]）的距离”（zh）
> 
> Went ahead and fixed ray_direction line_section translations

By the way, what is your native language?

**Comment by NexusKitten** [comment]
> > > > 这是我第一次使用Scratch.Translate编辑扩展，如果我破坏了任何东西，请道歉 image
> > > 
> > > 
> > > The correct translation of ray_direction is“（[x1],[y1]）到（[x2],[y2]）的方向” After adding ray_direction, the translation of “line_section” should be changed to “（[x1],[y1]）到（[x2],[y2]）的距离”（zh）
> > 
> > 
> > Went ahead and fixed ray_direction line_section translations
> 
> By the way, what is your native language?

I only speak english, I was using google translate to add the translations in the extension.

**Comment by GarboMuffin** [comment]
Any opinions on what this should return?

image

**Pull request merged**
