### PR TITLE
New image for browser fullscreen

### PR DESCRIPTION
**Pull request by veggiecan0419**
This is the new image:
browserfullscreen
It is more like the style of the other ones on the gallery.

### CODE REVIEW

**Comment by veggiecan0419** [comment]
@GarboMuffin, what do you think?

**Comment by GarboMuffin** [comment]
please provide an SVG instead of PNG if possible

**Comment by veggiecan0419** [comment]
> please provide an SVG instead of PNG if possible

@GarboMuffin We don't have an SVG. sorry

**Comment by GarboMuffin** [comment]
ok, that's fine

**Pull request merged**
