### PR TITLE
Timeutils

### PR DESCRIPTION
**Pull request by unknown07724**

### CODE REVIEW

**Comment by LilyMakesThings** [comment]
Submitting TurboWarp extensions requires a fundamental knowledge of JavaScript. Once you have learned JavaScript and are confident with the TurboWarp extension API, that's when submitting your ideas is recommended.

**Comment by GarboMuffin** [comment]
i think there's better ways to express that but yes this will not be merged on the basis that the single block it adds is not useful

**Comment by GarboMuffin** [comment]
The syntax error is because `class timeutils {` does not have a matching `}`. The `}` at the end corresponds to `wait(args) {`, so the `class timeutils {` is never closed, so it still thinks you're defining a class

(but again, fixing the syntax error does not get this into a mergeable state. we are already very backlogged on extension review and can't provide help with javascript syntax, sorry)

**Comment by unknown07724** [comment]
I am going to still work on timeutils and make another pull request as soon as I learn how to convert milliseconds to seconds via javascript

**Comment by AshimeeAlt** [comment]
I am going to assume you read what GarboMuffin and Lily said, but right now this won't be merged due to a few issues mainly being the know-how of JavaScript and the block not being necessary let alone in its own extension

> ​we are already very backlogged on extension review

> ​but yes this will not be merged on the basis that the single block it adds is not useful

Please don't make another pull request that's just this but fixed, It will save everyone a lot of time.

Get to learn the extension format and JavaScript and maybe you will make some cool stuff.

(I do not know if I am being too harsh so if so, I am sorry)


________________________________

**Comment by unknown07724** [comment]
it will have new blocks

**Comment by AshimeeAlt** [comment]
There is already a time extension, try to expand on that instead, but first please learn JavaScript if you have not 🙏

________________________________

**Comment by AshimeeAlt** [comment]
more controls, controls+, and many other older and in pr extensions have wait frames and ms, and also its still a unnecessary block + I said expand :skull:
________________________________

**Comment by unknown07724** [comment]
3 blocks, 1.0 is done(I used chatGPT and fixed any errors it made)

**Comment by AshimeeAlt** [comment]
AI made extensions are forbidden
________________________________

**Comment by unknown07724** [comment]
the contributing.md file doesn't say so

**Comment by unknown07724** [comment]
also I eventually gave up trying to tell the AI to do what I asked so I opened VS code and coded

**Comment by unknown07724** [comment]
plus I emailed garbo muffin and asked how to add extension and he eventually said to ask chatgpt to fix it for me

**Comment by unknown07724** [comment]
just in case that I am stupid(probably) I will remake timeutils

**Comment by AshimeeAlt** [comment]
That does not disregard the fact that ChatGPT does not know how to properly write extensions. (Same with this, and it seems the line was removed but the fact still remains https://github.com/TurboWarp/extensions/commit/b7d740b95c61818be43d20bdb079577d3bc413b4)


________________________________

**Comment by unknown07724** [comment]
That must be outdated as it added a label and 2 new blocks the problem came with color1 which isn't required

**Comment by unknown07724** [comment]
when it was on 3.5

**Comment by unknown07724** [comment]
I am making an extension to prove that chatgpt can make a extension

**Comment by AshimeeAlt** [comment]
,,, im not going to continue with you cause ChatGPT cannot make an extension correctly you are wasting your time.


________________________________

**Comment by AshimeeAlt** [comment]
I hope you have a great day day or night 👍
________________________________

**Comment by unknown07724** [comment]
yes it can

**Comment by unknown07724** [comment]
turbowarp reads it and doesn't error that is what correctly means

**Comment by GarboMuffin** [comment]
I told you to use chatgpt to help you fix syntax errors, nothing more. I do not want to be your personal JavaScript syntax checker.

**Comment by GarboMuffin** [comment]
AI can be a valuable helper and learning tool but submitting fully AI generated garbage here will not be merged and will not help you learn JavaScript.

**Pull request closed without merging**
