### PR TITLE
Add QOL and real mouse blocks based off suggestion (I think)

### PR DESCRIPTION
**Pull request by David-Orangemoon**
self explanitory

### CODE REVIEW

**Review by XeroName — APPROVED** [review]
Those are the things what I wanted! Thank you!

**Comment by Samq64** [comment]
Could you update the description to include the list of blocks you're adding?

**Comment by David-Orangemoon** [comment]
> Could you update the description to include the list of blocks you're adding?

block_7_3_2023-12_34_35 PM
block_7_3_2023-12_34_33 PM
block_7_3_2023-12_34_31 PM
block_7_3_2023-12_34_29 PM

**Comment by David-Orangemoon** [comment]
Keeping this and pen+ V6 up due to them still having the possibility of being merged

**Comment by David-Orangemoon** [comment]
Truely a moment of all time

**Comment by LilyMakesThings** [comment]
Patience is a virtue

**Pull request closed without merging**
