### PR TITLE
Update runtime-options.js

### PR DESCRIPTION
**Pull request by qxsck**
Allow the upper limit of clones to be freely modified and increase the translation of monitoring blocks.

### CODE REVIEW

**Comment by LilyMakesThings** [comment]
It already was though? If you put a join block in it you could access that.

**Comment by qxsck** [comment]
> 不过已经是这样了？如果你在其中放置一个连接块，你可以访问它。

how to use?but i think it would be more convenient for me to do this

**Comment by GarboMuffin** [comment]
you can do this already

image

the translate() fix is definitely something to merge though

**Comment by GarboMuffin** [comment]
the text-inputs-that-are-also-dropdowns inputs would be a better way to add the clone limit input

**Comment by qxsck** [comment]
> you can do this already
> 
> image
> 
> the translate() fix is definitely something to merge though

thanks

**Pull request merged**
