### PR TITLE
Cheat Codes extension

### PR DESCRIPTION
**Pull request by samuellouf**
Easily add cheat codes to your code.

### CODE REVIEW

**Comment by FurryR** [comment]
Please consider using `ioDevices.keyboard` instead of `document.addEventListener`.

**Comment by EmimalayaYT** [comment]
This one is actually very useful to me, thx!

**Comment by CubesterYT** [comment]
image
Ok but what stops you from using this block from Makey Makey? It does the exact same thing, but a whole lot simpler.

**Comment by yuri-kiss** [comment]
Closing for the above issue.

**Pull request closed without merging**
