### PR TITLE
Update Canvas Effects

### PR DESCRIPTION
**Pull request by SharkPool-SP**
Adds these blocks:
image

Modified Scale so it can be on the X or Y axis:
image

Also Modifies code to be simpler

### CODE REVIEW

**Comment by CubesterYT** [comment]
What

**Comment by SharkPool-SP** [comment]
> What

shovel told me to close it

**Comment by CubesterYT** [comment]
@SharkPool-SP, Why so?

**Comment by SharkPool-SP** [comment]
> @SharkPool-SP, Why so?

dms

**Comment by Skyhigh173** [comment]
Hmm

**Comment by GarboMuffin** [comment]
superseded by https://github.com/TurboWarp/extensions/pull/1262

**Pull request closed without merging**
