### PR TITLE
Part 2 of LilyMakesThings rename

### PR DESCRIPTION
**Pull request by GarboMuffin**
Renaming extension files creates permanent bloat -- it's not something we're going to do often.

### CODE REVIEW

**Comment by LilyMakesThings** [comment]
> @LilyMakesThings I assume you want LilyMakesThings instead of LukeManiaStudios for your URLs, yes? This is a one-time thing, so try to get it right, I don't want to do it again (every rename creates a lot of bloat)

Yes, that would be wonderful

**Comment by LilyMakesThings** [comment]
Changing it to just "lily" would almost future proof it, but part of me wonders if that's too generic

**Comment by GarboMuffin** [comment]
first come first  serve, why not

**Comment by LilyMakesThings** [comment]
> first come first serve, why not
> 
> do you want it?

yes please!

**Comment by LilyMakesThings** [comment]
Will this hold up on desktop/desktop beta?

**Comment by SurvExe1Pc** [comment]
wouldn't it be easier to just move all the request to the "/LukeManiaStudios" path to the new path instead of manually defining every extension, basically like Forwarding with masking?

**Comment by LilyMakesThings** [comment]
> wouldn't it be easier to just move all the request to the "/LukeManiaStudios" path to the new path instead of manually defining every extension, basically like Forwarding with masking?

this option allows the folder to be renamed, which is honestly more comfortable

**Pull request merged**
