### PR TITLE
New extension: Browser fullscreen

### PR DESCRIPTION
**Pull request by veggiecan0419**
Blocks to interact with the browsers fullscreen
picture of the blocks

### CODE REVIEW

**Comment by CubesterYT** [comment]
This extension isn't necessary as my upcoming extension named Window Controls already has Fullscreen related blocks. #708

**Comment by veggiecan0419** [comment]
> This extension isn't necessary as my upcoming extension named Window Controls already has Fullscreen related blocks. #708

@CubesterYT 
So should we remove it from the `index.ejs`?

**Comment by NexusKitten** [comment]
> > > This extension isn't necessary as my upcoming extension named Window Controls already has Fullscreen related blocks. #708
> > 
> > 
> > @CubesterYT So should we remove it from the `index.ejs`?
> 
> @veggiecan0419, no way for me to say this without making it feel upfront or something, but this extension is just not needed at all since Window Controls has these functions. I guess there's nothing I can think since you asked what we should do, but the only thing I can think of is for you to close the PR.
I feel as if closing the PR isn't necessary. As I said on your pull request, I believe fullscreen blocks would fit better in their own extension anyways, and considering this one already has a description + thumbnail, I feel like it's worth keeping up. Ultimately, it's up to @GarboMuffin on whether he adds this or not.

**Comment by LilyMakesThings** [comment]
I would kinda like an extension for just fullscreen since, to be frank, window controls is a bit of a mess palette-wise. So many unnecessary motion blocks

**Comment by CubesterYT** [comment]
> I would kinda like an extension for just fullscreen since, to be frank, window controls is a bit of a mess palette-wise. So many unnecessary motion blocks

@LilyMakesThings What do you mean by "unnecessary"? All blocks in Window Controls are necessary, without any of the ones in the current palette, there's no reason for Window Controls to exist. All blocks are based of their own "window." or "window.document." apis, meaning they have to exist. The blocks in the palette have their own reasons of existing and working out. Instead, there's so much I haven't added to Window Controls yet, that it's mind boggling. It would be perfect to say that Window Controls will soon be an extension with the most blocks in the entirety of all the extensions available when I'm done with it. Not by bloating, but by adding everything a user needs to or is available to use for a window. Having fullscreen in Window Controls was one of my main priorities. Having it separate just makes no sense. If you want me to explain every bit of Window Controls to you, speak to me directly in Discord. I didn't appreciate it when you called so many of the blocks that are the core of Window Controls "unnecessary". Frankly I felt hurt. There's more I want to say, but this is a GitHub PR page, it's best to stay professional, tell me anything you want to tell me on Discord, I will answer everything and my own defense on things.

**Comment by NexusKitten** [comment]
> > I would kinda like an extension for just fullscreen since, to be frank, window controls is a bit of a mess palette-wise. So many unnecessary motion blocks
> 
> @LilyMakesThings What do you mean by "unnecessary"? All blocks in Window Controls are necessary, without any of the ones in the current palette, there's no reason for Window Controls to exist. All blocks are based of their own "window." or "window.document." apis, meaning they have to exist. The blocks in the palette have their own reasons of existing and working out. Instead, there's so much I haven't added to Window Controls yet, that it's mind boggling. It would be perfect to say that Window Controls will soon be an extension with the most blocks in the entirety of all the extensions available when I'm done with it. Not by bloating, but by adding everything a user needs to or is available to use for a window. Having fullscreen in Window Controls was one of my main priorities. Having it separate just makes no sense. If you want me to explain every bit of Window Controls to you, speak to me directly in Discord. I didn't appreciate it when you called so many of the blocks that are the core of Window Controls "unnecessary". Frankly I felt hurt. There's more I want to say, but this is a GitHub PR page, it's best to stay professional, tell me anything you want to tell me on Discord, I will answer everything and my own defense on things.

Let's move this conversation back to #708.
It would be appreciated if OP could mark this post and the previous post as "off-topic".

**Comment by GarboMuffin** [comment]
Made redundant by #708

**Comment by LilyMakesThings** [comment]
Yay!!

**Review by BananaBake — COMMENTED** [review]
:(

**Pull request merged**
