### PR TITLE
Added PenguinMod's "Operators Expansion" extension

### PR DESCRIPTION
**Pull request by samuellouf**
I recreated "Operators Expansion" – a [PenguinMod](https://penguinmod.site/) extension – for TurboWarp
I based on [the extension's source code](https://github.com/PenguinMod/PenguinMod-Vm/blob/develop/src/extensions/pm_operatorsExpansion/index.js) to make it usable on TurboWarp.

[Test it](https://turbowarp.org/editor?extension=https://samuellouf.github.io/TurboWarpSandboxedExtensions/operations-expensions.js)

### CODE REVIEW

**Comment by LilyMakesThings** [comment]
This is made obsolete by 3 existing extensions: Text, Math and Utilities, that add these blocks with even more blocks. Porting this is unnecessary

**Comment by horizontal-shading** [comment]
To be honest PenguinMod feels like Turbowarp with 61 unsandboxed extensions altogether

**Comment by samuellouf** [comment]
Ok

**Comment by samuellouf** [comment]
I'm closing this pull request.

**Pull request closed without merging**
