### PR TITLE
Geolocation Extension

### PR DESCRIPTION
**Pull request by familycomicsstudios**
well yeah

### CODE REVIEW

**Comment by LilyMakesThings** [comment]
Please read the contributing guidelines before you submit an extension.

**Comment by hdboye** [comment]
https://github.com/TurboWarp/extensions/blob/master/CONTRIBUTING.md
Please read and modify

**Comment by samuellouf** [comment]
I had the same idea a while ago, I think you need to return only the city/country but not the exact location.

**Comment by CubesterYT** [comment]
No, returning the exact coordinates is fine as long as it prompts users that location will be used. It was said in your PR as well.

**Pull request closed without merging**
