### PR TITLE
Block to output data uri for media files

### PR DESCRIPTION
**Pull request by TheShovel**
Adds a block that outputs data url for files.

### CODE REVIEW

**Comment by TheShovel** [comment]
This is related to #149  and #172

**Comment by softedco** [comment]
You mean data uri?

**Comment by TheShovel** [comment]
> You mean data uri?

Yeah. I actually thought it was url until now because in js it is called dataurl.

**Comment by GarboMuffin** [comment]
we will use an alternative approach by adding blocks like these:

image

which is also future-proof if we ever want a pure base64 option or whatever else

for now there will be some redundancy in here with the old blocks, but that's okay, eventually we can find a way to make the old blocks keep working but without being listed in the flyout

**Pull request merged**
