### PR TITLE
Update and add extension images

### PR DESCRIPTION
**Pull request by GarboMuffin**

### CODE REVIEW

**Comment by Xeltalliv** [comment]
New cursors image uses `image-rendering:optimizeSpeed` to look pixelated, which works in Firefox, but doesn't in Chromium.

**Comment by Skyhigh173** [comment]
JSON extensions
can you please add this as json extension img

**Comment by True-Fantom** [comment]
@GarboMuffin I'm sorry for the delay. I lost almost all the images and had to look for them again.

Stretch: [arrows](https://icon-icons.com/ru/%D0%B7%D0%BD%D0%B0%D1%87%D0%BE%D0%BA/%D0%A0%D0%B0%D0%B7%D0%BC%D0%B5%D1%80-%D1%81%D1%82%D1%80%D0%B5%D0%BB%D0%BA%D0%B8/83819), [dango](https://twemoji.twitter.com/)([CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/)), [background](https://app.haikei.app/)
Gamepad: [gamepad](https://www.vhv.rs/viewpic/hbbiTiJ_video-game-controller-svg-png-download-game-controller/), [background](https://app.haikei.app/)
Files: [files](https://icon-icons.com/ru/%D0%B7%D0%BD%D0%B0%D1%87%D0%BE%D0%BA/%D1%84%D0%B0%D0%B9%D0%BB-%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%82-PDF/153412), [folder](https://commons.wikimedia.org/wiki/File:Folder_open_alt_font_awesome.svg), [dango](https://twemoji.twitter.com/)([CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/)), music_notes(Scrath 3), [arrows](https://icon-icons.com/ru/%D0%B7%D0%BD%D0%B0%D1%87%D0%BE%D0%BA/%D0%BF%D0%BE%D0%B2%D1%82%D0%BE%D1%80-%D1%81%D1%82%D1%80%D0%B5%D0%BB%D0%BA%D0%B0-2/56891), [background](https://bgjar.com/rect-light)
Mouse_Cursor: [cursors12](https://commons.wikimedia.org/wiki/File:Mouse-cursor-hand-pointer.svg), [cursor3](https://commons.wikimedia.org/wiki/File:%D0%9A%D1%83%D1%80%D1%81%D0%BE%D1%80_%22%D0%97%D0%B0%D0%BD%D1%8F%D1%82%22.png), [background](https://app.haikei.app/)
Math: [blackboard](https://svgsilh.com/ru/image/1295632.html), [ruler](https://svgsilh.com/ru/image/1299312.html), [compass](https://svgsilh.com/ru/image/154075.html), [formula](https://en.wikipedia.org/wiki/Binary_logarithm#/media/File:Binary_logarithm_plot_with_ticks.svg), [background](https://superdesigner.co/tools/patterns)
Couplers: blocks(Scrath 3), [microschemes](https://www.svgrepo.com/svg/278922/chip-microchip), [adapter](https://www.onlinewebfonts.com/icon/562040), [0](https://commons.wikimedia.org/wiki/File:US_0.svg), [1](https://ru.wikipedia.org/wiki/%D0%A4%D0%B0%D0%B9%D0%BB:Eo_circle_red_number-1.svg), [background](https://bgjar.com/circuit-board)
Clipping_&_Blending: [dango](https://twemoji.twitter.com/)([CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/)), [stars](https://icon-icons.com/ru/%D0%B7%D0%BD%D0%B0%D1%87%D0%BE%D0%BA/%D0%B7%D0%B2%D0%B5%D0%B7%D0%B4%D0%B0/64489), [box](https://icon-icons.com/ru/%D0%B7%D0%BD%D0%B0%D1%87%D0%BE%D0%BA/%D1%8D%D0%BA%D1%80%D0%B0%D0%BD-%D0%B2%D1%8B%D1%80%D0%B5%D0%B7%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%BF%D0%BE%D0%BB%D0%BD%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9/199719), [&](https://uxwing.com/and-icon/)
Camera_Controls: [box](https://icon-icons.com/ru/%D0%B7%D0%BD%D0%B0%D1%87%D0%BE%D0%BA/%D0%BF%D1%80%D0%B8-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B8-%D0%A7%D0%B5%D1%80%D0%BD%D1%8B%D0%B9-%D0%BA%D0%B2%D0%B0%D0%B4%D1%80%D0%B0%D1%82-%D0%BA%D0%BD%D0%BE%D0%BF%D0%BA%D0%B0-%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D1%84%D0%B5%D0%B9%D1%81-%D0%B7%D0%BD%D0%B0%D1%87%D0%BE%D0%BA/73101), [dango](https://twemoji.twitter.com/)([CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/)), [camera](https://commons.wikimedia.org/wiki/File:Camera-icon-estilizado.svg), [background](https://bgjar.com/animated-shape)
Custom_Extensions: [?](https://creazilla.com/ru/nodes/46807-vosklitsatelnyy-i-voprositelnyy-znaki-clipart)([Creative Commons Attribution 4.0](https://creativecommons.org/licenses/by/4.0/))
TurboWarp_Gallery: none
TurboWarp_Blocks: [tools](https://svgsilh.com/ru/image/1294338.html), [gears](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHDiS3KldfRdGORJ-TWF96ZM3fcKTcrV-WNg&usqp=CAU)

**Comment by True-Fantom** [comment]
@GarboMuffin Oh, and you can replace image of Clipping_&_Blending with a [centralized one](https://github.com/TurboWarp/extensions/issues/90#issuecomment-1460388495)

**Comment by GarboMuffin** [comment]
Thanks

In the future, keep in mind:

 - I had to replace https://www.vhv.rs/viewpic/hbbiTiJ_video-game-controller-svg-png-download-game-controller/ because "personal use only" is not GPL compatible
 - I had to replace https://commons.wikimedia.org/wiki/File:Folder_open_alt_font_awesome.svg because CC-BY-SA 3.0 is not GPL compatible (CC-BY-SA 4.0 and the non-sharealike creative commons are probably okay, just not older versions of CC-BY-SA)

**Comment by True-Fantom** [comment]
@GarboMuffin 

> * I had to replace https://www.vhv.rs/viewpic/hbbiTiJ_video-game-controller-svg-png-download-game-controller/ because "personal use only" is not GPL compatible

When I downloaded this image, site was not working, and I had to take it from the preview and process it. I'm sorry that I didn't look at the license when site started.

> * I had to replace https://commons.wikimedia.org/wiki/File:Folder_open_alt_font_awesome.svg because CC-BY-SA 3.0 is not GPL compatible (CC-BY-SA 4.0 and the non-sharealike creative commons are probably okay, just not older versions of CC-BY-SA)

Sorry for that, probably didn't see it

> * I had to replace the gear icon from https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHDiS3KldfRdGORJ-TWF96ZM3fcKTcrV-WNg&usqp=CAU because it is unclear what its license is

Okay

**Pull request merged**
