### PR TITLE
Write extension documentation in markdown

### PR DESCRIPTION
**Pull request by GarboMuffin**
Allows converting the current HTML extension documentation to Markdown instead, which is much easier to read, write, and edit (for humans). The scratchblocks code is now just in the markdown too. Compare the experience of trying to read or edit these:

 - https://raw.githubusercontent.com/TurboWarp/extensions/611677fd5e8e17b91209067227fcf2fe0f2b724f/docs/bitwise-new.md
 - https://raw.githubusercontent.com/TurboWarp/extensions/611677fd5e8e17b91209067227fcf2fe0f2b724f/website/bitwise.html

Remaining questions are,

 - finding ways to reduce how long scratchblocks takes to load
 - figuring out how to make extension icons work in a reasonable way

### CODE REVIEW

**Comment by SurvExe1Pc** [comment]
i like this idea.

**Comment by XeroName** [comment]
Can't wait for it!
Scratchblocks in markdown looks really cool 🎉

**Comment by LilyMakesThings** [comment]
omg I might actually write documentation for my extensions now

**Comment by GarboMuffin** [comment]
not completely satisfied with this but I still this is a massive improvement for the editing experience

**Pull request merged**
