### PR TITLE
steamworks: extension part

### PR DESCRIPTION
**Pull request by GarboMuffin**
also https://github.com/TurboWarp/packager/pull/880

### CODE REVIEW

**Comment by Drago-Cuven** [comment]
ooh? what's this?

**Comment by LilyMakesThings** [comment]
thank you garbo, very cool

**Comment by YogaindoCR** [comment]
Can't wait to see TurboWarp being a popular game engine!

**Comment by idris-x86** [comment]
noticed it doesn't have a thumbnail, so I made one
Non-Logo Design

**Comment by CubesterYT** [comment]
This isn't the place to comment that, there is a dedicated issue in the issues page to post thumbnails.

**Comment by idris-x86** [comment]
> This isn't the place to comment that, there is a dedicated issue in the issues page to post thumbnails.

Ya, I couldn't find it though.

**Pull request merged**
