### PR TITLE
New extension: UltraWarp

### PR DESCRIPTION
**Pull request by ClaytonTDM**
An extension to play [UltraBox](https://ultraabox.github.io/)/[BeepBox](https://beepbox.co) songs. UltraBox was chosen since it's compatible with a multitude of BeepBox mods, including [JummBox](https://jummb.us/).

### CODE REVIEW

**Comment by CodeFoxy-Github** [comment]
Validate / lint (pull_request)

**Comment by CodeFoxy-Github** [comment]
delete length registerShelfCenter chipWaveCompletionFadeLength samplesInPeriod stride makeLabel

**Comment by CodeFoxy-Github** [comment]
remove \#

**Comment by DogeisCut** [comment]
I already made this. https://github.com/TurboWarp/extensions/pull/1044

**Comment by ClaytonTDM** [comment]
oh, i didn't even realize that
sorry 🙏

**Pull request closed without merging**
