### PR TITLE
Add Color Picker extension

### PR DESCRIPTION
**Pull request by TheShovel**
A extension that let's you access your system color picker.
image
image
image
image

### CODE REVIEW

**Comment by horizontal-shading** [comment]
Nice :)

**Comment by horizontal-shading** [comment]
AAAHHH 666!!!!!!!

**Comment by TheShovel** [comment]
Wait! Don't push this yet! I found a way to position the color picker!
I'm going to implement it tomorrow. Going to draft this for now.

**Comment by SurvExe1Pc** [comment]
> Wait! Don't push this yet! I found a way to position the color picker! I'm going to implement it tomorrow. Going to draft this for now.

interesting..

**Comment by SurvExe1Pc** [comment]
I have an idea, i think you should add a hex option.

**Comment by TheShovel** [comment]
> I have an idea, i think you should add a hex option.

I can't. This is the system color picker. Every OS has a different one. I can't modify that.

**Comment by SurvExe1Pc** [comment]
like have a hex output, you could just turn the rgb into hex

**Comment by TheShovel** [comment]
> like have a hex output, you could just turn the rgb into hex

There is one already! Look at the pictures on the top!

**Comment by SurvExe1Pc** [comment]
im dumb lol sorry for the inconvenience

**Comment by GalacticCoder922** [comment]
I use ChromeOS.
The moving color picker blocks do not work. And whenever I click a block other than "show color picker", the color picker disappears.

**Comment by TheShovel** [comment]
> I use ChromeOS. The moving color picker blocks do not work. And whenever I click a block other than "show color picker", the color picker disappears.

The color picker disappearing is normal behavior. The color picker not moving is odd. I am on Linux (Pop_OS) and it works fine.
Mind showing me the console after you set the position?

**Comment by GalacticCoder922** [comment]
How do you access the console?

**Comment by Flappy25** [comment]
> How do you access the console?

If you don't know how to than why are you here

**Comment by TheShovel** [comment]
> How do you access the console?

Press CTRL+SHIFT+i and it will bring up the inspect element menu. After that, click on the console tab.

**Comment by GalacticCoder922** [comment]
I can't click "Inspect" on TurboWarp. It darkens it off and does nothing when clicked.

**Comment by GalacticCoder922** [comment]
I also tried Ctrl-Shift-I and it did nothing.

**Comment by SurvExe1Pc** [comment]
> I also tried Ctrl-Shift-I and it did nothing.

have you tried fn+f12 or f12?

**Comment by GalacticCoder922** [comment]
I actually figured it out and it said nothing.

**Comment by SurvExe1Pc** [comment]
weird

**Comment by GalacticCoder922** [comment]
I don't have "F12" on my keyboard, SurvExe1Pc!

**Comment by SurvExe1Pc** [comment]
what, why?

**Comment by GalacticCoder922** [comment]
I have a Chromebook.

**Comment by horizontal-shading** [comment]
Is this pull request popular because it's 666?

**Comment by SurvExe1Pc** [comment]
idk, but aughhhhhhhhh chromebook is evillll

**Comment by GalacticCoder922** [comment]
No it's not! I had a bad one before Christmas 2022, but now I have a good one! Chromebooks are worth it!

**Comment by Flappy25** [comment]
> idk, but aughhhhhhhhh chromebook is evillll

Yeah, all you need to do is jailbreak the Chromebook into Linux

**Comment by GalacticCoder922** [comment]
I can't!

**Comment by LilyMakesThings** [comment]
Please can we take this conversation elsewhere, such as the issues or discussion pages :)

**Comment by BlueDome77** [comment]
> AAAHHH 666!!!!!!!

lol

**Comment by GarboMuffin** [comment]
I will merge when the icon works better in light mode

image

**Pull request merged**
