### PR TITLE
Add Recording.js

### PR DESCRIPTION
**Pull request by SIPC**
image

### CODE REVIEW

**Comment by SIPC** [comment]
[Inspired by](https://github.com/TurboWarp/extensions/issues/422)

**Comment by LukeManiaStudioss** [comment]
You legend, this is incredible

**Comment by Skyhigh173** [comment]
> image
> 
> 

"Download as waw"
It should be wav lol

**Comment by SIPC** [comment]
> > image
> 
> “停止录制并下载哇”应该是wav lol

Take a look at the 2nd picture（）

**Comment by GarboMuffin** [comment]
Extension's menuIconURI works poorly in light mode (basically invisible). Either we can fix that icon or just use the normal colored dot.

**Comment by Martinelplayz** [comment]
maybe since sensing+ hid their sound blocks you could use this? i'd love to be able to tell what the player is saying to make a game like midnight evil.

https://www.youtube.com/watch?v=L5dD35qKiW4

**Comment by GarboMuffin** [comment]
I will merge this but not list it on the homepage in its current state, at least until some more blocks are added to make this more generally useful

**Comment by GarboMuffin** [comment]
Being able to save recordings somewhere would be a necessity for that, for example

**Pull request merged**
