### PR TITLE
Web & Device Extension by InfinityLoop (accidentally closed)

### PR DESCRIPTION
**Pull request by InfinityLoop1**
oops i didn't realize changing the branch would close the pull request
ah well ill take this as an opportunity to update some stuff on explanation

<h1>Web & Device</h1>
<h2>Created by InfinityLoop</h2>

Web & Device is an extension created by InfinityLoop (InfinityLoopGaming on Scratch), to interact and get data from websites, your device, and your network.

Features include:
- Change & get page title
- Get network stats
- Get browser, OS, and memory stats
- Toggle & get fullscreen
- Open and redirect tabs, get current tab, get data from URL
- Get screen width/height
- Get and set clipboard
- Get battery stats and events

><b>Note</b>
>By the way, All of these blocks exist in other extensions. This extension is meant to combine very similar extensions, like FETCH, Navigator Info, and Network. Because it would be easier to have these all in one, instead of having to install 2 or 3 extensions to do what you want, or having to find those extensions in a long list. I wasn't aware of the “no combination extensions” rule before I had started making this extension, because this is my first extension.

### CODE REVIEW

**Comment by InfinityLoop1** [comment]
oh get a life sharkpool there is no reason for you to keep saying that this extension is bad
Oh ExTeNsIoN iS bAd MuSt PuT tHuMbS dOwN eMoJi
i have already stated the use of this extension and even garbomuffin said "centralizing some of the random ones into an extension that people will actually be able to find is not a bad idea"
stop whining, this isn't your place to complain

**Comment by LilyMakesThings** [comment]
> oh get a life sharkpool there is no reason for you to keep saying that this extension is bad Oh ExTeNsIoN iS bAd MuSt PuT tHuMbS dOwN eMoJi i have already stated the use of this extension and even garbomuffin said "centralizing some of the random ones into an extension that people will actually be able to find is not a bad idea" stop whining, this isn't your place to complain

Please respect the opinions of others if you're going to make a public contribution to an open source repository.

And try to be mature while you do it.

**Comment by SharkPool-SP** [comment]
> oh get a life sharkpool there is no reason for you to keep saying that this extension is bad Oh ExTeNsIoN iS bAd MuSt PuT tHuMbS dOwN eMoJi i have already stated the use of this extension and even garbomuffin said "centralizing some of the random ones into an extension that people will actually be able to find is not a bad idea" stop whining, this isn't your place to complain

https://media1.tenor.com/m/mASTInk_y9IAAAAC/crying-baby.gif

**Comment by InfinityLoop1** [comment]
I don’t see sharkpool being mature here either. also I don’t see a code of conduct or anything on this repo that says I have to be respectful or mature

plus, why does it take so long for extensions to get passed? I’ve seen some that are like several months old. it’s basically a yes or no question, do you want it or not

**Comment by LilyMakesThings** [comment]
> I don’t see sharkpool being mature here either. also I don’t see a code of conduct or anything on this repo that says I have to be respectful or mature
> 
> plus, why does it take so long for extensions to get passed? I’ve seen some that are like several months old. it’s basically a yes or no question, do you want it or not
> 
> update: 9 months? just close it or merge it damn

You need a code of conduct tell you to be respectful and mature?

**Comment by GarboMuffin** [comment]
This pull request tracker is not the place to tell other users to get a life or post discord gifs. If you need a code of conduct to tell you that then this is not the place for either of you.

Extension review is slow and awful. We all know that. You can read "Important context" in the contributing guidelines for some insight on that. (You looked for a code of conduct, so surely you already saw the contributing guidelines document which outlines that everyone here is a volunteer. Do you also tell real life volunteers to "get a life"? I hope not)

**Pull request closed without merging**
