### PR TITLE
Create easycode1.js

### PR DESCRIPTION
**Pull request by LegoJohnny2013**
I just made this account after realizing that I will need a github account to add extensions to turbowarp 
edit: I added testing mode to easycode today

### CODE REVIEW

**Comment by LegoJohnny2013** [comment]
Just place easycode wherever

**Comment by SharkPool-SP** [comment]
This is just a bunch of utilites that already exist. Additionally Utility extensions arent allowed on the gallery.
Another note, you added the chat GPT extension from @cicerorph , which you probably didnt ask permission for, and is also not allowed on the gallery

**Comment by LegoJohnny2013** [comment]
I credited them isn't that enough the only extension that you have on penguinmod and turbowarp is font manager

**Comment by SharkPool-SP** [comment]
> I credited them isn't that enough the only extension that you have on penguinmod and turbowarp is font manager

Id rather you not start arguments about whos on the gallery. The main point is credit does not mean permission.

**Comment by LegoJohnny2013** [comment]
I should probably add buttons that link to their github and scratch accounts to be honest

**Comment by GarboMuffin** [comment]
as you have been informed above, we do not need more broad utilities extensions

**Comment by LegoJohnny2013** [comment]
It took like 6 months creating it

**Comment by LegoJohnny2013** [comment]
people are hooraying him because they probably hate me

**Comment by CubesterYT** [comment]
Okay, look, nobody said they hate you. We shit down this PR because it's blatantly against our extension policy here. Moreover your harrasing another member of the community on the number of extensions they have merged. We explicitly are here to give you feedback, and you assume we're just here to make fun of you.

**Comment by LegoJohnny2013** [comment]
I credited them even more because I ain't getting sued and because they deserve to be given status in the extension

**Comment by LegoJohnny2013** [comment]
Harassing is like spamming people's DMs
I only told him that once

**Comment by LegoJohnny2013** [comment]
> This is just a bunch of utilites that already exist. Additionally Utility extensions arent allowed on the gallery. Another note, you added the chat GPT extension from @cicerorph , and other extensions from other people which you probably didnt ask permission for, and is also not allowed on the gallery

if it is open source then it isn't stealing + developers do this all the f#cking time

**Comment by LegoJohnny2013** [comment]
> > This is just a bunch of utilites that already exist. Additionally Utility extensions arent allowed on the gallery. Another note, you added the chat GPT extension from @cicerorph , and other extensions from other people which you probably didnt ask permission for, and is also not allowed on the gallery
> 
> if it is open source then it isn't stealing + developers do this all the f#cking time

do you relilze that almost everyone copied chromium and that isn't stealing

**Comment by GarboMuffin** [comment]
Hi again legojohnny. 

I know you are new to programming and trying to have some fun and make a mark, that's great. If you like this extension a lot then keep using it as a custom one or share it around on other sites -- that's also great. We can't stop you and in fact encourage you to do that.

However the bar for getting things into this repository is quite high. We are expected to maintain everything that gets merged forever, otherwise real projects by real people break. I also cover everything in here under a [bug bounty program](https://github.com/TurboWarp/extensions/security/policy) so merging carelessly will directly impact my bank account. This isn't a playground anymore, it is a real project relied on by real people.

In the past we have fixed bugs in places such as the clipboard extension and then [forgotten to copy and paste the fix](https://github.com/TurboWarp/extensions/pull/636) to the other extensions that also have a "read clipboard" block. That's not maintainable. It's also a major discoverability issue: if someone is looking for a ChatGPT extension would you expect them to check an extension called "EasyCode" which describes itself as "Adds Lots and Lots of Blocks like Alert and Change Tab Title"? Seems unlikely. As such [broad utilities extensions aren't allowed anymore](https://github.com/TurboWarp/extensions/blob/master/CONTRIBUTING.md#acceptance-criteria), as noted in the contribution guidelines. If you wanted to break this into smaller pieces and submit them separately and with enough depth, we can talk about those (As an example, an extension that just has a "capitalize text" block wouldn't be accepted, but one that has a lot of blocks that deal with text case could. But please don't submit that, it already exists).

Aside from the extension, your conduct on this pull request has been unacceptable. I am not yet blocking you because I trust you can adjust your behavior in the future. But I want to be clear that:

- If someone criticizes something you wrote and you disagree, debate the *idea* not the *character*. Saying "the only extension that you have on penguinmod and turbowarp is font manager" is a [logical fallacy](https://en.wikipedia.org/wiki/Ad_hominem) that does not address the points being made
- One message can be enough to be "harassment"
- Many software licenses exist, and "open source" does not mean "do anything". I don't know what license the ChatGPT extension you used is under, but even permissive licenses often require you to keep a notice around giving the author credit and including the text of the license you used the code under.
- If you were concerned enough about swearing being received poorly here that you partially concerned it, then maybe you just shouldn't say it at all?

**Pull request closed without merging**
