### PR TITLE
Add Window Utils.js

### PR DESCRIPTION
**Pull request by BlueDome77**
This is my first PR

### CODE REVIEW

**Comment by CubesterYT** [comment]
*sigh* There goes another extension I was already working on...

**Comment by LilyMakesThings** [comment]
> _sigh_ There goes another extension I was already working on...

That's ok! Once this extension is merged you can make a pull request to add your blocks :)

**Comment by NexusKitten** [comment]
Why was this closed?

**Comment by CubesterYT** [comment]
@NexusKitten I will be reuploading it, me and BlueDome collaborated on a new one, with his one, and a ton of additions I added, such as new blocks, an icon, a new color scheme, and more.

**Pull request closed without merging**
