### PR TITLE
A custom sprite shader

### PR DESCRIPTION
**Pull request by promissame**
I don't think this thing will work perfectly for all operating environments, but at least for me I used it successfully and achieved the results I wanted

### CODE REVIEW

**Comment by LilyMakesThings** [comment]
My immediate impression of this is that it doesn't take into consideration other extensions that mess with the renderer like clipping and blending.

The fact you've also admitted this might not work in all environments suggests to me this shouldn't be merged and should be kept as a private one off extension.

**Comment by promissame** [comment]
Okay, thanks for the reply, I might take the time to change this extension to be compatible with most rendering extensions.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TurboWarp/extensions"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月29日(星期五) 晚上7:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TurboWarp/extensions] A custom sprite shader (PR #1064)





 
My immediate impression of this is that it doesn't take into consideration other extensions that mess with the renderer like clipping and blending.
 
The fact you've also admitted this might not work in all environments suggests to me this shouldn't be merged and should be kept as a private one off extension.

**Comment by promissame** [comment]
Now this extension will be compatible with basically all the rendering extensions I have tested and know so far, and implement different sprites with different parameters, which may be an important and huge breakthrough for TurboWarp's rendering extension

**Comment by snowboyz0825** [comment]
did you make it hard coded for it to be compatible or soft coded (soft coded sounds weird, but it's the best I could think of) (also, adding this to the archive)

**Comment by promissame** [comment]
> did you make it hard coded for it to be compatible or soft coded (soft coded sounds weird, but it's the best I could think of) (also, adding this to the archive)
Yes, at the moment I don't have any incompatibilities with this extension, soft coding (maybe you mean writing about blocks) I can't implement it very well, so I use text to transfer code to shaders. However, it is worth mentioning that this extension will theoretically be compatible with almost all rendering and special effects extensions

**Comment by promissame** [comment]
Yes, at the moment I don't have any incompatibilities with this extension, soft coding (maybe you mean writing about blocks) I can't implement it very well, so I use text to transfer code to shaders. However, it is worth mentioning that this extension will theoretically be compatible with almost all rendering and special effects extensions




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月1日(星期天) 中午11:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TurboWarp/extensions] A custom sprite shader (PR #1064)






你做了硬编码，它是兼容或软编码（软编码听起来很奇怪，但它是我能想到的最好的）（此外，添加到存档）

-
直接回复此邮件，在GitHub上查看，或取消订阅.
***@***.***与&gt;.

**Comment by CubesterYT** [comment]
Why was this closed?

**Comment by CST1229** [comment]
> Why was this closed?

#1068 exists, don't know why they made a new PR.

**Pull request closed without merging**
