### PR TITLE
Add my IP Addresses extension

### PR DESCRIPTION
**Pull request by PPPDUD**
The IP Addresses extension contains blocks for handling public IP addresses.

### CODE REVIEW

**Comment by SharkPool-SP** [comment]
This block already exists in Cloudlink

**Comment by wolfieboy09** [comment]
I've made an extension that contains that very block

**Comment by SharkPool-SP** [comment]
> I've made an extension that contains that very block

I did too but expands on it :trollface:

**Comment by CubesterYT** [comment]
Nope, it's not possible to access private ips. Plus that ip is useless.

**Comment by PPPDUD** [comment]
Looks like this is already implemented; sorry about that, devs.

**Pull request closed without merging**
