### PR TITLE
Skyhigh173/JSON: fix json_is_valid()

### PR DESCRIPTION
**Pull request by Procybit**
The function returns false when valid checked JSON is not whitespace-trimmed. Made it check parsed type.

### CODE REVIEW

**Review by RockyTheProtogen — COMMENTED** [review]
Code no longer returns false when whitespace is introduced.
Fulfils PR but could break existing projects.

**Comment by CubesterYT** [comment]
I don't think it'll break projects considering projects would've already accounted for this bug and used non whitespace valid json

**Review by RockyTheProtogen — APPROVED** [review]
After a bit of thinking, this shouldn't really affect anything unless projects, for some reason, use a rudimentary way of reading the JSON. Though that is doubted, as the get key block is in this extension.

**Comment by GarboMuffin** [comment]
this changes the output of

image

what do you think that should output?

`true` `false` `0` `"hello"` are all valid JSON too, should those not return true here as well?

regardless this will need to be a is_valid_v2 kind of situation

**Comment by LSPECTRONIZTAR** [comment]
uh this problem is already addressed in #1212

**Comment by Skyhigh173** [comment]
Just trim trailing and leading white spaces and test it with original script

**Comment by Procybit** [comment]
So for now it just trims given JSON string before processing it

**Comment by GarboMuffin** [comment]
okay, i think these blocks need to be replaced but this should be an unambiguous improvement for now

**Pull request merged**
