### PR TITLE
Combined Gamepad Update

### PR DESCRIPTION
**Pull request by Martinelplayz**
Combination of https://github.com/TurboWarp/extensions/pull/1018 and https://github.com/TurboWarp/extensions/pull/881 .

### CODE REVIEW

**Comment by CubesterYT** [comment]
Quick question, did you ask the owners of the original PRs for permission for making this mega PR? Just a question so we can get everything in check.

**Comment by Martinelplayz** [comment]
> Quick question, did you ask the owners of the original PRs for permission for making this mega PR? Just a question so we can get everything in check.

didn't know it was neccesary. i can take it down if you want me to.

**Comment by CubesterYT** [comment]
> > Quick question, did you ask the owners of the original PRs for permission for making this mega PR? Just a question so we can get everything in check.
> 
> didn't know it was neccesary. i can take it down if you want me to.

You don't need to take it down, you can just ask the other PR owners if they will allow you to make a combined PR.

**Comment by Meehdrescher** [comment]
> You don't need to take it down, you can just ask the other PR owners if they will allow you to make a combined PR.

I don't have a problem with it :)

**Comment by LilyMakesThings** [comment]
You don't need to ask for permission, don't worry

**Comment by GarboMuffin** [comment]
things can be merged independently (at least one of those is also now superseded)

**Pull request closed without merging**
