### PR TITLE
All Menus: Add experimental "All Menus" extension

### PR DESCRIPTION
**Pull request by LilyMakesThings**
'All Menus' creates a category in the block palette with every menu of every Scratch category as well as loaded extensions.
image

Some notes about this extension:
- If the user has no other extensions loaded, the blocks from this extension are 100% compatible with Scratch.
- The extension won't save to projects because you can't technically drag extension-created blocks from the extension, as there aren't any.
- As a result of the previous statement, changes made to this extension won't be "breaking" changes. This can be deleted at any time.

### CODE REVIEW

**Comment by SurvExe1Pc** [comment]
i like this idea

**Comment by LilyMakesThings** [comment]
In theory the "refresh blocks" button could be axed, this refreshes automatically whenever an extension is loaded anyway.

**Comment by ClaytonTDM** [comment]
image
im having too much fun with this

**Comment by LilyMakesThings** [comment]
This extension has had a full rewrite, it no longer uses icky injection code.

**Comment by ClaytonTDM** [comment]
HELL YEAH

**Comment by horizontal-shading** [comment]
Thank you Lily for adding this

**Pull request merged**
